### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#1002]
Improve dark mode proposal
https://github.com/tolgee/server/pull/997

**Comment by ZuzanaOdstrcilova** [comment]
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=125%3A934

**Comment by JanCizmar** [comment]
> I know this issue mostly targets the webapp more than the website, but it may be worth including revisiting slightly the website dark theme as well which has very low contrast ratio in certain places.

It's now updated on the website!
