### ISSUE TITLE
Support for .ini files

### ISSUE THREAD

**Issue by dgrammatiko** [tolgee/tolgee-platform#1012]
I would like to request the support for `.ini` files as the source of the languages. There are plenty packages to convert the .ini files to a key-value array so this should be quite straight forward.

Thanks

**Comment by JanCizmar** [comment]
Hi there! Can you please share an example of this file?

**Comment by JanCizmar** [comment]
And also! What is your use case? What language/library do you use?

**Comment by dgrammatiko** [comment]
@JanCizmar sure, here you go: https://github.com/joomla/joomla-cms/blob/4.1-dev/language/en-GB/com_config.ini

The use case is the Joomla CMS

**Comment by JanCizmar** [comment]
@dgrammatiko Hey, we still don't support that, So why closed? 😆

**Comment by dgrammatiko** [comment]
Oh, I thought you weren't interested to support such files...

**Comment by JanCizmar** [comment]
I was thinking to plan to add some universal support via our CLI. So user would be enabled to write custom JS function, which would accept all the translation data and store it as they wish. This way we can also provide some presets for major programming languages/frameworks. https://github.com/tolgee/tolgee-cli/issues/1

**Comment by dgrammatiko** [comment]
Sounds good, thanks
