### ISSUE TITLE
Remove discord from readmes

### ISSUE THREAD

**Issue by eweren** [tolgee/tolgee-platform#1016]
It seems to point to a specific channel instead of being an invite link

**Comment by JanCizmar** [comment]
Right! We decided to remove the discrord, but we didn't remove it from the readme's. Instead, use GH discussions for now.

**Comment by JanCizmar** [comment]
@marketachalupnikova can create some public slack channel for people to join and share it's link?

**Comment by marketachalupnikova** [comment]
Hi, here is the link to Tolgee Community Slack channel: https://join.slack.com/t/tolgeecommunity/shared_invite/zt-16l0sf7ae-6fmAl2Fb9wqFCV0uzSa7bw
