### ISSUE TITLE
Api keys redesign

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1020]
Make API keys view to look nicer. 
- [ ] Replace the scopes with number of enabled scopes
- [ ] Add label so users would know which keys are used for what
- [ ] Hide key values and show just beginning and end

**Comment by ZuzanaOdstrcilova** [comment]
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=726%3A1432

**Comment by jdimeo** [comment]
Thumbs up for the 3rd checkbox! was a bit surprised it was shown without any masking... but it was more convenient to copy/paste into my config :-)

**Comment by cyyynthia** [comment]
Seems like this has been solved by #1322?
