### ISSUE TITLE
[Feature request] Responsive CSS for mobile browsers

### ISSUE THREAD

**Issue by KaKi87** [tolgee/tolgee-platform#1021]

**Comment by JanCizmar** [comment]
We know about that, but this is currently out of scope. Are you really using Tolgee on phone?

**Comment by KaKi87** [comment]
> We plan definitely plan to do that, but not now

In that case, shouldn't this issue be kept open with a `backlog` tag or something ?
> Are you really using Tolgee on phone?

Yes, I did try, that's why I submitted this issue.
