### ISSUE TITLE
Error importing .po file

### ISSUE THREAD

**Issue by RumenGeorgieff** [tolgee/tolgee-platform#1071]
I'm trying to import .po file for a WordPress plugin, but I get this error "Unknown keyword 'msgstr'"

![error-import-po-file](https://user-images.githubusercontent.com/2687942/163722185-407e5d7f-489d-48b0-9bd6-a92017cf957f.jpg)

**Comment by JanCizmar** [comment]
I found the issue. The file is exported with windows `\r\n` newlines. So it it doesn't parse the file correctly. I will fix this tomorrow morning. :)

**Comment by JanCizmar** [comment]
Hi @ralexrdz, thanks for asking! is this related to this issue, or are you just asking for general recommendation?
