### ISSUE TITLE
Error exporting json file

### ISSUE THREAD

**Issue by RumenGeorgieff** [tolgee/tolgee-platform#1072]
I'm trying to export a json file, but I get an error

![error-export-json-file](https://user-images.githubusercontent.com/2687942/163722264-149fc1f4-ccc8-4959-8d03-57106d83ad57.jpg)

**Comment by JanCizmar** [comment]
I investigated this issue. You probably have a key in your project which name starts with `.` character. We use . character as a delimiter for structuring the resulting json. Woking on fix...
