### ISSUE TITLE
Support for DeepL translations

### ISSUE THREAD

**Issue by zefixlluja** [tolgee/tolgee-platform#1115]
Currently AWS and Google are supported for machine translations - with DeepL on the roadmap for 2022Q1 (https://tolgee.io/roadmap).

Is there already existing work for DeepL integration, is it sth where the project would want some code contribution?

**Comment by JanCizmar** [comment]
Hi there. We haven't started  working on DeepL integration. However, adding support for it shouldn't be very complicated task. I can do it in next 2 weeks. Or event better feel free to contribute. :)

**Comment by zefixlluja** [comment]
Excellent - then I'm setting up my local environment accd to the wiki.

**Comment by JanCizmar** [comment]
Ask if it's not clear. :)

**Comment by zefixlluja** [comment]
Hi Jan - sorry, but I'll have to take you up on the offer. The Readme is good - I've got the backend running and UI starts a craco process on `localhost:3000`, unfortunately it gives me an error right there. I assume I'm missing some piece of configuration to point the UI to the running backend - could you help me with this?

The DeepL part itself should be pretty clear thanks to the existing aws/google implementations.

**Comment by JanCizmar** [comment]
Hey! Can you ping me via out community Slack? We can discuss it there to not spam this thread.
 
https://join.slack.com/t/tolgeecommunity/shared_invite/zt-195isb5u8-_RcSRgVJfvgsPpOBIok~IQ

Or if you prefer another servise, just let me know.
