### ISSUE TITLE
Support for LibreTranslate translations

### ISSUE THREAD

**Issue by TechnologyClassroom** [tolgee/tolgee-platform#1124]
[LibreTranslate](https://github.com/LibreTranslate/LibreTranslate) is a machine learning, API based translation service that can be self-hosted.  For the self-hosting and privacy focused crowd, adding support for LibreTranslate would be cool.

On the backend, LibreTranslate is just [Argos Translate](https://github.com/argosopentech/argos-translate) with a front-end and an API so some glue for using Argos Translate on the command line would be slightly less resource intensive, but would probably be more work to implement as the rest of the options are API integrations.

**Comment by JanCizmar** [comment]
Adding support for their REST API would be pretty simple. I have no problem to pay for their hosted API, but they don't have pricing model, which would work for me. So I created issue there and let's see.

https://github.com/LibreTranslate/LibreTranslate/issues/264

**Comment by JanCizmar** [comment]
It's not, but you I can point you to the right direction. It might be better, if we discuss that in our [Slack community](https://tolg.ee/slack).
