### ISSUE TITLE
File storage S3 configuration

### ISSUE THREAD

**Issue by juanludlf** [tolgee/tolgee-platform#1158]
Hi,

What does `tolgee.file-storage.s3.endpoint` property mean? I just found a reference on a test file https://github.com/tolgee/tolgee-platform/blob/cb12f5f4ecf162276df52b8cf782f287fca1bc75/backend/app/src/test/kotlin/io/tolgee/component/fileStorage/FileStorageS3Test.kt#L27
But I still don't understand what I have to define here.

Thanks

**Comment by wodka** [comment]
by setting it up right now service endpoints are needed on aws: https://docs.aws.amazon.com/general/latest/gr/s3.html

I also added this as PR for the docs: https://github.com/tolgee/documentation/pull/303

**Comment by JanCizmar** [comment]
> I also added this as PR for the docs: [tolgee/documentation#303](https://github.com/tolgee/documentation/pull/303)

Thanks a lot!
