### ISSUE TITLE
[Feature Request]OpenID/Oauth2 or SAML authentication

### ISSUE THREAD

**Issue by throrin19** [tolgee/tolgee-platform#1164]
Hello,

Your project lokk amazing and we are really interested to use it. But, in our case, we use an authentication service (authentik in our case) and we wonder if it is planned to be able to manage tolgee users by this way?

You manage github and google users but being able to manage users coming from any authentication service (auth0, authentik, ...) would be a great advantage.

Thanks again for the work you do

**Comment by JanCizmar** [comment]
Hello, thanks a lot. It's currently not on our roadmap. :( But if you wish, you can submit pull request providing this feature. Maybe @waigel can help. (He did a great job adding Google Auth https://github.com/tolgee/tolgee-platform/pull/1133)

**Comment by waigel** [comment]
I could try to implement oauth2. This is the current standard for connecting to external authentication service providers, I think. With this, you should be able to implement a variety of authorization services. (e.g. KeyCloak, Okta, auth0, authentik...). Unfortunately I'm out of SAML, that's a protocol before my time, I don't want to deal with it 😄.

**Comment by throrin19** [comment]
@waigel that would be great !!

For saml, I just list authent protocoles, oauth2 is perfect and enough :)

**Comment by throrin19** [comment]
After tests with Authentik, I have this error : `third_party_auth_unknown_error`

I check logs on tolgee : I saw no error.
I check logs on authentik : everything seems to be fine

**Comment by waigel** [comment]
Interesting, I will have a look at it later on

**Comment by waigel** [comment]
You are right, authentik has a very strict checking of request parameters. Missing content type in request was here the problem. Also added more logging stuff to the OAuth2Handler. PR #1193
