### ISSUE TITLE
Web UI warns when <br> tags are not closed

### ISSUE THREAD

**Issue by martinet101** [tolgee/tolgee-platform#1183]
The web UI warns when \<br> tags are present, and it only accepts changes when they are like \<br/>. This element might be confusing for some starter level users, because the <br> tag does not need to be closed in any way.

**Comment by JanCizmar** [comment]
Tolgee Platform is focusing on editing strings in ICU message format. For ICU formating, we are using Format.JS library. The HTML/XML syntax is reserved for the ["Rich text formatting feature"](https://formatjs.io/docs/core-concepts/icu-syntax/#rich-text-formatting). Or something we call ["Tag interpolation"](https://tolgee.io/docs/web/using_with_react/tags_interpolation). 

So basically there is no such thing in ICU message format thus unpaired HTML tags are not supported.

@stepan662 What do you think?

**Comment by stepan662** [comment]
Yep, we need to stick to ICU format, because we would cause incompatibilities with 3d party libraries.
