### ISSUE TITLE
Ability to delete API keys

### ISSUE THREAD

**Issue by stophecom** [tolgee/tolgee-platform#1185]
Currently it's not possible to delete API keys. I think via GUI nor via API. This could be critical if a key has been exposed. 

API Docs: https://tolgee.io/api#tag/API-keys

Might be related to https://github.com/tolgee/tolgee-platform/issues/1020

**Comment by JanCizmar** [comment]
Hello, you can delete your API key via GUI. 
1. Click your avatar in top right corner
2. Select API keys
3. Click the basket icon to delete specific API key

**Comment by stophecom** [comment]
Oh, my bad, I didn't see that 🙈. I created the API keys on the integration page and didn't realize there was another entry point to handle API keys. But it's much more obvious through settings. So again, sorry to bother :)

**Comment by JanCizmar** [comment]
No problem... Maybe it should be mentioned somewhere in the integration section.
