### ISSUE TITLE
Position chat widget on the left side

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1196]
![image](https://user-images.githubusercontent.com/18496315/173564096-51dcfd7e-08a2-4ec3-8d57-9a4f8bffdaa8.png)

**Comment by ludovicobesana** [comment]
@JanCizmar If you need some help I can take this

**Comment by JanCizmar** [comment]
That would be awesome! The reason why it's now positioned right is that when we tried to move it left it hide the menu. But if we somehow positoned the widget to not cover the menu on the left side, it would be great. The screenshot is from my conversation with the guys from chatwoot, who gave some hints.
