### ISSUE TITLE
Others authentications and users registration

### ISSUE THREAD

**Issue by throrin19** [tolgee/tolgee-platform#1200]
Actually, if the option `tolgee.authenticate.registrations-allowed` is set to false, it's impossible to connect to tolgee with new user using github/oauth2/... authentication.

In some case, if external authent service is used, it's for use only this external service without the registration. In that case, users are automatically created even if the `registrations-allowed` is false

**Comment by JanCizmar** [comment]
If the user is invited to a project, they can sign in via OAuth service, can't they?

**Comment by throrin19** [comment]
I don't find the users invite in the self-hosted part

**Comment by JanCizmar** [comment]
Enter a project > Members > Click Invite User

**Comment by throrin19** [comment]
yep it works fine. Thanks
