### ISSUE TITLE
Possibility to confirm many translations at one time

### ISSUE THREAD

**Issue by throrin19** [tolgee/tolgee-platform#1201]
It's possible to add this feature ? Like when we select many translations, in addition to the delete option (which is the only one available right now), add an option to confirm translations.

In the case we move our translation project from another part to tolgee, We have to confirm one by one the translations after import. If We have many translations, this task is really time consuming.

Thanks

**Comment by JanCizmar** [comment]
Yes, it's possible. We are definitelly adding that as a part of batch operations.

**Comment by martinet101** [comment]
Yes, this would be a nice feature to have
