### ISSUE TITLE
Projects only in organizations

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1203]
Projects are created only with Organization owner. After upgrading (after merging our current billing branch) all projects will be migrated to be in user's default organization.
- [x] Add the organization switch to user menu to select user's current organization
       The current selected organization can be fetched from backend using `/v2/preferred-organization` endpoint
- [x] The projects on the main projects list should contain only projects from the selected organization
- [x] Add organization name input if user is registering without any invitation (otherwise they probably won't need their own organization)
- [x] Project can be created only when organization is selected (so we can remove the owner selection)
- [ ] When user is not member / owner of any organization and doesn't have direct permission to any project, they should have `create organization button` instead of project list. When organization is created, the user should be automatically switched to the new organization scope and be able to create project new project in that.

**Comment by ZuzanaOdstrcilova** [comment]
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=631%3A1388
![image](https://user-images.githubusercontent.com/99287646/176829783-337bce31-ef24-4030-acce-cefe1b7ed4b8.png)
