### ISSUE TITLE
Current environment language stored on backend

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1204]
I've added endpoints to store and get current user language, so we don't have to store it in local storage. It's `GET /v2/user-preferences` and `PUT /v2/user-preferences/set-language/{languageTag}`

**Comment by jdimeo** [comment]
Is this related to #1324 at all? it would be awesome if I could set up my translator accounts via API calls and then they aren't able to change (The language selector is hidden). This is a bit of "security by obscurity" but would be an easier lift than reworking the entire permissions structure right?
