### ISSUE TITLE
[Bug] Infinite amount of "Property [...] was accessed during render but is not defined on instance" warnings

### ISSUE THREAD

**Issue by KaKi87** [tolgee/tolgee-platform#1210]
Happening as soon as `TolgeeMixin` is imported from a grandchild of `TolgeeProvider`, making the page crash (notice the scrollbar size).

![Screenshot from 2022-06-30 14-31-45](https://user-images.githubusercontent.com/21284089/176678344-49a1bc56-c51d-4921-89a9-1035b4aff401.png)

Thanks

**Comment by stepan662** [comment]
Hey, the usage of TolgeeMixin on it's own can't be the source of this bug as we are using it in our example project and it works fine https://github.com/tolgee/vue-example. I need a way how to reproduce this error.

**Comment by KaKi87** [comment]
Turns out that, although it was only happening when using Tolgee, it was due to an undefined variable used in a `v-if` attribute.

Now, I have another issue : Alt-Click doesn't work.
> Tolgee UI is not provided. To translate interactively provide tolgee ui constructor to "ui" configuration property. To disable highlighting use production mode.

It doesn't seem that there's an "ui" configuration object anywhere in your demo repo though. :thinking: 

Thanks

PS: why do your examples show usages of `$t` when using `TolgeeMixin` but `t` using `useTranslate` ?

**Comment by stepan662** [comment]
Hmm, thats weird. Are you using newest version of `@tolgee/vue`? In newest version it should be provided automatically based on your environment ...

PS: Could we please move this to our community [slack](https://join.slack.com/t/tolgeecommunity/shared_invite/zt-16l0sf7ae-6fmAl2Fb9wqFCV0uzSa7bw) or [github discussions](https://github.com/tolgee/tolgee-platform/discussions) as I don't want to clutter issues with unrelated stuff.

**Comment by KaKi87** [comment]
I pinged you on Slack.
