### ISSUE TITLE
Dashboard counts for translated/reviewed are confusing

### ISSUE THREAD

**Issue by kenske** [tolgee/tolgee-platform#1269]
Translated keys that are marked as reviewed should still count as translated. I have translated all of my keys, and yet I see "Translated 3%" because I reviewed 97%:

![image](https://user-images.githubusercontent.com/940150/181302866-87f2b15b-f6ca-4349-93e7-00fad0e9f290.png)

**Comment by JanCizmar** [comment]
Hmmm. Technically it's not a problem to do it as you suggest, but I would open a discussion about this, since I would keep it as it is. For some reason I like it more.

@stepan662 @cyyynthia

**Comment by stepan662** [comment]
It's a good point. However I like that the numbers correspond to colors next to the translations and also with charts for individual languages. Not sure how to do it to keep consistency.

**Comment by cyyynthia** [comment]
My take on that would be that the terminology used is a bit confusing. To me, it'd be reasonable to consider that a "translated" string is a string which passed the whole translation process and which is ready to ship.

I'd say that having "Pending review" and "Translated" labels respectively would better reflect the string state, and would make the most sense with how the percentages are computed and displayed.

**Comment by JanCizmar** [comment]
Hmm. IMHO the current variant is better. "pending review" would be "forcing" teams, who just ignore the review step to do the review. The translated strings are Translated, because translator translated them. Reviewed string is string which was translated by translator *and* reviewed by reviewer/proofreader. Thats it.

**Comment by JanCizmar** [comment]
Sorry, I am closing it now. Maybe we will reopen it when more user's will express their confusion in feedback. Otherwise it's out of scope for now. 🥛
