### ISSUE TITLE
Allow setting formality for AWS Translate

### ISSUE THREAD

**Issue by kenske** [tolgee/tolgee-platform#1270]
The AWS Translate API supports a [Formality](https://docs.aws.amazon.com/translate/latest/dg/API_TranslationSettings.html) setting. It would be nice to be able to configure that value in Tolgee.

**Comment by JanCizmar** [comment]
Feel free to submit PR 😎

**Comment by Abhinav09-bits** [comment]
I would like to contribute in this as a my first contibution in open source  @JanCizmar can you assign this to me

**Comment by JanCizmar** [comment]
I believe, this is already fixed.
