### ISSUE TITLE
Allow use of IAM authentication for AWS translate/S3

### ISSUE THREAD

**Issue by kenske** [tolgee/tolgee-platform#1271]
Currently, the setup for AWS S3 and Translate requires you to add an access key and id for authentication. For self-hosted Tolgee instances running in AWS, authentication can be done through IAM roles/service accounts/instance profiles, so no access key would be needed.

**Comment by JanCizmar** [comment]
Feel free to submit PR. 🤓

**Comment by jdimeo** [comment]
I've begun working on upgrading to AWS SDK v2 so we get the better default credentials chain (just FYI). We need this if we're going to self-host as well.

**Comment by jdimeo** [comment]
PR is under review, still relevant

**Comment by kenske** [comment]
Not stale
