### ISSUE TITLE
Bug InvalidRequestException stripe exception

### ISSUE THREAD

**Issue by waigel** [tolgee/tolgee-platform#1310]
Unfortunately, the cloud version of tolgee has a bug in the connection to stripe. Neither the customer center nor any of the subscription routes are available.
```curl
GET /v2/organizations/{nr}/billing/customer-portal 
POST /v2/organizations/{nr}/billing/buy-more-credits
POST /v2/organizations/{nr}/billing/subscribe
```
All failed with status code 500 
```json
{"code":"unexpected_error_occurred","params":["com.stripe.exception.InvalidRequestException"]}
```

**Comment by JanCizmar** [comment]
Haha. 😸 I've tested it like 50 times, but then I forgot to updated the keys to production. Not it's fixed.
