### ISSUE TITLE
Front-end breaks with unrecognized flag emoji

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1316]
I *thought* I created the language with a correct country flag, but I guess I didn't :-)  Can this `t.getSvgNameByEmoji` fail more gracefully so it doesn't break the entire front end?
![image](https://user-images.githubusercontent.com/1071438/184718028-ec769cd9-971e-4745-8e85-1740fd51aa0d.png)
This is project 836

This happens now on most pages in the app:
![image](https://user-images.githubusercontent.com/1071438/184718159-8e5de129-5c06-475f-a458-e53bbf781582.png)
(but that is a fantastic error screen image :-))

**Comment by jdimeo** [comment]
Looks like the problematic flag emoji I'm trying to use for Indonesia is:
```
🆔
```
Ahh, I need to use alias `id_flag` to properly use emoji `🇮🇩` in the library I'm using...

![image](https://user-images.githubusercontent.com/1071438/184723620-71824e5a-e7c5-4db2-9fe3-5eefc58fc724.png)

**Comment by jdimeo** [comment]
I propose that if the emoji doesn't have an SVG, it's just rendered as-is

**Comment by JanCizmar** [comment]
haha, We didn't expect users creating languages manually with custom emojis. :)

**Comment by stepan662** [comment]
Problem with emojis is that they look different on each OS, it's hard to make them look nice everywhere. Since it should be an edge case, I'd just make it display blank flag.

**Comment by jdimeo** [comment]
Well yes, but if I'm intentionally setting a flag to a non-flag emoji, I would be willing to live with the different rendering on each OS. I also can't provide my own SVG the way you have it right now. So I have no way of providing a custom flag image- only a stock one or the blank flag.  In our use case, we are "back translating" from a language back to English and so I'm creating a language like `en-from-es-SV` (English from El Salvador Spanish). I would like to, in the future, have  a way to provide a custom flag image to differentiate from _real_ El Salvador Spanish.

**Comment by jdimeo** [comment]
but thank you for the fast fix!
