### ISSUE TITLE
Permission for translation import/export

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1323]
Is it possible to have the import and export of JSON/XLIFF files to either follow the existing permission structure or have a separate option to enable/disable? We don't want our translators to be able to download our entire data set if they just have Translate permissions on a specific language or two.

**Comment by jdimeo** [comment]
Right - the scenario here is that we've contracted with some company to translate a specific language or 2. We need them to have Translate permissions but don't want them "clicking around" the system and exporting our whole data set, especially with other languages. This one is a "nice to have" feature though and much lower priority than #1324

**Comment by JanCizmar** [comment]
Will be fixe - #1336
