### ISSUE TITLE
Permissions for viewing languages

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1324]
Thank you so much for the recent ability to limit a user to translating only specified languages. We would also like to similarly control the viewing/display of languages.

The reason that this is important to us is that we want a back translator to go from the target language back to English, and we don't want them to see the original English because then it's no longer an independent translation back to English. However, I think this is generally useful from a usability/UX standpoint- once you have more than a couple languages, it's confusing to have to select the particular language you're working with throughout the system and it would be great if all language menus were already limited to the languages you had permissions to. 

I could envision this as a checkbox that says "Also limit the display of languages to those the user is able to translate" or a separate picklist that says "Viewable languages:" that's similar to the current one where you can pick editable languages.

**Comment by jdimeo** [comment]
Thank you. I know that in the UI it won't seem like a big deal- one more combo box or check box- but I know it takes significant background work so I know this might be a "roadmap" item.

**Comment by JanCizmar** [comment]
Will be fixed - #1336
