### ISSUE TITLE
Provide ability to disable or skip a key/language pair for translation.

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1334]
In our situation, we have some keys that will never be translated for a given language. Say you are building financial software and one section only is relevant to a country/region and the languages spoken there - you don't need your translators to translate those keys in all languages. In our situation, we have survey questions that we don't ask in every country because they may be sensitive (like "do you have youth who use drugs?") so we are marking those as "🚫 Do not translate", however:
- This still counts as using translation quota
- These are visible to translators and are confusing
- Once the translator hides 🟢 reviewed translations to hide these "pre reviewed" no not translate strings, they can no longer distinguish between the work they actually did and reviewed vs. the system "reviewed" disabled translations

Can we add a status for **Disabled** or **Unused** or **Not translated** as one of the statues (in addition to Untranslated, Translated, and Reviewed)

This could dovetail nicely with adding a status for **Outdated** in #1147 

More generally, could you just add custom status options in the project settings and there would be no special behavior, but then we could leverage them with APIs and our own processes.

**Comment by JanCizmar** [comment]
Yes. We can add such status.

**Comment by jdimeo** [comment]
This is related to key based improvements in #1359

**Comment by cyyynthia** [comment]
This was introduced in #1972
