### ISSUE TITLE
Key namespaces, screenshots, edition dialog improvements

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1359]
## General tasks
- [x] Add namespaces field as it's going to be supported in new core & JS integrations
- [ ] Move key name and tags edition to separate dialog
- [ ] Show screenshot miniature right in the translation view and remove the camera
- [ ] Add key description field 

There were several feature requests related to keys. Some folks would like to add some custom JSON metadata, some would like to disable translation to some languages for specific keys. We can add this features later. But with the dialog in the UI it can be simple by adding multiple tabs. 

## Backend tasks
- [x] Add `Namespace` entity and add it's reference to `Key`
- [x] Update all the endpoints to work and return with namespaces
- [x] Add namespace to import

## Backend test cases
 - [x] Keys can be created in namespaces without constraint/index violations
 - [x] All key creating endpoints work with the namespaces
 - [x] User can add import for same existing language with different namespaces
 - [x] Conflicts are refreshed when changing namespace
 - [x] Namespaces are pre-selected correctly when uploading exported zip file
 - [x] Languages are pre-selected correctly when using namespaces
 - [x] Languages are reset when selecting namespace and has collision
 - [x] all namespace suggestions can be returned by the import controller
 - [x] all existing namespaces can be returned by the namespace controller

## Frontend tasks
- [ ] Create nice component for namespace selection and use it also in import view
- [ ] Show namespace in all view where key name is displayed
- [ ] Enable namespace name edition
- [ ] Export with namespaces

## E2E
- [x] Test whether file exported with namespaces can be imported without any configuration
- [x] Test selecting namespace in import

**Comment by JanCizmar** [comment]
@ZuzanaOdstrcilova UI proposal please.

**Comment by jdimeo** [comment]
I'm very eager for work in this space, especially the last one of adding a key description and making it a lot harder to accidentally edit a key
