### ISSUE TITLE
LDAP account support enhancements

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-platform#1379]
- [ ] Have a separate `ldap_username` field, and feed `username` with an email like Tolgee expects
   - The email could be looked up from the LDAP server. There should be a fallback to asking the user (configured by server admin). In the fallback scenario, the email field on the user profile is no longer a managed field.
 - [ ] Hybrid auth: have both LDAP accounts and Local accounts work at the same time (e.g. for external collaborators)
 - [ ] Prepare a test LDAP server for testing the whole LDAP authentication process
   - Both managed email and unmanaged emails should be tested

**Comment by poVoq** [comment]
Sounds like good improvements. I recommend using this as a test LDAP server: https://github.com/nitnelave/lldap/

**Comment by JanCizmar** [comment]
It doesn't look LDAP is required by many, oAuth is the state of the art, so I am closing this.
