### ISSUE TITLE
Add tags to all selected items in Translations vierw

### ISSUE THREAD

**Issue by elmaxe** [tolgee/tolgee-platform#1380]
Currently you can add a tag to each individual item in the Translations view:
[Screencast from 2022-09-23 13:36:29.webm](https://user-images.githubusercontent.com/33149910/191952106-0444ae61-bb64-426e-9be7-26c921e4ee78.webm)

However, there seems to be no way to add tags to all currently selected items.

**Comment by JanCizmar** [comment]
Noted! This is will be a part of batch operations. https://github.com/tolgee/tolgee-platform/issues/911
