### ISSUE TITLE
Minor: user email is case sensitive

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1382]
I've locked my account a couple times because I was trying to use `jdimeo@email.org` instead of `JDimeo@email.org`, which apparently was the exact casing I used during registration. Maybe this is a feature rather than a bug for security reasons?

**Comment by JanCizmar** [comment]
It's a bug.

**Comment by jdimeo** [comment]
Still a usability problem

**Comment by krisgerhard** [comment]
Would love to see it fixed :)

**Comment by ammassey** [comment]
Looks like this issue is still open, if so I would like to start contributing if possible. I am relatively new to the space so any additional information would be greatly appreciated! Thanks!

**Comment by JanCizmar** [comment]
Hi there! Thanks for the interest. However, we will fix this internally. The are users on Tolgee cloud who has colliding addresses, so we need to handle this somehow.

**Comment by esnoche** [comment]
Looks like this issue is still open, if so I would like to start contributing.

**Comment by Rkarama26** [comment]
Hi @JanCizmar! 👋

I noticed this issue has been open since 2022. Are you still planning to work on this, 
or would it be okay if I took it over?

I'd be happy to contribute a fix for this if it's available!
