### ISSUE TITLE
Slack expired invitation link

### ISSUE THREAD

**Issue by ludovicobesana** [tolgee/tolgee-platform#1393]
The link in the readme to join the slack community has expired.

![Schermata 2022-10-08 alle 18 28 51](https://user-images.githubusercontent.com/35035423/194717704-ab685420-24b5-49d6-936f-50c43779de6c.png)

**Comment by JanCizmar** [comment]
Hi there! Thanks for reporting. Use this one as a workaroun: https://join.slack.com/t/tolgeecommunity/shared_invite/zt-195isb5u8-_RcSRgVJfvgsPpOBIok~IQ

(Slack disables the previous link if I generate new one, which is the reason why we've published some expired ones)

**Comment by JanCizmar** [comment]
It's fixed now in the README.
