### ISSUE TITLE
[MINOR BUG]: Invitations sent show duplicate

### ISSUE THREAD

**Issue by martinet101** [tolgee/tolgee-platform#1396]
When email-inviting someone, the header shows always duplicated.

When more than one person is invited, all of them show two times.

Example: (censored for privacy)
![image](https://user-images.githubusercontent.com/53119851/195666649-f24c7701-1c1e-40cc-bb13-3968aff20ed4.png)

**Comment by JanCizmar** [comment]
Wow! What a fail.
