### ISSUE TITLE
Disable/hide login form when only using external providers

### ISSUE THREAD

**Issue by jaspervriends** [tolgee/tolgee-platform#1400]
It would be useful to be able to hide the login form when you're only using/allowing external providers to login. When the login form is disabled, only the other authentication options should be visible for the users to login/sign up.

When the login form is disabled, the user should also not be able to set a password in the 'Account security' settings.

**Comment by JanCizmar** [comment]
Hey! I have created an issue for the SSO here: https://github.com/tolgee/tolgee-platform/issues/2273

So I am closing this in favor of the master issue.
