### ISSUE TITLE
Support CockroachDB

### ISSUE THREAD

**Issue by wodka** [tolgee/tolgee-platform#1404]
Hi :)

I've just setup Tolgee with CockroachDB (it's made to run without masters on kuberenets). With the initial Setup there were only 3 minor errors with the following migrations:

* 1626957302295-1 (using syntax is not yet supported in CRDB - but I think will work out of the box in 23.1)
* 1637177424380-0 (changing the length of the key - I think will also work out of the box in 23.1)
* 1661361670848-3 the only real problem - as it will not support triggers

is there perhaps a way to generate the api keys without the triggers?

**Comment by JanCizmar** [comment]
Hi there!

You don’t need the triggers. It was there just to cover the time, when there were running instances with multiple different versions. Feel free to submit PR disabling this migration for CockroachDB.

**Comment by wodka** [comment]
Neat :D I was assuming it is still needed because of the query that is being executed: https://github.com/tolgee/tolgee-platform/blob/main/backend/data/src/main/resources/db/changelog/hideApiKeyMigration.sql

can you point me in some direction to disable certain migrations?

**Comment by wodka** [comment]
:/ ok found another error: `org.postgresql.util.PSQLException: ERROR: unknown signature: to_char(timestamp, string)`

Hopefully would be added with https://github.com/cockroachdb/cockroach/issues/3781 (but no clue when)


https://github.com/tolgee/tolgee-platform/blob/main/backend/data/src/main/kotlin/io/tolgee/repository/activity/ActivityRevisionRepository.kt#L64 here is the query with the function. 

Would it be possible to change it to (not sure how to add the typecast in that query)
```sql
select 
  count(ar.id) as count,
  ar.timestamp::date as date
from 
  activity_revision ar
where 
  ar.project_id = 1
group by date
order by date

# Now:
# select count(ar.id) as count, function('to_char', ar.timestamp, 'yyyy-MM-dd') as date

# New?
# select count(ar.id) as count, ar.timestamp::date as date
```

**Comment by JanCizmar** [comment]
> can you point me in some direction to disable certain migrations?

You can specify dbms in the `schema.xml` file by setting `dbms` attribute for sql statement. See db/changelog/schema.xml:1482. But I don't think this will be sufficient for you. However, there is other way. It seems like you can send some parameters to the liquibase chengelog and use them.

You can provide these params when the liquibase bean is created:
```
io.tolgee.configuration.LiquibaseConfiguration#liquibase
```

To actually disable the statements, you can use precondidions:
https://docs.liquibase.com/concepts/changelogs/preconditions.html

**Comment by JanCizmar** [comment]
> Would it be possible to change it to (not sure how to add the typecast in that query)

I don't really remember why it's there. Let me check... 😆

**Comment by JanCizmar** [comment]
> # New? (::date would also format it in iso so the output would be identical if this works)
> # select count(ar.id) as count, ar.timestamp::date as date

I've tested this and it doesn't work, But this works:

```
select count(ar.id) as count, cast(cast(ar.timestamp as date) as text) as date
```

**Comment by wodka** [comment]
with `select count(ar.id) as count, cast(cast(ar.timestamp as date) as text) as date` it would work for CRDB as well! :D if that is a possible change for you it would be great

**Comment by JanCizmar** [comment]
I've created a PR. Let's se what the test result shows, but it looks like we will have to wait for CRDB 22.2.

**Comment by wodka** [comment]
@JanCizmar is there a way for me to get a dockerimage with the modifications? Then I could also run this and see if something else pops up

**Comment by wodka** [comment]
:/ was a bit tricky to get the correct image but I managed it.

Sadly there is an error popping up:

```
ERROR: unimplemented: the configuration setting "join_collapse_limit" is not supported
```

coming from: https://github.com/tolgee/tolgee-platform/blob/afd2a1db034e1cae2bbaa4322691d5297e5747fc/backend/data/src/main/kotlin/io/tolgee/service/query_builders/TranslationsViewBuilder.kt#L343

The simple way of commenting the line seems to work - but the comment indicates to me that it is important for postgres....

**Comment by JanCizmar** [comment]
> Update: using the correct branch should help - rebuilding right now

Yeah, it's fixed here https://github.com/tolgee/documentation/pull/306
