### ISSUE TITLE
Export translations as ARB file

### ISSUE THREAD

**Issue by Purus** [tolgee/tolgee-platform#1407]
Please provide an option to export the files as ARB (Application Resource Bundle) file. Although it's just another version of JSON format, when keys/plurals features are used, it could make more sense to export in ARB format.

**Comment by JanCizmar** [comment]
Since ARB uses ICU message format, this shouldn't be complicated. I don't know when we will be to implement this, but as a workaround you can convert the exported `.json` via simple script.

**Comment by JanCizmar** [comment]
This is already released!
