### ISSUE TITLE
[BUG] When exporting as JSON, keys containing a dot (.) are converted it into nested objects.

### ISSUE THREAD

**Issue by LocalMonero** [tolgee/tolgee-platform#1410]
According to the [IETF JSON RFC](https://datatracker.ietf.org/doc/html/rfc8259), essentially any string of Unicode characters may be a key in a JSON. There are no rules as to the special interpretation of a key that contains a dot (.) character as a shorthand to a nested object or any other such thing.

One of the most popular web frameworks, Laravel, [allows and suggests the use of translation strings as keys](https://laravel.com/docs/9.x/localization#using-translation-strings-as-keys):

> For applications with a large number of translatable strings, defining every string with a "short key" can become confusing when referencing the keys in your views and it is cumbersome to continually invent keys for every translation string supported by your application.

This results in code that's much easier to read and maintain:

```html
    <p>
      {{__("I love programming.")}}
    </p>
```

Instead of:

```html
    <p>
      {{__("programming_string")}}
    </p>
```

When importing a JSON file with such key:value entries into Tolgee it works fine. Take, for instance, this Spanish .json:
```json
﻿{
    "I love programming.": "Me encanta programar."
}
```

Imports correctly:

![1](https://user-images.githubusercontent.com/31570671/198566120-2e875981-66b2-42f4-923b-a9ec01214662.png)

Now, if we export the Spanish translation through the export tool as .json, we get the following output:

```json
{
  "I love programming" : {
    "" : "Me encanta programar."
  }
}
```

Why? Because Tolgee interprets the `.` at the end of `I love programming.` as a reference to a nested object.

Please either bring the JSON export functionality in line with the IETF RFC or give us the option as to how to interpret the dots in the JSON keys for those who rely on such exports.

**Comment by JanCizmar** [comment]
Hello,

Thanks for letting us know!

First of all, the approach Laravel people suggest we consider the bad practice. This naming can lead to reusing the same keys in different contexts, which can lead to wrong translations. For example key "Close" can be translated as "Dismiss" in one context and "Near" in another. 

Perfect localization is crucial for Tolgee, and similar practices can cause a lot of trouble in the future. If you don't want to invent the keys, you can generate a random UUID as a key name.

You can modify the current exporting behavior if you use the export endpoint. https://tolgee.io/api#tag/Export/operation/export_1 

Using GET `https://app.tolgee.io/v2/projects/export`, you can provide empty `splitByScopeDelimiter`.

`https://app.tolgee.io/v2/projects/export?splitByScopeDelimiter=`

This makes it return the files you desire.

Notice that this parameter will be renamed `structureDelimiter` in the next major release since Tolgee will introduce namespaces. 

Anyway, it's not a bug, and the JSON we return is perfectly valid. It's just how Tolgee works and what's how Tolgee expects the files to look in its native integrations.

**Comment by LocalMonero** [comment]
Please add the relevant information into the docs.

**Comment by JanCizmar** [comment]
Feel free to submit PR to [docs repository](https://github.com/tolgee/documentation) . Otherwise, we will provide better docs for other than JS technologies with  All format support, which is on our [roadmap](https://tolgee.io/roadmap)

**Comment by adanielyan** [comment]
This query param doesn't seem to work with this API:
https://app.tolgee.io/v2/projects/translations/es-ES

**Comment by JanCizmar** [comment]
> This query param doesn't seem to work with this API:
https://app.tolgee.io/v2/projects/translations/es-ES

Yeah, you should use `https://app.tolgee.io/v2/projects/export`.

**Comment by adanielyan** [comment]
The problem is that this endpoint returns a zip file. I cannot use it in my app where I need a JSON response from API.

**Comment by panther7** [comment]
still issue,

old api is ok:
```
/export?format=JSON&splitByScope=false&splitByScopeDelimiter=~&splitByScopeDepth=0&filterState=UNTRANSLATED&filterState=TRANSLATED&filterState=REVIEWED&zip=true
```

new api is "broken"
```
/export?format=JSON&structureDelimiter=&filterState=UNTRANSLATED&filterState=TRANSLATED&filterState=REVIEWED&zip=true
```

**Comment by JanCizmar** [comment]
Are you using v3.alpha version?

**Comment by JanCizmar** [comment]
V3 is isn't released yet. Will be released on 11th January.

**Comment by panther7** [comment]
And some endpoit for test? For my issue

**Comment by JanCizmar** [comment]
There is currently no test endpoint.

**Comment by JanCizmar** [comment]
We should have to deprecate the old endpoint at first and remove it later. So there wasn't the need to switch immediately. Next time we will do a better job. ⛳

**Comment by cyyynthia** [comment]
You can easily spin up a test instance on your local machine via Docker as well. v3.0.0-alpha5 images are available for use (and do have the `structureDelimiter` paramerers).

https://tolgee.io/platform/self_hosting/running_with_docker

**Comment by paperrin** [comment]
We also had difficulties with a similar situation, our use-case is quite more specific tho...
We have to share keys between different environments, one being react, where deep nesting in the json translations isn't an issue, and another (C# Unity), where we have to convert the data to a CSV that the translation system takes in, this CSV looking like this:
```csv
Key;Type;Desc;English;French
PROFILE/GREETING;Text;Hello user !;Bonjour utilisateur !
PROFILE/LOGOUT;Text;Logout;Se déconnecter
```

We found this workaround, using current api (v2), that requires 1 fetch per language, and returns a flattened JSON object:

JS Code snippet
```js
const jsonData = fetch(`${BASE_URL}/v2/projects/export?ak=${token}`, {
  method: "POST",
  headers: {
    "content-type": "application/json",
  },
  body: JSON.stringify({
    format: "JSON",
    languages: [
      LANGUAGE_TAG,
    ]
    splitByScopeDelimiter: "",
    zip: false,
  }),
})
  .then(r => r.json())
```

Imported JSON / Default export as JSON:
```json
{
  "key1": {
    "key2": "value"
  }
}
```

Output for this same imported JSON:
```json
{
  "key1.key2": "value"
}
```
Suits our needs, if that might help anyone else...
Seems like `splitByScopeDelimiter` option isn't documented, which "kind of solves" this issue, even though you're still not able to do both deep nesting and dots in keys together.
