### ISSUE TITLE
Install without docker

### ISSUE THREAD

**Issue by mustafaulukaya** [tolgee/tolgee-platform#1411]
Hi,

I wanna ask, is there any chance to install tolgee without docker? I want to use it on my server but hyper-v is causing problems.

**Comment by mustafaulukaya** [comment]
Okay, I will try that but I can't find how can I pass my .env file to tolgee. I can't see any example for that. I tried:

java -jar tolgee-2.45.8.jar --env="./.env"

but it's not working I guess, tolgee still try to run docker

**Comment by cyyynthia** [comment]
Tolgee doesn't load environment from the `.env` file, but will read from the `application.properties` files.

The format should be similar if not identical to what you have in your `.env` file:
```
tolgee.postgres-autostart.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/tolgee
```

**Comment by mustafaulukaya** [comment]
Okay I can run it now, thanks a lot.
