### ISSUE TITLE
Cleanup flaky time-sensitive tests

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-platform#1415]
Timing sensitive tests (mostly MFA-related) are flaky because of a dependency on the system time, rather than a fixed, controlled time. `CurrentDateProvider` needs to be mocked in these tests.

MFA service might need slight changes to respond to the mock. Flaky tests also applies to some Cypress tests.

**Comment by JanCizmar** [comment]
When merged #1442 , there is an endpoint allowing you to set server time in test environment. That might help.
