### ISSUE TITLE
Link out to key location on page in screenshot

### ISSUE THREAD

**Issue by paradoxministry** [tolgee/tolgee-platform#1419]
Hello.

This is a feature request around providing some sort of hotspot or link out functionality on top of screenshots that would allow a translator to follow the key ID to its location on the page where the string would be displayed.

This would help with figuring out in broader context, where a string exists in the UI, even if a screenshot exists. A screenshot may not be encompassing all the context required for a translator to be able to correctly translate a string.

For example, if I had a navbar string called `Images` with the key `navbar-images`, I should be able to provide a hotspot on the screenshot or through another mechanism to be linked out to https://www.mysite.com/ where the navbar with the string `Images` would be displayed.

**Comment by JanCizmar** [comment]
Would be having a field for key description sufficient for this? I am not sure if it really makes such a benefit for us to add the specific field for the link...

**Comment by paradoxministry** [comment]
I think that would be beneficial as well. If the field can link out to the page where the string is located in the UI, a translator would be able to get more context. The screenshot would also be tied to the key so perhaps augmenting the image to identify the position of the string in the UI would be a lot more work but I think long-term it would help differentiate Tolgee from other translation platforms.

**Comment by JanCizmar** [comment]
Hmm... I don't think this would be very reliable. In single page apps the url doesn't always open the same content. There can be dialogs, error messages or other dynamic UI components. So such feature can lead to a lot of confusion/complains IMHO. 

For me it makes sense to add key description field. Which we already plan for some time and leave it to user to use it however they want.

What do you think? @stepan662 @cyyynthia

**Comment by stepan662** [comment]
I was thinking about automatically saving a relative path from in-context. But it's quite problematic as @JanCizmar said. In many apps, there are private urls, which are not accessible to all users, so that wouldn't work very well.

However, I see how it could make sense for some kind of apps, so we might consider it as a feature, that you can turn on if it makes sense for your app.

**Comment by cyyynthia** [comment]
Linking to app segments is very difficult if not impossible without some form of instrumentation, allowing to inject states within the app and components. There is also the problem of private endpoints, which could also be solved via instrumentation and test credentials, on a staging environment.

I don't see many cases where this would be necessary, and this would be a complex feature. I think for most of the cases where all the context is lacking on a single screenshot, allowing to attach videos showcasing the path to the string would allow to encompass much more context surrounding a string, without requiring to link to the live application.

I think for complex cases a video and a good key description would suffice. There is no harm to also adding a link to the app where the string is, but I think this info can just be noted in the key description, if we're not building any complex state injection or whatever.

**Comment by JanCizmar** [comment]
This might be interesting now, since we added a location prop to the screenshot entity, right? @stepan662

**Comment by stepan662** [comment]
We can display the location, but I'm not sure that it would necesarilly useful to the user, since it serves a bit different purpose.
