### ISSUE TITLE
auto-translate new language when added

### ISSUE THREAD

**Issue by eweren** [tolgee/tolgee-platform#1423]
Don't know if you need more info.
My usecase: We already translated 4 languages and have a keyset of like 500 keys. When adding a new language that should initially be autotranslated, we have to click through each key and manually click on the translation. It would be nice to tell tolgee to translate all missing translations automatically

**Comment by cyyynthia** [comment]
The Batch actions issue (#911) includes batch automated translation, which should be able to do cover this
