### ISSUE TITLE
Supabase storage middleware

### ISSUE THREAD

**Issue by danielduckworth** [tolgee/tolgee-platform#1426]
Hi, I would like to suggest a feature.

Supabase has S3 compatible storage buckets. It would be great if Tolgee could be configured to enable S3 but use a different provider like Supabase.

There is some information about it here: https://supabase.com/blog/supabase-storage

👍

**Comment by JanCizmar** [comment]
Hi. If it's S3 compatible, then you're able to configure it. Can you share your configuration?

**Comment by danielduckworth** [comment]
The [docs for configuring the .env for S3 storage](https://tolgee.io/docs/platform/self_hosting/configuration#s3enabled) refer to the following keys:

- s3.access-key
- s3.secret-key
- s3.endpoint (has to be set to a service endpoint: https://docs.aws.amazon.com/general/latest/gr/s3.html)
- s3.signing-region
- s3.bucket-name

The supabase docs cover [examples for libraries like Javascript](https://supabase.com/docs/reference/javascript/supabase-auth-admin-api) and Python but I can't find anything that refers to the keys stated above or something similar.

**Comment by danielduckworth** [comment]
OK, that makes sense. Thanks @cyyynthia. Nice to have to have, but not essential.
