### ISSUE TITLE
Sample .env for docker throws errors for unexpected "-" character

### ISSUE THREAD

**Issue by danielduckworth** [tolgee/tolgee-platform#1428]
The docs refer to the following [example .env for docker compose](https://tolgee.io/docs/platform/self_hosting/running_with_docker#running-with-compose):

```Docker
spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
tolgee.postgres-autostart.enabled=false
```
However this throws an error: "unexpected character "-" in variable name".

I had to change `tolgee.postgres-autostart.enabled` to `tolgee.postgres_autostart.enabled`.

There is a note in the docs that states:

> "Some versions of docker-compose doesn't accept dots (".") in .env file key names. Then you can replace . characters with </ underscores _."

I guess "-" are also a problem for recent versions of docker.

**Comment by adanielyan** [comment]
I was experiencing same errors. Replaced all dots and dashes with underscores and everything worked fine.

**Comment by JanCizmar** [comment]
It's fixed in docs, right?
