### ISSUE TITLE
Implementation details organization

### ISSUE THREAD

**Issue by Webrow** [tolgee/tolgee-platform#1431]
Dear all, 

Again thanks for this great piece of software. Currently we are tying to setup (not related to tolgee) the structure you use for organisations (one user with 1 login can be invited into multiple organisations, and select one of those accounts and continue as that account) in our own software. Is there a special term for this, or are you using any third party apps for this ? (we looked into Auth0 but pricey, keycloak (not 1 user owns multiple accounts). Ive tried skimming through the source but seems difficult for me to pinpoint where all this happens. I understand since it is not related to tolgee as an issue of you can't help me but would appriciate it if you coul dpoint me in the right direction, or paper, or whatsoever. 

Kind regards,

**Comment by JanCizmar** [comment]
We have our custom implementation for this. I actually don't know if there's a special term for this. So I don't really know where to point you. This happens in lot of places in the code. Starting with `io.tolgee.model.Oganization` class would be maybe good start for you. 😄

**Comment by Webrow** [comment]
Awesome, thanks @JanCizmar
