### ISSUE TITLE
Missing "splitByScope" for export translation via UI

### ISSUE THREAD

**Issue by panther7** [tolgee/tolgee-platform#1455]
If I need export JSON as `key: value` only

![2022-12-15 17 02 33](https://user-images.githubusercontent.com/3808250/207908849-74433eb3-37e8-4639-8ed2-8ab720c02d2c.png)

**Comment by JanCizmar** [comment]
The `splitByScope` option is removed in v3 (being released soon) and replaced with `structureDelimiter`. So @stepan662, please fix it in v3.
