### ISSUE TITLE
Statistics not showing correct progress

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#1456]
<img width="685" alt="Snímek obrazovky 2022-12-16 v 9 38 52" src="https://user-images.githubusercontent.com/8831144/208058107-293b57ca-85c2-4458-ab01-3280e56199ca.png">

**Comment by stepan662** [comment]
While all the translations are translated for french and english

**Comment by JanCizmar** [comment]
The stats were not refreshed after translation modification. Not sure why. Modification of the translation value should lead to stats refresh.
