### ISSUE TITLE
Screenshot is broken in docker environment

### ISSUE THREAD

**Issue by lordrive** [tolgee/tolgee-platform#1460]
If we're using tolgee in a docker environment even if we set the `tolgee.front-end-url` property in the .env file the screenshot uploaded won't use the provided url to display the image thumbnails and keeps using the ip:port used by docker instead. While clicking on the empty rectagle it will show the original image properly.

See provided screenshot: https://i.imgur.com/yXnuvxR.png

**Comment by JanCizmar** [comment]
Works on my computer.

Can you please share the docker configuration you're using?

**Comment by JanCizmar** [comment]
Anyway, the url can me configured via `tolgee.file-storage-url`. The `tolgee.front-end-url` has different purpose.

**Comment by lordrive** [comment]
Steps to reproduce properly:
- Create an env file and set up `tolgee.front-end-url` to https://whatever.com
- Create an apache virtualhost and set up a proxy to docker's ip and port
- Open tolgee in the browser on https://whatever.com
- Upload an image for a translation
- Only the thumbnail url will be wrong while the image url itself is not.

If only there was any kind of documentation then what is that "different" purpose `tolgee.front-end-url` has.
Also the documentation says file-storage-url is a `Public base path where files are accessible` which clearly states that it's a path not a doman or url. 

Also not entirely sure what you mean by front-end-url has a different purpose if not to prefix every url with this inside tolgee.

**Comment by lordrive** [comment]
By the way, it did indeed fix the url issue when i added `tolgee.file-storage-url` and set up the same doman as in the frontend url in the .env file so it's only the documentation that is ambiguous and hard to understand.

Feel free to close this issue after correcting the documentation about what is the actual purpose of those properties.

**Comment by JanCizmar** [comment]
Hey! Front-end url defines, where the front-end can be found. For example when sending email with a link to password reset page, the backend needs to know the URL when sending the e-mail.
The images are retrieved from backend's file storage endpoint. Thats why it's called `tolgee.file-storage-url`. 

> Also the documentation says file-storage-url is a Public base path where files are accessible which clearly states that it's a path not a doman or url.

Yeah. That's maybe not well documented, but the param name is ...-url. So it's enough to think, it might be a url.

**Comment by lordrive** [comment]
> Hey! Front-end url defines, where the front-end can be found.
Thats why i didn't understand why everything else works properly except for the thumbnail image urls. Generating urls in emails is not that different to generating urls for files used by tolgee. (For me at least it sounds a bit redundant since i can't exactly know the use and differences of those variables)

> Yeah. That's maybe not well documented, but the param name is ...-url. So it's enough to think, it might be a url.
Thats exactly why i said it's ambiguous. I shouldn't need experimenting with variables to figure out how to configure it properly. Especially since the documentation continues with configuration for s3 and such.
