### ISSUE TITLE
Integration of vue-i18n for vue3

### ISSUE THREAD

**Issue by Avey777** [tolgee/tolgee-platform#1472]
![image](https://user-images.githubusercontent.com/35259040/209521704-4156c494-306a-4fae-ba2a-f01d4f4dedf7.png)

Our project uses vue3, how to quickly integrate tolgee

**Comment by JanCizmar** [comment]
Hey, for Vue 3 you can use Tolgee native integration. 

https://tolgee.io/js-sdk/5.0.0-alpha.1/integrations/vue/installation

But if you prefer i18next, the integration should work also for Vue 3.
