### ISSUE TITLE
Ability to disable a language

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-platform#1489]
Feature Request: To have the abilito to temporary disabled (not delete) a language

**Comment by JanCizmar** [comment]
Hi there! What's the use case?

**Comment by paulwer** [comment]
within our development cycle, we want to prevent languages showing up to our marketing team, which is resposible for the languages.

-> It will be just nice to have.

an othe aproach could be, giving users scoped access

**Comment by JanCizmar** [comment]
Scoped access is part of the granular permissions: #1442
