### ISSUE TITLE
Invite Links do not show Sign-Up button if new registrations are not allowed

### ISSUE THREAD

**Issue by cdemi** [tolgee/tolgee-platform#1495]
I have Tolgee 3.0.0 with `tolgee.authentication.registrations-allowed` set to `false`. If I try to invite someone new when they click the link, they get redirected to the login page without any way to register. In v2.49.0 below the login form a sign up link used to show when you get an invite link.

I have these configurations set:

```
- name: tolgee.authentication.enabled
  value: "true"
- name: tolgee.authentication.user-can-create-organizations
  value: "false"
- name: tolgee.authentication.registrations-allowed
  value: "false"
- name: tolgee.authentication.needs-email-verification
  value: "true"
```

**Comment by JanCizmar** [comment]
Thanks for reporting. Let me check!

**Comment by JanCizmar** [comment]
It's a frontend issue. So @stepan662 will fix it soon.
