### ISSUE TITLE
Entering a translation with German special characters (Umlaut, ä, ö, ü, ß) cuts off before save

### ISSUE THREAD

**Issue by hofrob** [tolgee/tolgee-platform#1499]
Reproduce:

* create project
* base language EN
* translated language DE and/or TR
* go to the translations overview page: https://tolgee.example.com/projects/3/translations
* add a key
* click on the language you want to translate the key to
* enter "abcüabcäabc" (the bug only occurred when typing it, not while pasting)
* press "save"

In the browser network tab you'll only see "abc".

There's something wrong with the UI here. It does weird things. It seems like that it has troubles when using the compose key on Ubuntu. Using a german layout works as expected.

Whenever I use the compose key to type a character, all the changes are ignored.

**Comment by stepan662** [comment]
Wow, that's a weird bug. I was trying to replicate it but it works for me. I guess I will have to try it on ubuntu. Could you check if it throws any error to console?

**Comment by hofrob** [comment]
There's nothing in the console. No warnings or errors.

I tried using a different key for the compose key now. Same result.

Another thing: I just tried it on the same machine with Chromium and it worked correctly. So it seems like the combination Compose key + Firefox (stable and dev version) is the problem here.

**Comment by stepan662** [comment]
Not able to reproduce, seems like platform specific error.
