### ISSUE TITLE
Importing key with empty translation acts weird

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#1509]
When you try to import file
```
{
  "key_example": ""
}
```

It ignores file completely. I guess it's because it ignores empty strings and so it doesn't see any new translations.
But it is confusing for the user. It should probably throw some error like (nothing to add) or add at least new keys with empty translations.

**Comment by JanCizmar** [comment]
It's probably fixed here: https://github.com/tolgee/tolgee-platform/pull/1500 (v3.2.0), which is now released.
