### ISSUE TITLE
manual start of machine translation

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-platform#1521]
After adding a new language to an existing project, I would like to execute the machine language generation for all not translated phrases. Is there a givven workflow for that or can this be created as a new feature?

**Comment by JanCizmar** [comment]
Hey! This is a part of batch operations feature, we are working on. Hopefully it will be released before end of February.

**Comment by JanCizmar** [comment]
https://github.com/tolgee/tolgee-platform/issues/911
