### ISSUE TITLE
Some keys are missing when fetching translations in DevTools

### ISSUE THREAD

**Issue by vasyas** [tolgee/tolgee-platform#1522]
When DevTools fetches translations via API call `https://app.tolgee.io/v2/projects/XXXX/translations/en`, some keys are missing in the response. Missing keys are present when calling `export` endpoint. They also present in the Platform UI or when alt-clicking key.

Output of the `export` endpoint:
```
curl "https://app.tolgee.io/v2/projects/export?languages=en&filterKeyPrefix=chargePoint.status&zip=false" -H ...

{
  "chargePoint" : {
    "status" : "Status",
    "status.active" : "Active",
    "status.charging" : "Charging",
    "status.disconnected" : "Disconnected",
    "status.faulted" : "Faulted",
    "status.hidden" : "Hidden",
    "status.maintenance" : "Maintenance",
    "status.notConnected" : "Not Connected",
    "status.offline" : "Offline",
    "status.online" : "Online"
  }
}
```

Output of the DevTools endpoint (relevant part):
```
curl "https://app.tolgee.io/v2/projects/.../translations/en" -H ...

{
   "en" : {
   ...
    "chargePoint" : {
      "status" : "Status"
    },
    "chargePoint.status.active" : "Active",
    "chargePoint.status.faulted" : "Faulted",
    "chargePoint.status.maintenance" : "Maintenance",
    "chargePoint.status.notConnected" : "Not Connected",
    ...
  }
}    
```

**Comment by JanCizmar** [comment]
Hi there! which values are missing specifically?

**Comment by vasyas** [comment]
Hi!

All that are not in the output sample are missing:
- "status.charging" : "Charging",
- "status.disconnected" : "Disconnected",
- "status.hidden" : "Hidden",
- "status.offline" : "Offline",
- "status.online" : "Online"

I cannot imaging the reason why it could be like this. Maybe, some keys are created earlier, some keys are created later?

If it's needed, I can share the project ID for further investigation.

**Comment by JanCizmar** [comment]
Seems like a serious bug

**Comment by JanCizmar** [comment]
If you are not convenient with sharing the project ID here, you can join the Slack community and send a direct message to me. https://tolg.ee/slack
