### ISSUE TITLE
Create new users in Server Administration Panel

### ISSUE THREAD

**Issue by KxmischesDomi** [tolgee/tolgee-platform#1541]
It should be possible to create new users in the Server Administration Panel.
Having people always create their own account is a mess if you only want certain people having accounts.
You would have to enable registration and then disable it again.

**Comment by cyyynthia** [comment]
> Having people always create their own account is a mess if you only want certain people having accounts.
You would have to enable registration and then disable it again.

This isn't documented (and should); but invitation links to projects allow people to sign up when registrations are disabled. If you pass an invite link to a project to people who should have an account, they will be allowed to create an account without modifying the configuration of the server.

**Comment by KxmischesDomi** [comment]
Thank you very much for the answer! This will very much help with the problem.
Still there should be an option for administration to create accounts via their panel :)

**Comment by JanCizmar** [comment]
This should be added to organization/project members. Instead of inviting the user's it might create a user account, right away. Not sure about the use case anyway.
