### ISSUE TITLE
[@tolgee/format-icu]: tag attributes

### ISSUE THREAD

**Issue by Akronae** [tolgee/tolgee-platform#1551]
I'm looking to create a link using Icu with tags interpolation.

A key with any value like
```html
<a href="any"></a>
```
Will throw a `SyntaxError: INVALID_TAG` error.

[Bug that might be related](https://github.com/tolgee/tolgee-platform/discussions/1552)

**Comment by JanCizmar** [comment]
If you use React.js, then you should follow [this doc page](https://tolgee.io/js-sdk/integrations/react/tags-interpolation)

**Comment by Akronae** [comment]
@JanCizmar The doc explains how to use attribute with the actual JSX element that is being used for the interpolation.
However it does not explain anything how attributes in the tag **that has to be interpolated**

Whatever, there will still be a bug when a tag has an attribute in the translation value, `SyntaxError: INVALID_TAG` will be thrown when the tag is totally valid, it simply has some attributes :/

**Comment by stepan662** [comment]
Hey, tag attrubutes are not allowed in the ICU parser, that's why it doesn't work. We actually can't really influence this
https://formatjs.io/docs/intl-messageformat#intlmessageformat-constructor

**Comment by Akronae** [comment]
Oh. Okay. Too bad. Found a hack using nasty json inside of the tag and parsing it when interpolating 😄 
```html
<a>'{"_content": "Link", "href": "https://google.com"}'</a>
```
