### ISSUE TITLE
Support for .properties

### ISSUE THREAD

**Issue by tpgxyz** [tolgee/tolgee-platform#1556]
Hello team,
first i'd like to thank you for this great platform which tolgee is. I like it very much.
What i'd like to share with you that i'm missing import/export file feature that will handle the [.properties](https://en.wikipedia.org/wiki/.properties) file format extension.
Thanks for taking it into consideration.

**Comment by JanCizmar** [comment]
Hey, this is part of #1547. Thanks for sharing! :)
