### ISSUE TITLE
Control nested structure level

### ISSUE THREAD

**Issue by Ilkhom-S** [tolgee/tolgee-platform#1557]
Is there option to add nested structure level. So we can choose only 1 level when exporting to json.

For now: 
key: texts.Container.SomeValue
Get's transformed to 
```JSON
{
texts :{
},
Container: {
SomeValue: "Translation Text"
}
}
```

What needed is : 

Translation to : 

```JSON
{
texts : {
Container.SomeValue: "Translation Text"
}
}
```

If there could be set nested structure level to 1. So only first level get transformed

I hope I could explain.

**Comment by JanCizmar** [comment]
Tolgee now natively supports namespaces. Nesting is adding some error prone complexity to the system, so we consider wiser not to continue to add any features to that.
