### ISSUE TITLE
Import: User can't upload multiple files with the same language selected

### ISSUE THREAD

**Issue by Martin005** [tolgee/tolgee-platform#1571]
The import doesn’t allow user to upload multiple files with the same language selected.

I think that the user should have an option to upload multiple files with the source language.

![image](https://user-images.githubusercontent.com/10096404/219422504-c88fdc3a-07a7-4932-a7e6-cd31254113ae.png)

**Comment by JanCizmar** [comment]
This is fact of life. In that case languages would be possibly have conflict between each other, solving this would add a lot of complexity to the task.
