### ISSUE TITLE
Automatic Translation not working

### ISSUE THREAD

**Issue by DavithkbY** [tolgee/tolgee-platform#1577]
I added a project with base language English.
Then I added Dutch (nl-BE) to this project and enabled translation memory and translation with primary provider. After this the words in nl-BE became translated automatically. 

Now I have added spanish (es) as a language and this won't translate automatically. I tried removing nl-BE and tried to get the words automatically translated, this didn't work either anymore!

Any idea what I am doing wrong?

**Comment by JanCizmar** [comment]
I am not sure I got it. The automatic translation currently works only when you add new keys or initially set the source language value. If you add new language, the strings are not translated automatically (which is a part of #911). Are you referring to this or am I mistaken?

**Comment by DavithkbY** [comment]
> I am not sure I got it. The automatic translation currently works only when you add new keys or initially set the source language value. If you add new language, the strings are not translated automatically (which is a part of #911). Are you referring to this or am I mistaken?

Ah it only works when adding new keys. I was exactly asking for #911 indeed. 
It would also be usefull if when importing a json with keys and translations, these imported keys would be automatically translated as well.

**Comment by DavithkbY** [comment]
Is it possible to have it auto generate translations for all other languages when adding a translation key with english base translation through the rest POST api call?(<---Sets translations for existing or not existing key)

**Comment by JanCizmar** [comment]
There is also auto-translate [endpoint](https://app.tolgee.io/swagger-ui/index.html?configUrl=%2Fv3%2Fapi-docs%2Fswagger-config&urls.primaryName=V2%20Internal%20-%20for%20Tolgee%20Web%20application#/Auto%20Translation/autoTranslate_1) you can use to auto-translate keys.

**Comment by DavithkbY** [comment]
@JanCizmar  For our use case, we want to use the api key with only read rights instead of using static json files with translations in our angular project for production. Is this a safety issue is we only give the api key read rights and nothing else? Because for our use case we really cannot work with static json files in our project since we have crud operations that when creating data in the database, that data needs to be translated in 15 languages. We want to use tolgee for these translations.

Is this a safety issue?

**Comment by JanCizmar** [comment]
Its not a safety issue, but it's not recommended either. You can do it this way for now, but when [CDN feature](https://github.com/tolgee/tolgee-platform/issues/1538) is implemented, you should go for that.

**Comment by DavithkbY** [comment]
> Its not a safety issue, but it's not recommended either. You can do it this way for now, but when [CDN feature](https://github.com/tolgee/tolgee-platform/issues/1538) is implemented, you should go for that.

Alright thank you very much! Is there a place we can donate since we're using self hosting but would still like to contribute to the project!

**Comment by ikbenignace** [comment]
This package is way underrated, has way more features than competitors and such nice incoming updates.

**Comment by JanCizmar** [comment]
> Alright thank you very much! Is there a place we can donate since we're using self hosting but would still like to contribute to the project!

We are just working on features, that will be licensed under BSL also in the self-hosted version. It's enhanced permissions, CDN and Automated Backups. But before that, we will enable the donate button, here. 🤑

**Comment by JanCizmar** [comment]
> This package is way underrated, has way more features than competitors and such nice incoming updates.

@ikbenignace Thanks, you can help us by sharing it on your favorite socials :)
