### ISSUE TITLE
Tolgee affects Angular

### ISSUE THREAD

**Issue by ikbenignace** [tolgee/tolgee-platform#1594]
Hi, it maybe sounds very weird, but since I installed Tolgee in my Angular project, the styles.scss doesn't get updated, if I delete everything in my styles.scss, it doesn't get empty for example.

But this issue only persist on Linux/Mac, not on Windows.

**Comment by JanCizmar** [comment]
Hello! Thanks for reaching out. This is issue for https://github.com/tolgee/tolgee-js .

Anyway... What do you mean by style.scss doesn't get updated? If you remove @tolgee/ngx package, it works again? To me it seems super unlikely this can happen due to Tolgee integration.

**Comment by ikbenignace** [comment]
It were symbolic links in the file structure, nothing to do with tolgee, my fault.
