### ISSUE TITLE
ssl certificate

### ISSUE THREAD

**Issue by roeycohen** [tolgee/tolgee-platform#1595]
First thing first, thank you for this great project :)

Installing Tolgee using Docker is indeed a breeze, but how can we use an SSL certificate?

is it possible to use letsencrypt?

Thanks,
Roey

**Comment by JanCizmar** [comment]
Hey! You can use nginx or traefic as proxy to get it working with HTTPS. I would recommend Traefic, which a have better experience with. Check this: https://doc.traefik.io/traefik/v1.7/user-guide/docker-and-lets-encrypt/

**Comment by roeycohen** [comment]
I've learnt something :) thanks!
