### ISSUE TITLE
delete old translations using API

### ISSUE THREAD

**Issue by roeycohen** [tolgee/tolgee-platform#1596]
Hi,

How can we removed translations no longer in use that we don't want the translators to translate anymore?

this option seems missing here...
https://tolgee.io/api#tag/Translations

**Comment by stepan662** [comment]
You can delete delete whole key by calling this endpoint:
https://tolgee.io/api#tag/Localization-keys/operation/delete_4

Individual translations can be set to null, but they can't be `deleted` as they belong to the key.

**Comment by roeycohen** [comment]
hi @stepan662, thanks for your quick reply, it worked :)

I'm wondering if there's a better way to mark a translation as "obsolete" instead of deleting it, so we can restore it in case it appears again in the future...

**Comment by roeycohen** [comment]
alright @stepan662, thank you :)

**Comment by Martin005** [comment]
Hello @roeycohen!
Sorry I got back to you late.

Could you please describe your translation workflow in a more detail? And would you like to mark the **whole key** as obsolete, or **just a translation** in a selected language?

**Comment by roeycohen** [comment]
hi @Martin005, no problem :)

In our code the keys are English phrases.
Lets say in version **1** the key "how are you today?" appears and the translators translate it.
Later, on version **2**, this key is removed and not longer in use and a new language is added - now we wouldn't want to pay the new language translator for this key.
But, we wouldn't want to the delete the key completely, just in case it will be used again in version **3** -  so we would not need to re-translate it.

I hope this was clear enough...

Thanks for this awesome project,
Roey

**Comment by Martin005** [comment]
@roeycohen
Thanks for the detailed answer!

Currently, the only way I see to overcome this issue (at least partially), is to add a tag to these "obsolete" keys and to instruct the translator to not translate keys with this "obsolete" tag.

In the upcoming future, we will add Tasks (#1548) which would allow you to send for translation only selected keys or keys with the selected tags (whether for new or existing language). I believe this would solve the issue you are facing. Do you agree? 🙂

**Comment by Martin005** [comment]
@roeycohen
Ah yes, namespaces was my other idea 👍

As for the tasks, I can confirm that we are planning that the user would be able to create a task with keys from only the specified namespaces or tags 🙂

Is it okay if I close this issue, then?

**Comment by roeycohen** [comment]
Thanks :)

**Comment by jdimeo** [comment]
#1489 is now implemented as well
