### ISSUE TITLE
Update Cloud Pricing

### ISSUE THREAD

**Issue by Martin005** [tolgee/tolgee-platform#1609]
Current cloud pricing model is far from ideal. We are going to:
 - charge users by translated strings amount, not by translations slots (including untranslated values)
 - introduce Pay as you go model, so users won't be charge for what they actually use without the need for buying a package
 - lower the free translation limit to 1000. For current users we keep the current pricing. So don't worry.

**Comment by ecstrema** [comment]
> * lower the free translation limit to 1000. For current users we keep the current pricing. So don't worry.

Does that apply to organisations created before the pricing change, or to users registered before that date?

Some info seems to be missing in the pricing page, like the number of seats for the self-hosted free plan,  and the number of strings for that same plan.

**Comment by JanCizmar** [comment]
> Does that apply to organisations created before the pricing change, or to users registered before that date?

It does not.

> Some info seems to be missing in the pricing page, like the number of seats for the self-hosted free plan, and the number of strings for that same plan.

For the Free plan the number of strings and seats is unlimited.
