### ISSUE TITLE
it's not possible to add the tag "budget" to a key

### ISSUE THREAD

**Issue by roeycohen** [tolgee/tolgee-platform#1616]
trying to add the tag "budget" or "help" using the UI and/or the API doesn't work.

from the API I get the following error:
org.springframework.dao.IncorrectResultSizeDataAccessException

any ideas?

thanks for everything :)
Roey

**Comment by JanCizmar** [comment]
It's a bug. Let me check what happens.

**Comment by roeycohen** [comment]
hi @JanCizmar, seems like it happened because we made multiple API calls simultaneously.
weird that it caused single Api calls to fail later...

I've removed the tags manually and made the calls one by one and it fixed the problem...

**Comment by JanCizmar** [comment]
Good, but it's a bug anyway. The thing is, there is no unique index in the Tag table/entity, so you are able to create 2 same tags in single project which later causes this issue.

**Comment by roeycohen** [comment]
Hi @JanCizmar thanks for fixing it :)

how can we update our installation in case we using docker?

**Comment by JanCizmar** [comment]
Yes, you can, when it's released.

**Comment by roeycohen** [comment]
any instructions @JanCizmar?

**Comment by JanCizmar** [comment]
Oh, you asked how! Sorry. Basically, run the new docker image with the old volume mapped to it. That's it. Database is updated automatically. Hopefully, you don't have more similar inconsistencies in the DB, so it should work fine. :)
