### ISSUE TITLE
Keys ordering

### ISSUE THREAD

**Issue by AndrewNaumovskiy** [tolgee/tolgee-platform#1622]
Hello!

Add the ability to configure the display of keys.
In the current implementation, they are displayed in alphabetical order.
It would be great to also display in order which keys were added/imported.

**Comment by vrozkovec** [comment]
I'd even go further and allow specifying the order myself, for example if I add a key later for a certain screen, I'd then reassign order to all keys so they are displayed in the order they appear in the screen.
We have an automated process that scans source files and pull keys to Tolgee from there.

Ordinal numbers could be assigned automatically during import, so this feature would not have to be used, but still would allow for other than alphabetic key ordering.

**Comment by ZuzanaOdstrcilova** [comment]
Design of first version of sorting is ready. Now it is waiting for developement.

![Image](https://github.com/user-attachments/assets/3e2fe9e4-d2ae-42fd-bda3-bc191e2fc4f5)

#2487
