### ISSUE TITLE
Make base language optional in projects

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#1623]
We have "Back translation" projects where we go from the target language *back to* the source language and want to see if there is "drift". 

So you might have:
Reference `en-US`: Hello!
Spanish `es-ES`: ¡Hola!
Back traslation: `en-from-es-ES`: Greetings!

and you can see how the meaning changed. We have separate projects for the back translators to work which deliberatly do *not* have the reference language because we want to see what they translate without seeing the original. But that means for these projects there's no such thing as a base language since there are just `xx-XX` and `en-from-xx-XX` pairs.

It has been really confusing for our users to see word counts or progress measured against an arbitrary "base" language from another country just because we have to pick one.

**Comment by JanCizmar** [comment]
This is kind a complex requirement, since base language is used for providing translation memory and machine translation results. Making the base language optional would lead to disabling of these features.

**Comment by jdimeo** [comment]
Understood, if it's not worth it, I get it! thanks for considering.
