### ISSUE TITLE
Default organizations are still being created despite configured not to do so

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-platform#1630]
As previously discussed in Slack, new users are still receiving their default organizations when `tolgee.authentication.user-can-create-organizations=false`

**Comment by JanCizmar** [comment]
Hey! Do you have enabled registrations with `tolgee.authentication.registrations-allowed: true`?

**Comment by wfjsw** [comment]
Yes

**Comment by JanCizmar** [comment]
Because, it doesn't make sense to me. When user registers using public registration form, but `user-can-create-organizations=false`, they have no permissions on the server.

**Comment by JanCizmar** [comment]
It has to be fixed anyway.
