### ISSUE TITLE
Using Redis for Session Storage

### ISSUE THREAD

**Issue by mikebreed** [tolgee/tolgee-platform#1644]
I see in the Tolgee documentation mentions using Redis for cache, and for socket.io, but I don't see any refrence to using it for session storage.  I tried to set "spring.session.store-type" = "redis" [referencing these docs](https://docs.spring.io/spring-session/reference/guides/boot-redis.html) as an Environment variable, but this seems to have no effect. Is it possible to use Redis for session storage with Tolgee and I have the wrong settings, or is this something that is not supported?

**Comment by JanCizmar** [comment]
Hello! Thank for reaching out! 🚀

Can you describe why do you need session storage? SInce AFAIK we don't use session storage at all in the platform code.

**Comment by mikebreed** [comment]
We are running Tolgee in Kubernetes and with multiple pods running I get never get logged in. With only one pod, it works as expected.

**Comment by cyyynthia** [comment]
Tolgee uses stateless Json Web Tokens to authenticate users without sharing a state. Make sure all your instances are configured with the same [`tolgee.authentication.jwt-secret`](https://tolgee.io/platform/self_hosting/configuration#jwt-secret) configuration setting, so they can verify the signatures appropriately.

If unset, all instances will be using a different secret key and the authentication can't work properly.

**Comment by mikebreed** [comment]
Ahh, I see. I generated a random string and set it and it works great now. Thanks!
