### ISSUE TITLE
Missing Option to take screenshot, when api-key permission translation.edit is missing

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-platform#1649]
![Unbenannt](https://user-images.githubusercontent.com/52678724/229450505-b38d193b-8d26-46ab-af49-125ef0e5e2df.png)
Hey everyone,
I encountered an issue (maybe).
If you generate an api-key, which is allowed to upload screenshot, but not allowed to change translations. Is there a way to allow i.e. the developers to upload screenshot, but not editing the translations itself?

Key has the following permissions: translations.view, activity.view, screenshots.upload, screenshots.view

**Comment by JanCizmar** [comment]
It's issue for tolgee-js repo. Can you please recreate it there? https://github.com/tolgee/tolgee-js

**Comment by paulwer** [comment]
@JanCizmar of cause i can do it. can you please verify first, that an upload of a screenshot is possible, within tolgee, when the user  dont have the right translation.edit?

(Is my assumtion right, that the user should have the ability to upload them)

**Comment by JanCizmar** [comment]
Hey, we verified and the error is actually on the both sides. So I've assigned this issue to myself and @stepan662 will fix the tolgee-js part.

**Comment by stepan662** [comment]
https://github.com/tolgee/tolgee-js/pull/3190
