### ISSUE TITLE
Question: Strategy for translations in different dev environments

### ISSUE THREAD

**Issue by stefandevo** [tolgee/tolgee-platform#1653]
Hi,
Just wondering what the best strategy is for dev environments.
Should I create projects "dev" "beta" "prod" to have different dev environments?
Is there an easy path to move "dev" keys and translations to "beta" to "prod"?
Any suggestions welcome!

**Comment by JanCizmar** [comment]
Hey! Thanks for the question! Do you really need multiple environments for localization data? Can you maybe describe your use case more deeply?

**Comment by stefandevo** [comment]
When working on a new version of the application, you need to add new keys, change some existing keys with corrected translations.
However, during development, you don't want to change production keys yet. When you need to do a fix in production, you still want the original set of production keys to be present in the CI.

So I am not sure what would be best; use different projects and merge keys from one project to another to have this kind of feature?

**Comment by JanCizmar** [comment]
We recommend keeping all the translations in a single project as we think of translations of something different than the application code. When you fix a translation, in most cases, you want to fix it environment wide; not just in prod/dev, and in cases where you really need to have a different value for a different branch, you may use a different translation key. 

For production mode, you should not use data from Tolgee API but data exported as static assets, so changes in Tolgee are not reflected in the production environment before you refresh the exported files.

Anyway, we plan to add [branching feature](https://github.com/tolgee/tolgee-platform/issues/1550) in the future, but we are still concerned about the complexity it would add both to Tolgee and user workflows.

So if you really need it, you can indeed use two separate projects and manually sync the data between them using the API, but as I said, I would recommend not to and just sticking with the single project.

**Comment by stefandevo** [comment]
Ok @JanCizmar thanks for your insight and advice!
