### ISSUE TITLE
Translation memory bug

### ISSUE THREAD

**Issue by AndrewNaumovskiy** [tolgee/tolgee-platform#1658]
Is there any logging I can turn on to help you debug the app?
![image](https://user-images.githubusercontent.com/32496284/232085555-2d1360fd-9e5a-427e-ba9e-11584549ebae.png)

**Comment by JanCizmar** [comment]
Hello, 500s are printed to the stdout, but 400 are not since they normally contain self explanatory error codes. This case is weird, since the API responses with JSONs not with HTML when they're called from the frontend. 

Can you share what happens in the network tab of your browsers dev tools?

**Comment by AndrewNaumovskiy** [comment]
@JanCizmar Sure

I don't think the issue is in any character but in the amount of them. 

![image](https://user-images.githubusercontent.com/32496284/232087794-f43aa114-8b07-4fa1-a6ef-026c9da07ca7.png)
![image](https://user-images.githubusercontent.com/32496284/232087991-ada64f38-3deb-4212-baf4-afa50f3ab690.png)

**Comment by JanCizmar** [comment]
Can you show also the response?

**Comment by AndrewNaumovskiy** [comment]
The response in 
`<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>`

**Comment by JanCizmar** [comment]
Can you please also share the base text?

**Comment by AndrewNaumovskiy** [comment]
Я за лічені хвилини промерз та покрився гусячою шкірою. Добре, що моя улюблена куртка була хоча б більш-менш теплою.\nЧоботи набралися води та гидко чавкали при кожному кроці.\nЗ наближенням до кручі вітер посилювався. Я навіть зміг почути страшний звук, з яким великі хвилі розбивалися об скелі.\nЯкий же кошмар опинитися в морі в таку погоду. А ніхто ж навіть не попереджав про такий циклон!\nЯ на мить зупинився та напружив зір.\nСпереду щось було. Спахнула блискавка, і на мить я зміг розгледіти зелений браслет.\nВін зачепився за кущ, що ріс на схилі, та тремтів від вітру, ніби піратський прапор.\nЯ обережно спустився по схилу, з усіх сил намагаючись не послизнутися.\nЦе точно був її зелений браслет. Я оглянув землю - жодного натяку на сліди.\nМої руки трусилися, але вже не від холоду. Мозок за секунду намалював до жаху реалістичну картину.\nАгата послизнулася та покотилася по мокрій траві зі схилу.\nНаближаючись до прірви, вона спробувала ухопитися за гілки куща, але в неї не вийшло.\nТреба було зробити один крок уперед та подивитися вниз.\nОсь він, абсурд, який нас бісить, коли ми критикуємо фільми.\nЯ знав, що побачу на дні прірви, але чомусь не міг змусити себе ступити вперед та подивитися.\nНе знаю, як довго я простояв, наче вкопаний, стискаючи в руці зелений браслет Агати.\nЯкоїсь миті, я таки наважився.\nСтрумочки води, що бігли вниз, швидко заповнювали дно прірви калюжами.\nЯ нахилився та придивився. Важко було розгледіти у деталях, але там точно не було нічого, що хоча б частково нагадувало людину.\nНіхто туди не падав, схоже, я дарма хвилювався.
