### ISSUE TITLE
Add "exclude" filtering option 

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#1664]
It would be great to have a "exclude" option in the Tag and Namespace filter 

E.g. at the moment, I am able to filter missing translations that are drafts but I am not able to filter the missing translations that are not drafts.
<img width="678" alt="Snímek obrazovky 2023-04-17 v 14 03 33" src="https://user-images.githubusercontent.com/75572718/232478830-95dcbde5-45d9-473f-b9b3-cf9aa99e76ea.png">

user feedlack: it would also be cool to filter by multiple tags like one key has to have all the selected text and currently its and-or

**Comment by JanCizmar** [comment]
@ZuzanaOdstrcilova can you consider it as a part of the filters update?

**Comment by ZuzanaOdstrcilova** [comment]
Design is ready.

![Image](https://github.com/user-attachments/assets/3e78833b-5980-4a92-b125-b851a701eb39)


It is part of new issue: https://github.com/tolgee/tolgee-platform/issues/2777
