### ISSUE TITLE
Export to .po

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1712]
We need the export to .po files for the unreal engine integration.
- [x] Export to .po by simply exporting the string msgid, msgstr
- [x] Support single plurals in strings

**Comment by KaptinLin** [comment]
any plan on export to .po?

**Comment by budak7273** [comment]
Export to `.po` would be quite useful

**Comment by Anonyfox** [comment]
any updates here? we would need it in order to use tolgee with [Phoenix](https://phoenixframework.org/) or switch to a different i18n tool soon

**Comment by sbsce** [comment]
I need this as well

**Comment by JanCizmar** [comment]
This was covered in https://github.com/tolgee/tolgee-platform/issues/1547

So I am closing this. Do you folks need other message formats the C/C++ and PHP?
