### ISSUE TITLE
Default organisation configuration setting

### ISSUE THREAD

**Issue by steffans** [tolgee/tolgee-platform#1718]
By disabling the `tolgee.authentication.user-can-create-organizations` it would be nice to have a `tolgee.authentication.user-default-organization` setting. Then all new users would automatically be added to the default organisation which would easily allow sign ups for community translations. Without having the public projects yet, https://github.com/tolgee/tolgee-platform/issues/1360

**Comment by JanCizmar** [comment]
HI! Thanks for proposal. You can provide invitation links to projects / organization. Or is there some use case which this doesn't cover?

**Comment by steffans** [comment]
Hi Jan, to my understanding the invitation links only work for single users. I would like an open community registration so anyone can sign up and be a member of the default organisation (eg. for open source projects).

**Comment by JanCizmar** [comment]
Oh, well. This will be covered in #1360. I understand what you want to achieve but it won't be very secure. Community translations will address anything you wish including it will be safe.

Anyway, I would like to hear more about your use case. If are open to share your thoughts on Tolgee at general or specifically community translations, please join our community [Slack](https://tolg.ee/slack).
