### ISSUE TITLE
Tags interpolation in Vue 3

### ISSUE THREAD

**Issue by bitbybit** [tolgee/tolgee-platform#1751]
Can please anybody guide me how to implement this behavior with a Vue component properly?
https://tolgee.io/js-sdk/integrations/react/tags-interpolation

vue-i18n for example has special slots for that:
https://vue-i18n.intlify.dev/guide/advanced/component.html#slots-syntax-usage

That variant outputs plain text instead of HTML:

```
import { FormatIcu } from '@tolgee/format-icu'

// ...

Tolgee()
      .use(FormatIcu())

// ...
```

```
<T
  default-value="test1 <test>test2</test>"
  key-name="test"
  :params="{
    test: (content) => `<i title='${content}'>${content}</i>`
  }"
/>
```

**Comment by bitbybit** [comment]
Although with vnode function it seems to be working

```
import { h } from 'vue'
```

```
<T
  default-value="test1 <test>test2</test>"
  key-name="test"
  :params="{
    test: (content) => h('i', { innerHTML: content })
  }"
/>
```

**Comment by bitbybit** [comment]
@stepan662 thanks for the reply

Honestly, I am not in the position to make some expert assumptions here 😅 I just wanted to make sure that at least the way I am doing it will not break things later on because of the lack of documentation on the matter.

The slot-solution seems like a bit more Vue-ish to me. Or maybe some helper component for that.

`h()` possibly could become a pain for more complex nested tags structure. Also, I am not enterily sure if is it possible to pass components as an argument (probably, yes) there.

**Comment by stepan662** [comment]
Ok, once I'll do a bit more research on this I'll try to implement it.

**Comment by stepan662** [comment]
Solution for this was implemented in https://github.com/tolgee/tolgee-js/pull/3327
