### ISSUE TITLE
catalan flag is wrong

### ISSUE THREAD

**Issue by frnandu** [tolgee/tolgee-platform#1752]
should be according to https://en.wikipedia.org/wiki/Estelada
something like this:

![Estelada_blava svg](https://github.com/tolgee/tolgee-platform/assets/1931672/eb5979be-1f6d-4c13-afc8-f479666a0e67)

**Comment by JanCizmar** [comment]
Hello. We are using emojis as flags. If you would like to add Catalan flag support, feel free to create pull request to https://github.com/tolgee/language-util

**Comment by Martin005** [comment]
@frnandu
Hello 🙂
I don't think you are correct with the flag suggestion. You are proposing "Estelada" which is a flag used by supporters of the independence of Catalonia, but the "official" flag of Catalonia is "[Senyera](https://en.wikipedia.org/wiki/Senyera)".

As we are using emojis for flags, we are following the Unicode standard that concluded that "Senyera" should be used as the flag for Catalonia.

You can learn more about the "Senyera" flag in Unicode [here](https://www.unicode.org/L2/L2017/17382-rgi-flag-omnibus.pdf#page=9) 🙂
