### ISSUE TITLE
Project ID is not shown in project dashboard

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1756]
For usage with Tolgee CLI, user has to find their project ID. It's not optimal they have to extract it from address.

**Comment by cyyynthia** [comment]
It seems the regression was introduced here: https://github.com/tolgee/tolgee-platform/commit/a9cdd442ecd1c25776346c2056b8944b1ca5d959 in `webapp/src/views/projects/ProjectListView.tsx`

By adding the organization usage in `navigationRight`, it overwrites the Project ID label defined higher up in the component tree.

**Comment by stepan662** [comment]
Connected to https://github.com/tolgee/tolgee-platform/issues/2207
