### ISSUE TITLE
Homepage improvements

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#1757]
- [ ] Add Calendly widget
- [ ] Add Video Ask
- [ ] Add curly arrow to the first screen of website
- [ ] Add Capterra button `
<a href="https://www.capterra.com/reviews/278005/Tolgee?utm_source=vendor&utm_medium=badge&utm_campaign=capterra_reviews_badge"> <img border="0" src="https://assets.capterra.com/badge/7da1869535ec85f42df2a7cc09e8d270.svg?v=2225987&p=278005" /> </a>`

**Comment by JanCizmar** [comment]
@marketachalupnikova This should me moved to https://github.com/tolgee/documentation
