### ISSUE TITLE
Improve changes loss protection for the translation editor

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#1778]
The warning close dialog appears only if you click another cell, but not when you click some other action (like filters).
![Zrzut ekranu (19)](https://github.com/tolgee/tolgee-platform/assets/8831144/78d04a90-4167-49ab-951c-56557030a32b)

**Comment by stepan662** [comment]
We should also think about how to prevent loss of data when you e.g. close the browser or tab or go to different page.
Protection by `onbeforeunload` is not perfect, so this might be solvable by storing in localstorage, so it's available when you re-open the editor.

However I'm not sure if it won't be confusing if you open a translation and in the editor will be different text than expected.

**Comment by JanCizmar** [comment]
Well, it's web. So I guess onbeforeunload is enough.
