### ISSUE TITLE
Permanent invite links

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1779]
I'm using Tolgee as a crowdsourcing localization platform. At the moment, I have to individually send everyone invite links, which is a lot to manage for a big project.

Could the invite links have a toggle to be permanent and not expire after use?

**Comment by JanCizmar** [comment]
Hi! Thanks for the query and idea! 🤩 

In most cases you want to set specific language permission for specific users. For example English speaking translator should be able to modify only english strings. Sending the same invitation link to multiple users is currently security hazard. We are working on Community translation features, which aims to help admins like you to securely manage community translated strings.

But for now, we don't want to add this feature for the described security reasons.
