### ISSUE TITLE
5XX - HTTP Error after deleting a key on UI

### ISSUE THREAD

**Issue by horstmannmat** [tolgee/tolgee-platform#1780]
After deleting a key from a project on the UI, I cannot upload it anymore by using the `tolgee-cli push` command
I manage to replicate it twice.
Steps: 

1. Import JSON files from your i18n directory, 
2. Add new keys and use  `tolgee-cli push` to push it to the server (works fine)
3. Delete a key in UI and also and in the JSON files.
4. Use  `tolgee-cli push` to push it to the server (500 or 504 (timeout))

[error.txt](https://github.com/tolgee/tolgee-platform/files/12005009/error.txt)

**Comment by JanCizmar** [comment]
Hello! Thanks for reporting. I am afraid the error isn't related to error you're facing. Is there something else suspicious happening in the log?

**Comment by horstmannmat** [comment]
Hi, I manage to reproduce it again, here are the full logs of the output
[error_full.txt](https://github.com/tolgee/tolgee-platform/files/12052100/error_full.txt)

**Comment by JanCizmar** [comment]
Hey! This is fixed in latest (with 99% probablity).
