### ISSUE TITLE
User specific statistics

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1783]
I am using Tolgee as a crowd source localizatiln platform, and I would like to have access to how many translations a single member has done and see their individual logs. This is to include them in the game's (I'm localizing my game) credits if they contributed a lot.

Currently it seems like this isn't possible

**Comment by JanCizmar** [comment]
Hi there! Unfortunately, Tolgee doesn't support this yet. But it's planned as a part of #1548.

**Comment by JanCizmar** [comment]
We can also add it to #1360 .
