### ISSUE TITLE
Support for nested YAML

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1785]
Tried to search for this, but couldn't see it supported yet. I'm using Tolgee for a Flutter game, and I'm using nested yaml on the localization files. Is support for this planned?

Currently, I need to convert my yaml to json, and then import them on Tolgee. Would be awesome if Tolgee could do that, or just support nested yaml in the first place

**Comment by JanCizmar** [comment]
This is part of #1547

**Comment by Schamppu** [comment]
Just an heads up for anyone who might be in similar situation as I am (working with yaml):

You can use [yq](https://github.com/mikefarah/yq). I created a script that converts all of my yaml files to JSON, and converts imported files back to yaml. Works like a charm in the meantime.
