### ISSUE TITLE
"500: Error status code from server" when trying to edit translations

### ISSUE THREAD

**Issue by Zaegkzis** [tolgee/tolgee-platform#1789]
I am getting this error everytime I try to write translations. I am the only one in my team having this issue.
![image](https://github.com/tolgee/tolgee-platform/assets/130304995/643b4c83-32b3-4d90-b0b7-7abf90b85cca)

**Comment by JanCizmar** [comment]
Hello! Are you using Tolgee cloud or does it happen on self-hosted instance?

**Comment by Zaegkzis** [comment]
> Hello! Are you using Tolgee cloud or does it happen on self-hosted instance?

I'm using Tolgee Cloud with my GitHub account

**Comment by JanCizmar** [comment]
I've checked the logged errors and it might be related to the Tolgee Translator. Do you have Tolgee translator enabled as translation service in the project? Does this happen for every translation or only for some of them?

**Comment by JanCizmar** [comment]
Well, I've checked it again and strange. Can you please share what does your network tab content of developer tools in your browser looks like when this happens? Maybe some adblock or another plugin messing with the requests.

**Comment by Zaegkzis** [comment]
I'm not quite familiar with the developer tool but I hope that's what you need : 

![image](https://github.com/tolgee/tolgee-platform/assets/130304995/8f45a871-6cc3-459a-906e-91da9b5854ba)

**Comment by JanCizmar** [comment]
Hey! I've found out that you're actually not using our cloud, so I could not see the error logged. You will have to ask your server admins to analyse the server logs.

We also offer advanced support as a part of our Business plan for self-hosted instances. https://tolgee.io/pricing/self-hosted#pricing-toggle

With such subscription your request would get high priority and special care from our side.

**Comment by Zaegkzis** [comment]
Alright thank you for your help :D

**Comment by JanCizmar** [comment]
No problem! If you can get a printed Stacktrace from the server, we can probably find out what's happening. 👀
