### ISSUE TITLE
Ctrl + Enter, saves but takes me outside of the editing box, 

### ISSUE THREAD

**Issue by Andrzej-Hochul** [tolgee/tolgee-platform#1794]
Ctrl + Enter, saves but takes me outside of the editing box, I would like to have an auto save feature or very llist to continue editing in the same spot, alike to ctrl + s in regular applications

**Comment by stepan662** [comment]
You can also hit just Enter to save.

**Comment by Andrzej-Hochul** [comment]
> You can also hit just Enter to save.

It also takes me outside of the editing box ;(

**Comment by JanCizmar** [comment]
Hey! That's weird. 🤔 Can you please provide a video of this behaviour?

**Comment by Andrzej-Hochul** [comment]
> Hey! That's weird. 🤔 Can you please provide a video of this behaviour?

Forgive the professionalism on this https://photos.app.goo.gl/qvzfor3z2pW59C5g7

**Comment by stepan662** [comment]
So if I understand it correctly: You are editing a long text in the editor and you don't like that saving button also closes the editor. Also if you close the editor, it scrolls outside the list. Right?

**Comment by Andrzej-Hochul** [comment]
It Also scolls outside the list, yes, but that's minor to me. it's more annoying that saving closes the editor, since I like to save every sentence more or less,  because I am prone to misclicks like F4 or clicking tags, that pulls me out of the editor mode without confirmation... you see

**Comment by stepan662** [comment]
Well, the situation is following:
 - Current Tolgee layout is not well prepared for a long long translations and the scrolling thing is kinda part of that (we'll try to address it in the future)
 - Saving without closing the editor doesn't fit this case, we don't have a concept of "draft", which would be necessary in this case

As quick fix for now I'm preparing an improved protection against accidental closing of the editor (it catches clicks on filters and tab closing). We'll release it asap.

**Comment by Andrzej-Hochul** [comment]
that should work for me
