### ISSUE TITLE
Adding tags & screenshots with multiselect

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1798]
When adding new tags, I often find myself needing to add the same tag to at least a hundred keys. Tolgee already has multiselect, so could that be utilized for adding same tag for more than just one key at a time?

Same goes for screenshots.

Also, I'm looking forward on getting this issue resolved #1782

**Comment by Martin005** [comment]
This will be solved in https://github.com/tolgee/tolgee-platform/issues/911
