### ISSUE TITLE
Written context for keys

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1799]
Hello!

As I'm working on translating a game with Tolgee, context is a huge deal. The screenshots are great, but as the game is not released but already being translated by the public (who don't have access to it), I've had to explain a lot of the contexts multiple times on our localization Discord channel.

Could it be enabled that in addition to tags and screenshots, we could write a description for the key that gives more context?

**Comment by Martin005** [comment]
Hello @Schamppu!
There is already an issue for this: https://github.com/tolgee/tolgee-platform/issues/918, so I will close this one as a duplicate.
