### ISSUE TITLE
In-depth changelog

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1800]
Currently, when watching the changes, you can't get a very in-depth listing of what has changed. Could this be expanded with a better list that would have filters (for languages, users, times etc.) and sorting?

**Comment by JanCizmar** [comment]
That's true. Please define what filters exactly would you like us to implement.

**Comment by Schamppu** [comment]
Filters:
- By user
- By language
- By namespace
- By tags
- Between dates
- By the type of change (has it been reviewed, changing keys, translating)

Sorting options similar to filters would also be great.

**Comment by JanCizmar** [comment]
This is covered in #2244.
