### ISSUE TITLE
Building your own login logic to self hosted Tolgee

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1801]
Would it be possible to make a easily modifiable authentication way for the self hosted Tolgee? My game already has registration elsewhere, and it would be awesome if people who have authenticated there could also login to our translation platform?

With good documentations to go with it, it would be very cool.

**Comment by JanCizmar** [comment]
Well, you can directly modify the data in the database to do so. You can also generate a JWT token for your users outside of Tolgee and then use the JWT token to authenticate. However, you need to know user's id in Tolgee DB to generate such key. You can explore the key generation here: https://github.com/tolgee/tolgee-platform/blob/a9327aa8507a90d926e764be1a1d5642e74e312a/backend/api/src/main/kotlin/io/tolgee/security/JwtTokenProviderImpl.kt#L4

**Comment by Martin005** [comment]
And you can also use custom [OAuth2 login configuration options](https://tolgee.io/platform/self_hosting/configuration#oauth2) :)
