### ISSUE TITLE
Setting export format nested by default

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1805]
Hello! Sorry that I'm posting so many issues over here, but I try to mention every improvement that I might find in Tolgee.

Could it be possible to have default export settings? I never change how my files are exported, as they are always exported as nested JSON, which I then convert to yaml with [yq](https://github.com/mikefarah/yq) as there isn't support for nested yaml yet.

But I sometimes forget to press the "nested structure" button on Tolgee. Could there be added an option on the configuration files of Tolgee to have this selected by default? Or if not on the config files, just on the project settings page?

**Comment by JanCizmar** [comment]
You can create a script, which will do this for you automatically. This is currently out of scope for us.

**Comment by cyyynthia** [comment]
By the way, if you're already using CLI tools you might be interesting in fetching strings using the [Tolgee CLI](https://tolgee.io/tolgee-cli) which does have a way to [configure pull sources and the delimiter](https://tolgee.io/tolgee-cli/project-configuration) using a `.tolgeerc` file
