### ISSUE TITLE
Automated memory translations didn't work

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1807]
Hello!

I restructured my localization files today, which meant that all of the keys were changed. I was pleased to see that there was an option to have new keys automatically filled with memory translations.

When I did this, the keys were not filled though, seems like this feature is broken. Filling those manually wasn't too bad though, as the memory translation does still work to suggest stuff from the previous keys. All are 100%, which was the requirement for the feature to work. 

But it would be very nice to have this fixed. My way of adding new stuff was a bit unorthodox, which might have been causing this:
- All of my old keys were not assigned to a namespace.
- All of the restructured keys were assigned to namespaces.
- I'm using the reverse proxy setup. Didn't check logs yet.

Either the feature doesn't work at all, or it might have something to do with namespaces or my setup? Or then I understood it wrong.

**Comment by Martin005** [comment]
Hello @Schamppu 🙂

Did you import the new files using CLI, through UI to import whole file or through API?
All of these options currently don't run automatic translation on the imported keys.

Currently, we are close to releasing [Batch Operations](https://github.com/tolgee/tolgee-platform/issues/911) where you will have an option to pre-translate selected keys using TM. After we release that, we will re-work a bit how the Automatic translation works.

**Comment by jdimeo** [comment]
I just confidently told a user his keys would be machine translated upon import and... they weren't. Whoops.
(I had only used API calls myself, but he is using UI import and/or CLI)

**Comment by JanCizmar** [comment]
Batch operations are released, so this is now possible! 🚀
