### ISSUE TITLE
Option to bring screenshots & comments to new keys

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1811]
Would it be possible to have a way/toggle to bring screenshots & comments to new keys that have 100% memory translation? It's currently very difficult and requires a lot of manual tinkering to bring the screenshots to new stuff if you add lots of new keys, or restructure your localization and need to delete the old ones.

**Comment by JanCizmar** [comment]
Hello! Can you descibe it more deeply. I don't really understand what you mean. Thanks! 🐁
