### ISSUE TITLE
Unable to use brackets as the value .translation giving extra bracket

### ISSUE THREAD

**Issue by srinath-sarva** [tolgee/tolgee-platform#1826]
when I use tolgee.t('haikey',hai(s)');
The html is being displayed as hai(s))
Only one bracket should come ..but two are coming

**Comment by JanCizmar** [comment]
Hello! Thanks for the query, but I am afraid you need to specify it more.

**Comment by srinath-sarva** [comment]
no need of any explaination .Just try to translate any text which have brackets in that.U will get extra brackets.Pls resolve the issue

**Comment by srinath-sarva** [comment]
try translating this "Hello how are the apple(s)" You will get problem with brackets

**Comment by stepan662** [comment]
What do you mean by translating? That sounds like in platform, but you've listed an example with tolgee SDK, I'm a bit confused.
