### ISSUE TITLE
Support for external PostgreSQL server

### ISSUE THREAD

**Issue by nuclon** [tolgee/tolgee-platform#1853]
I could not find in the documentation, how I can set up tolgee to use an external PostgreSQL server.
It looks a bit weird, that there are just two options, Embedded and Docker. What about "External"?

**Comment by codeagencybe** [comment]
It is in the documentation under data source: https://tolgee.io/platform/self_hosting/configuration?config-format=yaml#data-source-settings

**Comment by nuclon** [comment]
Thanks. I was looking in the wrong section :)
