### ISSUE TITLE
Enhance exporting 

### ISSUE THREAD

**Issue by ortiort** [tolgee/tolgee-platform#1862]
**Feature request**

Our use case:

* For some English translations we are working with an external translator
* The translator doesn't translate in Tolgee, but gets the exported files

In Tolgee we handle our translations as follows:
* We always provide German (our base language) and a first English translation, because many of our developers work with our English UI and we don't want to see them keys
* However, now we have the issue that we can't easily export these keys for translation
* Internally we have a tag "needs translation" and the English version is not reviewed.
* But in Tolgees export section, we can't select "Export all keys with the tag xyz". This would be very helpful for us.
* Moreover it's only possible to select the state "Reviewed", but not "Not reviewed". 

New options for export:

* Select a tag and only export keys with this tag
* Select the state "Not reviewed"

**Comment by JanCizmar** [comment]
Hey! Thanks for the query. You already can export the "Not reviewed" data by selecting translations only in Translated state.

Exporting keys with specific tag is not yet possible. Thanks for the request. :)

**Comment by Martin005** [comment]
The exporting key with tags was already requested [here](https://github.com/tolgee/tolgee-platform/issues/1519) 🙂

**Comment by ortiort** [comment]
Okay, thank you :-)
