### ISSUE TITLE
Incorrect way of handling new translations for a key

### ISSUE THREAD

**Issue by cyperdark** [tolgee/tolgee-platform#1884]
So i tested self-hosted version and find out that current way of editing approving translations is strange.

<br>

1. If two different people suggest different translations, i can't pick one of them, i can only approve latest, or copy one i like and submit it and then mark as reviewed
2. if translation was marked reviewed and someone change it, it'll be automatically approved, even if suggestion is non-sense
3. there is no button to choose which translation i want to use as default (video attached)

<br>

https://github.com/tolgee/tolgee-platform/assets/21735205/11f5420a-d77d-417b-8226-e87230ebf80c

history:
![image](https://github.com/tolgee/tolgee-platform/assets/21735205/87db6c24-3b30-4523-8fc7-2fb09dfc3d6f)

**Comment by JanCizmar** [comment]
Hello! The editing in the editor is not "suggesting", you're editing the actual value. We don't have a concept of suggesting implemented yet. It's a part of #1360.

**Comment by cyperdark** [comment]
oh, i see. Sadly it will be only in december
