### ISSUE TITLE
Error request url

### ISSUE THREAD

**Issue by Ardear** [tolgee/tolgee-platform#1893]
When I trying to login tolgee, I meet error:
<img width="1920" alt="截屏2023-09-04 15 14 37" src="https://github.com/tolgee/tolgee-platform/assets/57893417/24a991d6-6b6b-432e-867a-f4be024763e6">

I notice the `generatetoken` request url is `http://localhost:8080/api/public/generatetoken`, but `inital-data` request url is `http://localhost:8080/v2/public/initial-data`. 

I think maybe the `generatetoken` request url is wrong?

**Comment by JanCizmar** [comment]
Hello, the request is correct. You've probably added your initial-user and initial-password configuration after running the server with authentication disabled. Try clearing the database and run it again.

**Comment by Ardear** [comment]
> Hello, the request is correct. You've probably added your initial-user and initial-password configuration after running the server with authentication disabled. Try clearing the database and run it again.

My mistake， thank you
