### ISSUE TITLE
same person shouldn't be allowed to translate and review 

### ISSUE THREAD

**Issue by ppvnf** [tolgee/tolgee-platform#1908]
sometimes I see people marking strings directly as reviewed even though they just translated. I think the first person to translate should only be allowed to mark as translated (unless someone else modify the original translation) and the others should only be allowed to mark as reviewed

**Comment by stepan662** [comment]
Hey, what you are describing is possible with granular permissions (paid feature). However even with basic permissions, if you set permission to "translate", user will not able to be change the review state.

**Comment by ppvnf** [comment]
that seems to be the case, thanks
