### ISSUE TITLE
Issue when trying to use staticData

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-platform#1922]
Hey everyone, 
I followed the example [here](https://tolgee.io/js-sdk/providing-static-data) to use tolgee in production and encountered a strage behavior (from my perspective).

When generating the language file some text-keys are not exported as a component from the module, but are exported as default export.
By just using the () => import() syntax this results in a behavior, where only the exported components are used for translation.
f.ex. tags like liveMachine.childrenLiveMachine are ignored within replacement and display the tags itself...

My fix was the following: (using the default export of the modules, where all properties are present)
```
export const tolgee = Tolgee()
  .use(DevTools())
  .use(FormatSimple())
  .init({
    language: "en",
    staticData: {
          en: () => import("./locales/en.json").then((m) => m.default),
          de: () => import("./locales/de.json").then((m) => m.default),
          fr: () => import("./locales/fr.json").then((m) => m.default),
          it: () => import("./locales/it.json").then((m) => m.default),
          ru: () => import("./locales/ru.json").then((m) => m.default),
        },
  });
```
you can also take a look at "Only matching manufacturers of your machines are displayed" the generation looks here also quite strange, but after my fix it worked...

Here is the generated file:
```
const e = {
    access_denied: "Kein Zugang. Kontaktieren Sie den Support für weitere Informationen."
}
  , i = {
    disabled: "Gerät deaktiviert",
    disabledDataAccess: "Datenzugriff deaktiviert",
    moduleId: "Modul-ID",
    moduleName: "Externer Modulname",
    moduleSlaveId: "Modul-Slave-ID",
    noLiveMachineAssigned: "Keine Live-Maschine verknüpft",
    suggestedSerialNumber: "Vorgeschlagene Seriennummer"
}
  , n = "Maschine"
  , r = "Abmelden"
  , a = "Hersteller"
  , t = "Neu"
  , l = "Benachrichtigung"
  , o = "Produktgruppe"
  , s = "Profil"
  , c = "Suche"
  , u = "Einstellungen"
  , h = "Status"
  , d = {
    start: "Tour starten"
}
  , g = "Anzeige"
  , v = {
    "Activity Timeline": "Aktivität",
    "All Manufacturers are displayed": "Alle Hersteller werden angezeigt",
    "All ProductHierarchies are displayed": "Alle Produkthierarchien werden angezeigt",
    "Current Organization": "aktuelle Organisation",
    currentOrganizationSelect: e,
    iotDevice: i,
    liveMachine: n,
    "liveMachine.childrenLiveMachine": "angeschlossene Live-Maschinen",
    "liveMachine.constructionDate": "Baudatum",
    "liveMachine.list.view.admin": "Admin-Ansicht",
    "liveMachine.list.view.manufacturer": "Hersteller-Ansicht",
    "liveMachine.list.view.organization": "Organisation",
    "liveMachine.list.view.user": "Benutzer",
    "liveMachine.listView.view.admin": "Administrator-Ansicht",
    "liveMachine.listView.view.company": "Firmenbezogen",
    "liveMachine.listView.view.user": "Benutzerbezogen",
    "liveMachine.name": "Name",
    "liveMachine.organizationRoles.role.CARRIER": "Träger",
    "liveMachine.organizationRoles.roleDescription.CARRIER": "Organisation, die die Live Machine zum geplanten Ziel transportiert.",
    "liveMachine.organizationRoles.roleDescription.MAINTENANCE_CONTRACTOR": "Organisation, die für die Instandhaltung verantwortlich ist",
    "liveMachine.organizationRoles.roleDescription.MANUFACTURER": "Organisation, die die Live Machine hergestellt hat",
    "liveMachine.organizationRoles.roleDescription.OWNER": "Organisation, der die Live Machine gehört",
    "liveMachine.organizationRoles.roleDescription.RESELLER": "Wiederverkäufer der Live Machine",
    "liveMachine.organizationRoles.role.MAINTENANCE_CONTRACTOR": "Wartungsunternehmer",
    "liveMachine.organizationRoles.role.MANUFACTURER": "Hersteller",
    "liveMachine.organizationRoles.role.OWNER": "Inhaber",
    "liveMachine.organizationRoles.role.RESELLER": "Wiederverkäufer",
    "liveMachine.productHierarchy": "Produktkategorie",
    "liveMachine.serialNumber": "Seriennummer",
    "liveMachine.status.ACTIVE": "Aktiv",
    "liveMachine.status.BROKEN": "nicht einsatzbereit",
    "liveMachine.status.DELIVERED_AT_CUSTOMER": "Kundenlieferung erfolgt",
    "liveMachine.status.DELIVERED_AT_RESELLER": "Händlerlieferung erfolgt",
    "liveMachine.status.INACTIVE": "Inaktiv",
    "liveMachine.status.MAINTENANCE": "Wartung",
    "liveMachine.status.ORDERED": "Bestellt",
    "liveMachine.status.PRODUCTION": "In Produktion",
    "liveMachine.status.STOCKED": "Auf Lager",
    "liveMachine.status.TRANSPORT_TO_CUSTOMER": "Transport zum Kunden",
    "liveMachine.status.TRANSPORT_TO_RESELLER": "Transport zum Händler",
    "liveMachine.status.UNKNOWN": "Unbekannt",
    "liveMachine.userRoles.role.DELIVERY_RESPONSIBLE": "Lieferung verantwortlich",
    "liveMachine.userRoles.roleDescription.DELIVERY_RESPONSIBLE": "Person, die für die Lieferung verantwortlich ist",
    "liveMachine.userRoles.roleDescription.ISSUE_CONTACT": "Ansprechpartner bei Problemen oder Fragen",
    "liveMachine.userRoles.roleDescription.MAINTENANCE_ACCESS": "Temporärer Zugang für Wartungsarbeiten",
    "liveMachine.userRoles.roleDescription.OWNER_RESPONSIBLE": "Hauptverantwortlicher bei der Eigentümerorganisation",
    "liveMachine.userRoles.roleDescription.RESELLER_RESPONSIBLE": "Hauptverantwortlicher bei der Reseller-Organisation",
    "liveMachine.userRoles.roleDescription.SUPPORT_CONTACT": "Ansprechpartner für Fragen und Unterstützung",
    "liveMachine.userRoles.role.ISSUE_CONTACT": "Problemkontakt",
    "liveMachine.userRoles.role.MAINTENANCE_ACCESS": "Wartungszugang",
    "liveMachine.userRoles.role.OWNER_RESPONSIBLE": "Eigentümer verantwortlich",
    "liveMachine.userRoles.role.RESELLER_RESPONSIBLE": "Verantwortlicher Wiederverkäufer",
    "liveMachine.userRoles.role.SUPPORT_CONTACT": "Support-Kontakt",
    Logout: r,
    manufacturer: a,
    New: t,
    "No data available": "Keine Daten verfügbar",
    "No Filter applied": "Kein Filter angewendet",
    "No manufacturers found": {
        "": "Keine Hersteller gefunden."
    },
    "No productHierarchies found": {
        "": "Keine Produkthierarchien gefunden."
    },
    "not available": "Nicht verfügbar",
    Notification: l,
    "Only matching manufacturers of your machines are displayed": {
        "": "Es werden nur passende Hersteller Ihrer Maschinen angezeigt."
    },
    "Only matching productHierarchies of your machines are displayed": {
        "": "Es werden nur passende Produkthierarchien Ihrer Maschinen angezeigt."
    },
    "Organization Roles": "Organisationsrollen",
    "Please select": "Bitte auswählen",
    productGroup: o,
    Profile: s,
    "Read All Notifications": "Als gelesen markieren",
    Search: c,
    "Select a manufacturer first": {
        "": "Wählen Sie zunächst einen Hersteller aus."
    },
    Settings: u,
    Status: h,
    tour: d,
    "Unknown Manufacturer": "Unbekannter Hersteller",
    "Unknown Name": "Unbekannter Name",
    "Unknown ProductHierarchyName": "Unbekannter ProductHierarchyName",
    "User Roles": "Benutzerregeln",
    View: g
};
export {r as Logout, t as New, l as Notification, s as Profile, c as Search, u as Settings, h as Status, g as View, e as currentOrganizationSelect, v as default, i as iotDevice, n as liveMachine, a as manufacturer, o as productGroup, d as tour};
```

Suggested solutions:
- change example on website OR
- change export behavior OR
- change parsing of static files

**Comment by stepan662** [comment]
Hmm, do you encounter any bugs, or just the file looks weird to you?

The nuance of `import()` function depends on your build setup. It also looks like its getting optimized, which is why it looks so weird imho. Also it looks like you are exporting with `structureDelimiter` so it tries to split keys with "." and so when you use the english translation as a key with dot in it, the result looks like this:

```
"Only matching productHierarchies of your machines are displayed": {
    "": "Es werden nur passende Produkthierarchien Ihrer Maschinen angezeigt."
},
```

**Comment by paulwer** [comment]
the generated file does not look consistent. tags like liveMachine.list.view.ADMIN are whole strings as keys and Sentences with an point at the end are formated as objects.
if i do use the default import it works fully, because it contains all tags, but feel free to check if this behavior is realy wanted.

maybe if some projects just use our syntax quite rarely this issue would not be so clearly understood.
f.ex. it just took me 20min to figure out, why certain tags are translated and why others dont.

the behavior leading to the result, that only some keys are translated is, that objects are exported seperatly and string keys are not and therefore only accessable within the default export.

**Comment by stepan662** [comment]
I'll add note about `.then(m => m.default)` to the docs. @JanCizmar and @cyyynthia what do you think about this? I'd be personally for switching default delimiter to "". Could we change this in the CLI?

**Comment by stepan662** [comment]
https://github.com/tolgee/documentation/pull/471

**Comment by cyyynthia** [comment]
I don't mind making the default behavior be "no nested keys"; in some circumstances advanced minification setups can work out the name of the object keys and mangle them more efficiently - but probably very very few people have a setup capable of that so it's not that much of a concern

Within the CLI it's just a matter of changing the arguments `pull` processes and not default to dot - which was done to match the default and expected behavior of Tolgee exports

A flat export is more aligned with what other tools are doing AFAIK, so it makes Tolgee easier to gradually adopt Tolgee while using existing more simple i18n libraries which people are probably more used to

**Comment by JanCizmar** [comment]
Changing the default delimiter to "" would be a breaking change, so I don't support it. This whole thing is a about the build system, Tolgee provides valid JSON. So we should just improve the docs.

**Comment by stepan662** [comment]
Is it such a big change if we make it only in the CLI? The "." separation is very ugly when used with base translations as keys and also is basically completely pointless, since we discourage people from editing translation files manually.

**Comment by JanCizmar** [comment]
It would be still a breaking change, but indeed only for the CLI. Anyway, it would be inconsistent, so the REST API would return different result than the CLI. 

It's not so pointless, not all user's are using Tolgee with the SDKs and might be willing to edit the files manually, read them, etc. And also, we discourage people from using base translation texts as keys.

Although, I have to say if I implemented this essential functionality today again, I would indeed go for the flat variant. But for now I would rather keep it as it is then introduce breaking changes or inconsistencies.

**Comment by cyyynthia** [comment]
I guess this is something that could be kept in mind whenever Tolgee 4 is is around the corner. It would indeed be a breaking change and the CLI still allows having "" as delimiter via .tolgeerc which is the closest we have to "no delimiter by default".

**Comment by JanCizmar** [comment]
Agree.

**Comment by stepan662** [comment]
In the UI the default is no delimiter
![Snímek obrazovky 2023-10-03 v 11 13 18](https://github.com/tolgee/tolgee-platform/assets/8831144/abf14f9c-225c-445b-b6e4-80c456185c26)

**Comment by JanCizmar** [comment]
Yeah, we discussed this while implementing this export UI and we decided to do this this way, since the view looked completely different, users won't be confused with this change.
