### ISSUE TITLE
Document overall concept and context

### ISSUE THREAD

**Issue by raman-nbg** [tolgee/tolgee-platform#1925]
As a Tolgee beginner, I find it difficult to understand the overall concept of Tolgee. For instance, I have the following questions:
- what effect does it have to create separate organizations?
- Is the translation memory shared across orgs or only available within an org? or even only within a project?
- API Key vs Access Token: The documentation describes that API Keys are project specific and access tokens are global. But when to use what?
- How long should you use a project? Is it meant to have an infinite live time?

**Comment by JanCizmar** [comment]
Hey!

> what effect does it have to create separate organizations?

The main use case for organization is on Tolgee cloud, where the organizations are "billing unit", so you can understand organization as a group of users from the same company.

> Is the translation memory shared across orgs or only available within an org? or even only within a project?

Only within a project so far

> API Key vs Access Token: The documentation describes that API Keys are project specific and access tokens are global. But when to use what?

If you need to do basic stuff like exporting data or using in-context tools in the SDKs, use PAKs, if you need to manage user accounts, organizations, create projects etc, use PATs. You can also use PAT for login from CLI, so you can use single PAK to manage multiple projects.

> How long should you use a project? Is it meant to have an infinite live time?
Yes, we are not going to delete your project, unless you don't delete it yourself
