### ISSUE TITLE
Make translation memory available on multiple scopes

### ISSUE THREAD

**Issue by raman-nbg** [tolgee/tolgee-platform#1926]
Currently, the translation memory is per project. Every project maintains its own memory and exactly one memory. It would be helpful to fall back to an organization or even a global memory for new projects.

Can we do this? How would you estimate the effort for this? I would be happy to contribute if this feature fits to the product.

**Comment by JanCizmar** [comment]
Hey! I would be happy to help you with this, we actually planned to add this in this roadmap item #1569.

And organization memory would be a good start, I don't see much use case for some kind of global memory, since in that case you can just use machine translation.

**Comment by JanCizmar** [comment]
If you would like to contribute with this, it would be great if you joined our slack community: https://tolg.ee/slack
