### ISSUE TITLE
Unexpected error while updating a key via chrome extension

### ISSUE THREAD

**Issue by may-symmedia** [tolgee/tolgee-platform#1931]
Hey tolgee team,

we are using the chrome extension at symmedia to update the translation keys. When updating a translation in the frontend, we are currently always getting an unexpected error and the tranlation is not updated. In the tolgee App everything works fine.

![image](https://github.com/tolgee/tolgee-platform/assets/98011329/4e7a210e-6f6f-4b08-80bc-8e36551b8e6a)

**Comment by may-symmedia** [comment]
I have to correct my comment: after refreshing the page, the changes are applied -> the bug is not that serious

**Comment by stepan662** [comment]
Hey, does could you check the network activity in the chrome dev tools and see what error is backend returning?

**Comment by may-symmedia** [comment]
No dedicated error message, only

https://app.tolgee.io/v2/projects/keys/1000741243/complex-update?ak=tgpak_gyytoxzrhb3g25dqozsxeztrojvxk4toge4hcojrgyywqmrt

<img width="752" alt="image" src="https://github.com/tolgee/tolgee-platform/assets/98011329/fdc4b2af-1a24-4c1e-819d-dc51907a6d54">

**Comment by stepan662** [comment]
@may-symmedia be careful, you are exposing your API key in the url (beter invalidate it and generate new one).
So there is no network error, not even an error in console?

Also what version of tolgee SDK are you using?

**Comment by may-symmedia** [comment]
is recreated, thanks for the tipp, I didn't check that.

No, there's no error message.
We are still using SDK 4, so I think you would recommend to upgrade to 5, wouldn't you?

**Comment by stepan662** [comment]
Hey, if it's possible yes, I've tried to replicate your error, but I wasn't successful. Maybe it's some weird edge case, older versions might be more prone to that.
