### ISSUE TITLE
Site-Braking CSS bug - White Gradient - on Firefox

### ISSUE THREAD

**Issue by gabriel-v** [tolgee/tolgee-platform#1936]
What it's supposed to look like: https://tolgee.io/platform/translation_process/translation_memory

What it looks like on Chrome:
![image](https://github.com/tolgee/tolgee-platform/assets/7493327/96a109ad-130e-4719-a405-4f17243b7467)

What it actually looks like on Firefox:

![Screenshot_20231006_175227](https://github.com/tolgee/tolgee-platform/assets/7493327/afee86e9-0030-4e7e-b375-c58d64750fb3)

Tested on https://app.tolgee.io/projects today

The white overlay in Firefox breaks the page because it hides the text.

----

Everything's great otherwise, thanks for making this!

**Comment by stepan662** [comment]
Hey, could you specify the version of firefox, you are using? I've tested this in version 118.0.1 on Mac and I don't see this behavior.

**Comment by thifranc** [comment]
Hi, firefox version is : firefox-esr    115.3.0esr-1~deb12u1 amd64 on debian-bookworm, latest available for my part

**Comment by gabriel-v** [comment]
I confirm this issue on Firefox Extended Support Release 115.3.0esr (64-bit) / linux

**Comment by stepan662** [comment]
I guess I'll have to run it on Linux

**Comment by stepan662** [comment]
I've tested this on ubuntu 22.04.2 and firefox 115.0.2 and the issue didn't appear.
