### ISSUE TITLE
Keep file consistency when importing nested JSON data

### ISSUE THREAD

**Issue by Nikaple** [tolgee/tolgee-platform#1937]
Imported source JSON:
```json
{
  "foo.bar": "FooBar",
  "deeply": {
    "nested": "value"
  }
}
```

Exported file without `Nested structure`:
```json
{
  "deeply.nested" : "value",
  "foo.bar" : "FooBar"
}
```

Exported file with `Nested structure`:
```json
{
  "deeply" : {
    "nested" : "value"
  },
  "foo" : {
    "bar" : "FooBar"
  }
}
```

It's obvious that both file is different from the source file. So we had to use [uni-flatten](https://github.com/Nikaple/uni-flatten) to handle such keys. Original translations are flattened first, and imported to tolgee later. Flattened json:
```json
{
  "[\"foo.bar\"]": "FooBar",
  "deeply.nested": "value"
}
```

Is there any chance that tolgee could find a way to implement similar functionalities? Other platforms like `Localise` can handle this situation well.

**Comment by JanCizmar** [comment]
Hi! Thanks for the query. This is interesting one. I have actually no idea, how we would fix this. Tolgee Platform, does not store the keys in tree structure. The unique id of key is string, so we have to somehow convert the nested json path to single string.

One solution might be allowing you to override default `.` structure delimiter while importing, so you would be able to handle this.
