### ISSUE TITLE
Support for LibreTranslate translations 

### ISSUE THREAD

**Issue by gabriel-v** [tolgee/tolgee-platform#1940]
We have our own LT cluster and are interested in integrating it with Tolgee Self-Hosted. If successful, we intend to contribute the integration.

I see there was an attempt here https://github.com/tolgee/tolgee-platform/issues/1124, but the details are lost in slack.

I also see there was a discussion about billing, which is not relevant in the Self-Hosted context (through it would be easier to count characters in Tolgee, instead of on the LT side as asked in https://github.com/LibreTranslate/LibreTranslate/issues/264).

Request: can you please write here the pointers for how to add a new machine translation backend service? Some general instructions on contributing a new backend would be greatly appreciated.

Thanks!

**Comment by JanCizmar** [comment]
Hey! It should not be a problem for you. Here are the development notes: https://github.com/tolgee/tolgee-platform/wiki

And you can get inspired in this PR: https://github.com/tolgee/tolgee-platform/pull/1253

**Comment by gabriel-v** [comment]
That's great, I managed to get it working locally very quick.

I'll work on this later this month - thanks for the links!
