### ISSUE TITLE
API /v2/projects/{projectId}/import/apply returns 403 for API key with Scope.TRANSLATIONS_VIEW

### ISSUE THREAD

**Issue by azieh** [tolgee/tolgee-platform#1943]
Hello,
I tried to integrate the CI/CD process with Tolgee API. I have created an API Key for that. 
![image](https://github.com/tolgee/tolgee-platform/assets/10528511/20e491ba-6f05-4a1f-9b12-e89e492bbb00)

As you can see on the screen, the API key has selected the scope for TRANSLATIONS_VIEW.

In the code, I found that the scope for TRANSLATIONS_VIEW should be checked on action /import/apply.
![image](https://github.com/tolgee/tolgee-platform/assets/10528511/276b72a7-8225-4c83-993a-6f7b0ed1b221)

So, it should work.
Unfortunately, any action on /import except /import itself returns error 403 Forbidden.

`{
  timestamp: 1697113439518,
  status: 403,
  error: "Forbidden",
  path: "/v2/projects/1/import/apply",
}`

Could you help?

**Comment by JanCizmar** [comment]
Hmm, how are you provifing the API key?

**Comment by azieh** [comment]
I add it as a header 'X-API-Key'. Please note that import files are working correctly. In my scenario the first call is okay, and the second one throws 403.

        `const responseImport = await axios.post('http://mytolgeeurl/v2/projects/1/import', formData, {
            headers: { 'content-type': 'multipart/form-data; boundary=' + bonduary, 'X-API-Key': apiKey },
        });`

       ` await axios.put('http://mytolgeeurl/v2/projects/1/import/apply', {
            headers: { 'X-API-Key': apiKey },
        });`

**Comment by JanCizmar** [comment]
That's weird. Does the API key have all the scopes permitted? 

The permissions are checked inside the import methods, so it decides which permissions are required according to what data are you importing. So translations.view is probably not enough.

**Comment by JanCizmar** [comment]
Ha! Maybe you're calling the axios wrong. You're actually missing the body parameter, so you send the headers as a body, right?

**Comment by azieh** [comment]
@JanCizmar you are right! My apologies. Forgot to add the body as you mentioned....

The correct request looks like 
            `await axios.put(
            'http://translations.in.amusys.pl/v2/projects/1/import/apply?forceMode=NO_FORCE&',
            {},
            {
                headers: { 'X-API-Key': apiKey },
            }
        );`

And it works...
