### ISSUE TITLE
How to check the full history of translations?

### ISSUE THREAD

**Issue by orange-kush** [tolgee/tolgee-platform#1945]
Hello guys! We're using a self-hosted tolgee instance and was wondering if there is a way to see the full list of translations that have happened in tolgee, and which member has done them?

If someone could point out if there's a way to do that I'd appreciate it.

Thanks.

**Comment by JanCizmar** [comment]
Hey! It is. If you can access the database, then all the activity is stored in tables `activity_revision`, `activity_modified_entity`. 🚀

**Comment by orange-kush** [comment]
Amazing, thank you so much!
