### ISSUE TITLE
Default value of `tolgee.authentication.enabled` is not taken into account

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-platform#1953]
I am self-hosting Tolgee with the docker image.

It seems that if `tolgee.authentication.enabled` is not set, then it will not display the login screen even though the default value is stated as `true` (https://tolgee.io/platform/self_hosting/configuration#authentication), I had to explicitely set it to true to see the login page on startup.

**Comment by cyyynthia** [comment]
Hey there, this is actually the intended behavior (which is not correctly documented yet, documentation needs to be updated)

On the docker image authentication is turned off by default, and needs to be explicitly enabled. The documentation has been updated in the Tolgee codebase (documentation for config properties is auto generated), but the mention of this specificity hasn't been integrated to the docs just yet.

**Comment by JanCizmar** [comment]
@cyyynthia Can you please update it? 🙏

**Comment by JanCizmar** [comment]
I finally deployed your big update to Tolgee Cloud yesterday night, so we are ready to go.

**Comment by cyyynthia** [comment]
I'll make a PR, though it seems I did mess up a bit the formatting in the annotations 😅 I'll deal with all that...
