### ISSUE TITLE
Save view in translation

### ISSUE THREAD

**Issue by philippjenni** [tolgee/tolgee-platform#1968]
It would be good if you could define per user the default view the translation or that the setting is saved per project and user. For certain use cases it is better to use the table view instead of the list view.

**Comment by stepan662** [comment]
Good idea, we'll discuss it

**Comment by stepan662** [comment]
We plan to introduce a better single key view, which will change the logic a bit. So I don't want to get into this now, because it might be obsolete quite fast.
