### ISSUE TITLE
Projects getAll endpoint regression

### ISSUE THREAD

**Issue by rgraudin** [tolgee/tolgee-platform#1970]
Many of our automations with Tolgee use the endpoint `GET /v2/projects/` to retrieve the slug information from each project before running other operations. In the last few days I have been tracking that this endpoint is not performing as it had been on our Cloud Instance. The specific error being returned is a `403: API access forbidden`. I’m interested in if this endpoint or its permissions has changed in a recent release.

**Things I have checked:**
- The PAT is accurate, has been regenerated, and I am an organization owner. I had someone else try and they received the same error. A project API token is not being used as I know that would be refused for this request.
- Other operations can be completed from the environment using the same authentication, even `GET /v2/projects/{projectId}`.
- The API spec we are using for this endpoint is up-to-date, as far as I can tell, and I don't see recent releases that relate to this.
- I have confirmed this operation and the overall tool works on our self-hosted environments that are on slightly older versions.
- Confirmed the issue from a simple Insomnia call below (performs as expected on self-hosted).

![simple test](https://github.com/tolgee/tolgee-platform/assets/110696613/4cce7f9f-7b18-4518-99ce-ec2742a4f95a)

As always, thanks for creating a great product! I appreciate the help!

**Comment by JanCizmar** [comment]
Hey! Thanks for the query. We did some larger security refactoring & improving update and this is probably a mistake / bug.

@cyyynthia The `io.tolgee.api.v2.controllers.V2ProjectsController#getAll` is not anotetaded with `AllowApiAccess`, do we have a valid reason why we are not enabling the API access for that endpoint?  If not, I've created a PR fixing it.

**Comment by cyyynthia** [comment]
Not really! The regression comes from the fact the security enhancement changed how tokens are granted access to endpoints; prior to the update PATs were allowed to access almost the entire API (including undocumented endpoints which were not mentioned on the REST API docs on the website). This was changed to an explicit declaration within the code, which also has the benefit of enhancing the public docs!

I don't see a reason to restrict this endpoint at all, we should definitely mark it as allowed for API usage.

**Comment by rgraudin** [comment]
Wow that was quick! Thanks, you're on top of it!

**Comment by jdimeo** [comment]
We notice that cloud is still on v3.35.3 - when will this release ship? right now all of our integrations are blocked on this. Thank you for your fast turn around!

**Comment by JanCizmar** [comment]
It's released. Sorry for the inconvenience!
