### ISSUE TITLE
Create project via API

### ISSUE THREAD

**Issue by raman-nbg** [tolgee/tolgee-platform#1973]
We want to automatically create projects via API, as we have another master/leading system owning the projects. For ease of use we want to create the Tolgee projects automatically.

Currently, the `POST /v2/projects` endpoint can only be used with a bearer token. Can we enable this API to be accessible via personal access token (PAT)?

To my understanding this only requires an annotation on the request method in `backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/V2ProjectsController.kt`. Is this correct?

**Comment by cyyynthia** [comment]
That is correct, plus the addition of `AuthTokenType.ONLY_PAT` in the annotation. You're welcome to open a PR if you desire!

**Comment by raman-nbg** [comment]
Sure, I will do this.

How to update the swagger api? Is this auto generated? Currently, the POST /v2/projects endpoint is not visible in the swagger at all.

**Comment by stepan662** [comment]
Hey, yeah, swagger is auto-generated. It is in the swagger, but you have to switch to the "internal" endpoints.

**Comment by stepan662** [comment]
https://app.tolgee.io/swagger-ui/index.html

**Comment by JanCizmar** [comment]
@Cynthia - this is what I was talking about. [This](https://tolgee.io/api) only shows the api key endpoints, but not the PAT endpoints. 😢

**Comment by cyyynthia** [comment]
> @cynthia - this is what I was talking about. [This](https://tolgee.io/api) only shows the api key endpoints, but not the PAT endpoints. 😢

They actually do! See for example the Organizations section, these endpoints are PAT only. Endpoints not shown there are endpoints that do not have the AllowApiAccess enabled; if you find some missing endpoint then they should be annotated so they become available and documented.

**Comment by JanCizmar** [comment]
But! It actually shows all the project endpoint without the `{projectId}` path variable. And there is ak query param and header with PAK exapmle everywhere.

**Comment by cyyynthia** [comment]
The PAK example comes from the annotations on the AllowApiAccess, they might need to be adjusted. As for the paths, they get filtered here: https://github.com/tolgee/tolgee-platform/blob/43b7eb44932e8223bf415fcb3188741ec8ac76bb/backend/app/src/main/kotlin/io/tolgee/configuration/OpenApiConfiguration.kt#L218

**Comment by raman-nbg** [comment]
@stepan662 thanks for sharing the link. I wasn't aware of this documentation. I only used the one at https://tolgee.io/api. This one does not show the internal endpoints.

**Comment by raman-nbg** [comment]
@cyyynthia I have created a PR under https://github.com/tolgee/tolgee-platform/pull/1979
