### ISSUE TITLE
E-mail notification from comments

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#1984]
It would be so cool if you could mention others in comments like this:

<img width="1812" alt="notification_email" src="https://github.com/tolgee/tolgee-platform/assets/75572718/e95bfd7f-569f-445b-ad8a-087319448afe">

Then a short email notification with a link to this translation key could provide the "spark" to look into it.

**Comment by JanCizmar** [comment]
@cyyynthia might consider this while implementing the notifications.
