### ISSUE TITLE
Make "Select all" more intuitive

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#1990]
![image](https://github.com/tolgee/tolgee-platform/assets/8831144/d3f6f8b6-122b-40ce-b9d0-36c9119021a3) Make this "+" and maybe add a visible label

**Comment by ZuzanaOdstrcilova** [comment]
- add a checkbox and arrow (dropdown) next to the items count
- add arrow (dropdown) next to the checkbox with count 1/250

![Image](https://github.com/tolgee/tolgee-platform/assets/99287646/68ee667e-a04a-4205-a448-3d00214ae8ee)
![Image](https://github.com/tolgee/tolgee-platform/assets/99287646/0088da0d-bca6-440e-bec7-7fa23d8fc8f5)

More:
https://www.figma.com/file/cSobP7nqLgeN4S6f5xyf8y/Tasks-2023?type=design&node-id=511%3A13968&mode=design&t=txvY7gUAouQOdqvN-1
