### ISSUE TITLE
I can't set up authorization

### ISSUE THREAD

**Issue by dmitrydrynov** [tolgee/tolgee-platform#1993]
Hello everyone,

I deployed the platform via Docker. Set these environment variables:
TOLGEE_AUTHENTICATION_INITIAL_PASSWORD=admin
TOLGEE_AUTHENTICATION_INITIAL_USERNAME=admin123
TOLGEE_AUTHENTICATION_ENABLED=true

… and I don't have any authorization process. 

I follow the web application link (an example, http://locahost:8090) and immediately get into the application.
I want to be able to login/logout.
How can I do it?

![image](https://github.com/tolgee/tolgee-platform/assets/4089575/269a02bd-4581-4aea-8e02-503343ed9c2b)

**Comment by JanCizmar** [comment]
Hello!

Can you please share how you exactly provide the env to the docker? Do you use docker compose file or do you run it from the console directly?

**Comment by JanCizmar** [comment]
🎉
