### ISSUE TITLE
XLIFF export is not compliant with XLIFF 1.2 Schema (XSD)

### ISSUE THREAD

**Issue by GeertZondervan** [tolgee/tolgee-platform#2015]
The XLIFF generated by the exporter is not valid according to the official XLIFF 1.2 Schema (XSD).
The XLIFF schema can be found here:
https://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-transitional.xsd

XLIFF 1.2 Documentation: https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html

Currently the output from Tolgee looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>

<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file xmlns="" datatype="plaintext" source-language="en" target-language="en">
    <body>
      <trans-unit id="Z key" datatype="html">
        <source>A translation</source>
        <target>A translation</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```
When validating this output against the XSD, it will show a couple of errors. You can use any online validator for this, but the JDK validator also confirms this
- The `file` element has an empty namespace (xmlns) attribute. This attribute should not be there.
- The `file` element is missing an `original` attribute.

The XLIFF 1.2 documentations shows an example of what it should look like:
```
<xliff version='1.2' xmlns='urn:oasis:names:tc:xliff:document:1.2'>
   <file original='hello.txt' source-language='en' target-language='fr' datatype='plaintext'>
    <body>
    </body>
   </file>
</xliff>
```

**Comment by JanCizmar** [comment]
Hello! Thanks for sharing. We'll try to fix it next week.

**Comment by JanCizmar** [comment]
Oh! There is a PR! Thanks!
