### ISSUE TITLE
Tranlated/Untranslated percentage should be based on amount of keys translated.

### ISSUE THREAD

**Issue by GeertZondervan** [tolgee/tolgee-platform#2021]
Currently the percentages that shows how much is translated/untranslated for a language is based on the word count.
```
              stats.apply {
                translatedKeys = rawLanguageStats.translatedKeys
                translatedWords = rawLanguageStats.translatedWords
                translatedPercentage = rawLanguageStats.translatedWords.toDouble() / baseWords * 100
                reviewedKeys = rawLanguageStats.reviewedKeys
                reviewedWords = rawLanguageStats.reviewedWords
                reviewedPercentage = rawLanguageStats.reviewedWords.toDouble() / baseWords * 100
                untranslatedKeys = projectStats.keyCount - translatedOrReviewedKeys
                this.untranslatedWords = baseWords - translatedOrReviewedWords
                untranslatedPercentage = untranslatedWords.toDouble() / baseWords * 100
              }
```            

I think it would be better if this percentage was calculated based on the **keys** that have been translated. It gives a better view of the amount of work that needs to be done.

**Comment by JanCizmar** [comment]
Hello! This should probably become an configuration option. From the translator point of view it makes more sense to count the words.

**Comment by krisgerhard** [comment]
+1

Is it possible to convert it into a feature request or should we create new issue?

**Comment by JanCizmar** [comment]
Fot this one, it would be better to create a new issue.
