### ISSUE TITLE
NextJS 14 - Error with Link component

### ISSUE THREAD

**Issue by marcosriver** [tolgee/tolgee-platform#2023]
I followed [this](https://tolgee.io/js-sdk/integrations/react/next/app-router) tutorial in order to get Tolgee working with next 14.
I got next working with the translations on both server and client components but when using the component Link from @/navigation I am getting this error: 

<img width="988" alt="image" src="https://github.com/tolgee/tolgee-platform/assets/48689765/d56d9069-326e-42f9-9a01-fcc1e71084a1">

I checked the example app and everything is working completely fine and I don't see the next-intl provider being used... just the TolgeeNextProvider! 

So, I get this error by using the Link component in both client and server components and the useRouter and usePathname in client components.

These are the dependencies:

![image](https://github.com/tolgee/tolgee-platform/assets/48689765/8268735c-fc29-49ac-af87-2a8d65c702b2)

And these the configrations for tolgee and next-intl:

![image](https://github.com/tolgee/tolgee-platform/assets/48689765/ed27d887-ddf3-452e-a155-5420a19aff09)

<img width="701" alt="image" src="https://github.com/tolgee/tolgee-platform/assets/48689765/a0bb0e46-c78c-423d-89ae-dba8f4337880">

The Server, Shared and Client configs are the same as the example except I am using the BackendFetch plugin.

Hope someone know what's going on.

**Comment by stepan662** [comment]
Hey, I think this happens if the route is not matched by the middleware. https://tolgee.io/js-sdk/integrations/react/next/app-router#next-intl-setup

**Comment by marcosriver** [comment]
This is the folder structure: 
![image](https://github.com/tolgee/tolgee-platform/assets/48689765/07a8197f-c3cd-481f-914d-35abbc4b1b0a)

I think it should be okay, do you think it could be the groups (site) (auth). The Provider is in the layout under (site)

**Comment by marcosriver** [comment]
Any follow up with this? Still not able to fix the issue.

**Comment by JanCizmar** [comment]
@stepan662

**Comment by stepan662** [comment]
Hey, I've tested it with the groups, and our example app works fine, so I don't think an issue is in that. I'd need a steps to reproduce, to help you more. What I'd recommend is to compare our [example app](https://github.com/tolgee/next-app-example) with your settings, see if anything is different. Also make sure to upgrade packages to latest version.
