### ISSUE TITLE
Error 500 in Project API keys

### ISSUE THREAD

**Issue by vasyas** [tolgee/tolgee-platform#2027]
![image](https://github.com/tolgee/tolgee-platform/assets/133608/ad9d1037-7e1e-4730-bdab-72bd69363f6f)

**Comment by JanCizmar** [comment]
Hello! Thanks for reporting. We are working on the fix. Sorry for the inconvenience.

**Comment by JanCizmar** [comment]
OK, I've found the cause. The older keys could have empty scopes array, which in Hibernate 5 was retuned as empty set, but Hibernate 6 apparently returns null.

**Comment by JanCizmar** [comment]
Edit! OK, so actually the issue was that there were some older keys (last one from 20th December 2022), which included null scopes. To quick fix this on self hosted instances, run `delete from api_key_scopes_enum where scopes_enum is null;`
