### ISSUE TITLE
Remove Search in Tolgee app Projects

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2031]
**Remove Search in Tolgee app Projects**

The amount of projects is usually not that hight to need to search amog them.
Also, users try to search for some other information in the search input, so it may be confusing.

**Comment by Thibault-Brocheton** [comment]
If we were able to search for keys across all projects, that would be awsome

**Comment by stepan662** [comment]
This is already released, I forgot to close it
![Snímek obrazovky 2024-02-05 v 9 40 24](https://github.com/tolgee/tolgee-platform/assets/8831144/71a79c28-77bc-4ac4-9396-c71e826fb3f0)
