### ISSUE TITLE
Fix onboarding

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2039]
- [ ] add fixed space for in-context
<img width="235" alt="291923478-39c45616-9e46-41bc-aee2-aab446fbc027" src="https://github.com/tolgee/tolgee-platform/assets/75572718/cbb1e1c8-0940-416d-9ea3-e4facefce57b">

- [ ] Add space: Set up
<img width="382" alt="291923800-b1cdf4d5-170c-4dc7-ab81-21f034552f79" src="https://github.com/tolgee/tolgee-platform/assets/75572718/28f87d16-aa9d-4b57-9e8d-4dec7c90f3f2">

- [ ] Export - add round corners
<img width="962" alt="291924084-c50f1a16-b4c7-43ef-93b3-de8398f53ea5" src="https://github.com/tolgee/tolgee-platform/assets/75572718/b1aa96b8-5aeb-49f9-a12f-5d77c1a0ce3d">
￼
￼- [ ] Content delivery - pink frame is too close
<img width="1218" alt="291924443-b12e3969-322c-48f6-b5cb-c267ec39fb39" src="https://github.com/tolgee/tolgee-platform/assets/75572718/5fbdb5a2-b0f5-42b2-95cb-1dece366c792">

**Comment by ZuzanaOdstrcilova** [comment]
**New little improvements**
https://www.figma.com/file/cSobP7nqLgeN4S6f5xyf8y/Tasks-2023?type=design&node-id=302-4277&mode=design

- there are comments in designs 
- in general optimize margins and size (a bit more space)
- colors will be fixed later
