### ISSUE TITLE
Having a full page view of the "Activity" section of the dashboard

### ISSUE THREAD

**Issue by leajuski** [tolgee/tolgee-platform#2054]
My issue
Having to click on "Load More" on repeat to see the last activities on the dashboard
![Capture d’écran de 2023-12-28 15-20-47](https://github.com/tolgee/tolgee-platform/assets/134073349/ddf151a4-f02c-4223-8713-23eddf23d3fc)

Ideas
- Being able to open in full width the Activity part of the dashboard
- Having a pagination that ease the navigation throughout the activities

**Comment by ZuzanaOdstrcilova** [comment]
Will be solved in issue: https://github.com/tolgee/tolgee-platform/issues/2244
