### ISSUE TITLE
Editor design (frontend)

### ISSUE THREAD

**Issue by ZuzanaOdstrcilova** [tolgee/tolgee-platform#2084]
**Design editor (ZO)** - notes:
- plurals (key, view, edit...)
- editation mode (code, preview, missing placeholders)
- different views, panel

**Frontend (ŠG)**

**Comment by ZuzanaOdstrcilova** [comment]
**The final design**
https://www.figma.com/file/cSobP7nqLgeN4S6f5xyf8y/Tasks-2023?type=design&node-id=630%3A24113&mode=design&t=r6axLMzJ0udLoBzk-1

**Comment by stepan662** [comment]
- [ ] update editor everywhere (key creation, translations, single key view)
- [ ] add switch to key edit modal and key creation dialog (checkbox + name of the variable)
- [ ] right side panel with translation tools
- [ ] make table view scrollable + fix the resizable columns
