### ISSUE TITLE
Suggestion: Email notifications

### ISSUE THREAD

**Issue by yrjarv** [tolgee/tolgee-platform#2096]
I apologize if this has been brought up before (I couldn't find any issues about it though); I would love it if you guys created a system that sent an email to those who want it as soon as new keys are added to a project. I am currently translating [ElevenClock](https://github.com/marticliment/elevenclock), and because we are just random people who translate it, we don't have any structured way to receive information about new keys being added. If I could e.g. go to my profile page on Tolgee, and then choose to get e-mail notifications for new keys.

I don't know if you can implement, but as I said I would love to see such a feature at some point in time.

(PS: I know about the slack stuff, but I don't have Slack and ElevenClock doesn't use Slack)

**Comment by JanCizmar** [comment]
I guess this is covered in #1539, right @cyyynthia ?

**Comment by cyyynthia** [comment]
It is covered by the epic #1539, this feature requests targets a smaller task of it. Note that the initial implementation of notifications will not have emails at first (hence why #1986 is named "core"); although the intent is to make them delivered via email as well. 🙂

**Comment by JanCizmar** [comment]
Hello! Since this is a duplicate as discussed in past comments, I am closing this. Please see the referenced issues.
