### ISSUE TITLE
In-context translating not working with local docker setup

### ISSUE THREAD

**Issue by henrikvolmer** [tolgee/tolgee-platform#2107]
Hey guys,

I tried to use in-context translating with my local test app (react + Vite). Everything is working fine, but when I try to translate in context, the server is responding with 400. 

![Bildschirmfoto 2024-01-26 um 10 46 02](https://github.com/tolgee/tolgee-platform/assets/25845699/20c6827a-6af6-439c-937a-3cc45b8b41c1)

`{"code":"invalid_authentication_method","params":null}`

```
My API Keys seems to be correct.

import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import {DevTools, FormatSimple, Tolgee, TolgeeProvider} from "@tolgee/react";

const tolgee = Tolgee()
    .use(DevTools())
    .use(FormatSimple())
    .init({
        language: 'de',

        // for development
        apiUrl: "http://localhost:8085",
        apiKey: "{apiKey}",
    });

tolgee.run();

ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
        <TolgeeProvider
            tolgee={tolgee}
            fallback="Loading..." // loading fallback
        >
            <App/>
        </TolgeeProvider>
    </React.StrictMode>,
)

```

```
import './App.css'
import {T} from "@tolgee/react";

function App() {
  return (
    <>
        <T keyName="foo" />
    </>
  )
}

export default App
```

**Comment by derfl007** [comment]
I can confirm this issue for the [Vue Example App](https://github.com/tolgee/vue-example/tree/main) with a local docker setup.
Nothing has been changed in the project, i only setup a project and added the api key and url in the .env.development.local file

**Comment by JanCizmar** [comment]
Hey! Thanks for reporting. ✅ Can you please share what Tolgee Plarform and Tolgee JS versions do you use?

**Comment by JanCizmar** [comment]
I guess, you're using PAK to authenticate, right?

**Comment by JanCizmar** [comment]
I can confirm I can reproduce it on the latest version. [v3.47.0](https://github.com/tolgee/tolgee-platform/releases/tag/v3.47.0)
