### ISSUE TITLE
Bait and Switch

### ISSUE THREAD

**Issue by arb362** [tolgee/tolgee-platform#2108]
You better notify everyone that you have baited them in with unlimited seats when free and self hosted and now you are limiting them to 10 seats. Honestly quite frustrating. 
https://tolgee.io/pricing/self-hosted#features-table
https://github.com/tolgee/tolgee-platform/pull/2103
![image](https://github.com/tolgee/tolgee-platform/assets/6188411/3e5cfbde-3376-4f2b-9c11-c3a9adbce612)

**Comment by JanCizmar** [comment]
Hello! 

We did notify with this blog post, and via in-app announcement.

https://tolgee.io/blog/new-pricing-2024-01  

We are open to talk with companies and individuals, who are affected by this individually using mentioned channels.

Don't hesitate to get in touch with me personally via
- Tolgee Slack community: https://tolg.ee/slack
- Book a quick chat slot via my Calendly: https://tolg.ee/jan
- Or send me an e-mail via jan@tolgee.io

We can come up with solution for your specific case.

Sorry for your inconvenience 🙏. I believe we have advocated this decision in the blog post.

**Comment by cyyynthia** [comment]
Hi there, sorry for the delayed response.

*Disclaimer: I am not a lawyer. This is not legal advice, nor intends to be. This does not supersede any applicable license terms in any way shape or form.*

Tolgee's core source code is licensed under the permissive Apache 2.0 license, and you are free to modify (and redistribute) the open-source code provided you comply with the terms of the Apache 2.0 license.

However note that Tolgee Enterprise Edition (Tolgee EE) code is proprietary software and you are as such not allowed to modify, or redistribute modified copies of Tolgee EE. This means, you are free to modify the open-source core, but you are not allowed to include any software that is part of Tolgee EE (code under `ee` and `webapp/src/ee`) even unmodified.

Tolgee currently only publishes precompiled jars of what should be considered "Tolgee EE Free", which comes with a 10 seats limit. Tolgee is focusing on Enterprise users at this time as they directly fund the development of the platform, and funds are necessary for working on the project to be sustainable. This leaves users of open-source behind for now, but there is a long-term plan once things are more stable of having a more explicit distinction between "EE Free" and an eventual "Open Source Edition", free of any EE-licensed code (and without any limits on how you can use it, such as seats limit).
