### ISSUE TITLE
Tolgee exports file wrong

### ISSUE THREAD

**Issue by oneVcard** [tolgee/tolgee-platform#2110]
So our file exports perfectly fine except this object in the json:

![image](https://github.com/tolgee/tolgee-platform/assets/144775392/a2da759c-ed80-4710-a9a2-ee3a74aa0dc5)

which is converted to:
![image](https://github.com/tolgee/tolgee-platform/assets/144775392/060bce8e-f024-46d2-b855-28382b8ba229)

Why is this happening?

**Comment by JanCizmar** [comment]
Hello! It's because you have dots in your keys. Tolgee treats the dot as a key nesting separator. I believe, we cannot simply change this now. So as a workaround, you can either omit the dots in the keys or fix this in your integration.

**Comment by oneVcard** [comment]
@JanCizmar We have dots in there? In the first image is our object. After uploading it to tolgee and then exporting it again it becomes converted to string like in the second image

**Comment by JanCizmar** [comment]
Oh! I see. Then

**Comment by JanCizmar** [comment]
Hey! Oh, now I see the reason. Since you've got a key `resend_invitation.context_menu` defined. It cannot be structured. Since the key is already occupied by the string. In that case, Tolgee merges the other keys, so there is no collision with the string.

**Comment by JanCizmar** [comment]
Maybe you've added the key later?

**Comment by oneVcard** [comment]
![image](https://github.com/tolgee/tolgee-platform/assets/144775392/233bda33-d9ee-49ab-8676-f61273e617b6)


You are right, there is a key with that name.

But are keys not deleted automatically when they are not in the uploaded json anymore?

**Comment by oneVcard** [comment]
Ohh okay well then thanks for the help :)
