### ISSUE TITLE
Ability to export json/xliff documents based on translations panel filters

### ISSUE THREAD

**Issue by zeldigas** [tolgee/tolgee-platform#2114]
Right now export functionality is limited and lacks flexibility of "Translations" page.

Would be really great that after configuring Filters and optionally search critiria, I can press export button and export filtered subset of strings that corresponds to this search criteria:

![image](https://github.com/tolgee/tolgee-platform/assets/749858/85cc798e-9eae-4ccf-9b6b-15905dbf274d)

**Comment by JanCizmar** [comment]
Hello! Thanks for the suggestion! I will add it as a part of #1547.
