### ISSUE TITLE
Set unused key as outdated with Tolgee CLI

### ISSUE THREAD

**Issue by EtienneGuilletPackative** [tolgee/tolgee-platform#2118]
Hello,
I would like to know if it was possible while synching the keys with the cli (` tolgee sync './src/**/*.ts?(x)'` ) to set the unused key as "Outdated" with a specific flag instead of removing them with the flag `--remove-unused`?

**Comment by JanCizmar** [comment]
Hey! Thanks for reporting! I have added this feature request to the CLI 2.0 issue in the tolgee-cli repo. We will implement is soon. https://github.com/tolgee/tolgee-cli/issues/74
