### ISSUE TITLE
Review Activity view design

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2128]
I am very unhappy with the behavous and look of the activity view in the project.
- [ ] The rows have hover state, while there are not clickable
- [ ] There is 3 dots on the right, while is suggest it will open dropdown, while it opens detail dialog instead. This should be removed and the row should be clickable
- [ ] For larger operation (like modification of multiple fields on key) it shows `...` under each section. Please get rid of it.
- [ ] When user imports data they cannot see what data is imported
- [ ] There is load more button, it should be probably changed to infinite scroll
- [ ] There should exist a special view with filtering by user
- [ ] For operations without special detail, the clicking should be disabled

**Comment by ZuzanaOdstrcilova** [comment]
Will be solved in issue: https://github.com/tolgee/tolgee-platform/issues/2244
