### ISSUE TITLE
Partial publishes to content delivery

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2130]
We've got this feature request:

We are setting up a relatively complex full stack project, Mobile, Web (Microfrontends), BFF Services, Backend Microservices  where translations are used in every layer.
Setup would be:
- Project per Vertical Team
- Namespace per Component (i.e. a Microservice) that needs it's own translations

We want to be able to publish entire Project to S3 and also just Publish and update specific Namespaces (or other publishing configuration).
Currently when creating a ProjectContentDelivery a random "Slug" is generated which is then the base folder in S3 this prevents preparing Full/Partial ProjectContentDelivery configurations.
Suggestion:
- Allow overriding the default ?Slug? property in the Edit/Create Dialog

----

The simplest solution would be only adding the option to provide own slug for custom storages and letting the content delivery configuration to overlap each other. However, this would solve the issue only if we guarantee, that we don't delete all the data from the content delivery destination before. So better option will be to let user choose the behaviour explicitly. 

- [x] Add the configuration option to provide own slug for custom content storages
- [x] Enable users to configure whether they want to purge data first on the content delivery config level

**Comment by rnevet-reply** [comment]
Hi @JanCizmar,
We were just discussing today the possibility of using Partial Exports, is there a plan for this issue?

**Comment by JanCizmar** [comment]
Sorry, I am a bit behind the schedule, hopefully I will be able to get into this tomorrow.
