### ISSUE TITLE
Import Settings UI Proposal & Tolgee ICU support on project level

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2131]
## Import settings

After user uploads the files they may configure
 - [x] Convert placeholders to Tolgee ICU Placeholders - If they want to convert for example %s to {0}
   - This will be disabled if they have disabled Tolgee ICU placeholders on project level
 - [x] Override key descriptions - If they want to override the key descriptions
   - Some of the formats might contain the key descriptions and we don't know what's the source of true. By default we will consider Tolgee is the source of truth, so by default this will be disabled
   
## Project settings
- [x] Tolgee ICU Message format support - somewhere in the project settings should be an option to specify whether Tolgee ICU message format is supported for proejct. This is true by default.
  - Some users want to use Tolgee only for translation of iOS app for example and they want to keep everything in the native format, so we will just disable Tolgee ICU placeholders and ICU syntax in general.
  
## Supported formats

It would be cool to have there a tooltips with descriptions and might link to docs.

- [x] JSON [Tolgee] (Tolgee Logo)
- [x] XLIFF [With ICU message format]
- [x] PO PHP (php logo)
- [x] PO C / C++ (C logo)
- [x] PO PYTHON (Python logo) 
- [x] APPLE Strings (Apple logo)
- [x] APPLE Stringsdict (Apple logo)
- [x] Apple XLIFF (Apple logo)
- [x] Android resource XML (Android logo)
- [x] Flutter ARB (Flutter logo)

**Comment by ZuzanaOdstrcilova** [comment]
Import - icons, settings
https://www.figma.com/file/cSobP7nqLgeN4S6f5xyf8y/Tasks-2024?type=design&node-id=1183%3A30131&mode=design&t=vZ8XxaCa0h8xcfI2-1
