### ISSUE TITLE
T component doesn't recognize self closing tag

### ISSUE THREAD

**Issue by EtienneGuilletPackative** [tolgee/tolgee-platform#2140]
The self closing tag are not recognized by the T component

Example:

`<T
keyName="some-key-name" 
defaultValue="This is my first line.<br />This is my second line."
params={{ br: () => <br /> }}
/>`

It's not a big deal since we can use it as a non self-closing tag like `<br></br>` but it would be cool if it worked! 😄

**Comment by stepan662** [comment]
This is a duplicate issue https://github.com/tolgee/tolgee-js/issues/3101
