### ISSUE TITLE
Visual Editor -> Last fixes

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2151]
- [x] Plural translation in raw mode is not unescaped in view
 - [x] Cannot edit key in safari -> Clicking on key doesn't work
 - [x] Safari -> Import -> Formats grid looks differently then in chrome
 - [ ] The colors in the "code mode" should match the ones used in visualization
     -> Skip now
 - [x] The "hide placeholders" tooltip should be renamed to "Edit as code"
  -> Show/hide code

**Comment by ZuzanaOdstrcilova** [comment]
- [ ] The Tolgee translator is not accurate in plurals (weirdly translates delete as add - e.g. screenshot, and badly plural forms)
- [ ] add key - I would add some (i) with form of placeholder #, or something like missing placeholders
- [ ] add key placeholders - how to add key in plural in form of screenshot bellow (there are no tasks)
- [ ] translation in czech 0.5 item (i) some info that it is not mandatory in some cases

Design
- [ ] light gray - hover TM, MT and comments should be same - the light one
