### ISSUE TITLE
No line break after import Apple Strings

### ISSUE THREAD

**Issue by awatke** [tolgee/tolgee-platform#2166]
When I try to import strings with line breaks like `\n` I see strings in tolgee without `\`.
For exmaple `line 1\nline 2` ->  `line 1nline2`. 

And if I add `\n` in tolgee I get `\\n` after the export. 

Is this a known issue?

**Comment by JanCizmar** [comment]
Hey! Thanks for reporting. It's not known issue. It's a bug. I am looking into it immediately.

**Comment by JanCizmar** [comment]
The fix is released now.
