### ISSUE TITLE
Pluralization in activity

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2172]
The plural forms are not rendered correctly in activity
![image](https://github.com/tolgee/tolgee-platform/assets/18496315/7ebf7fa6-0367-4153-b42f-3d0b6ed92df6)

**Comment by stepan662** [comment]
Hmm, this feels like a quite difficult task

**Comment by JanCizmar** [comment]
Isn't the same component used everywhere able to do the job?

**Comment by stepan662** [comment]
It's not so simple - e.g. how to compare non-plural string with plural with diff.

**Comment by JanCizmar** [comment]
In that case, we can just consider the non-plural string a plural string where all the forms are the same non-plural string. Which semantically is the same, isn't it?

**Comment by stepan662** [comment]
Will be solved as part of new activity https://github.com/tolgee/tolgee-platform/issues/2244
