### ISSUE TITLE
Option to remove keys missing on an import

### ISSUE THREAD

**Issue by cryogen** [tolgee/tolgee-platform#2201]
My workflow looks something like:

Scan code for translatable strings
Build master en-US json file for those strings
Import that json file into Tolgee
Export untranslated strings to get translated
Manually remove keys that are no longer needed

It would be nice to be able to have Tolgee automatically do that last step by providing an option to remove keys that are not included in the import file.

**Comment by JanCizmar** [comment]
This will be a feature of [Tolgee CLI v2](https://github.com/tolgee/tolgee-cli/issues/74)

**Comment by JanCizmar** [comment]
Or do you prefer to use the UI import for some reason?

**Comment by cryogen** [comment]
Hadn't thought of the cli tool to be honest!

Either works for me
