### ISSUE TITLE
Improve API to update machine translation settings

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-platform#2202]
For us AWS is the preferred MT provider, but we need to use Google in some cases because they have better language coverage. So my goal is to set all languages to AWS except in cases where AWS doesn't support the language, then set to Google.

After much trial and error, I finally figured out the process that does what I want and it involves the following steps:
- For each language, attempt to set the primary and enabled services to AWS
- If that throws an exception, attempt to set the primary and enabled services to Google
- If that throws an exception, set the primary to `null` and the enabled services to the empty set
- Track the successful API call and aggregate into one final overall API call using that sets it again for all languages

Setting one language at a time is still considered a "batch" and reverts the settings of the previous language calls, so you must collect the final results into one last call at the end.

Can we:
- Expose which languages are supported by which service?
- Set the primary, secondary, etc. in one call and Tolgee can pick which one "sticks" based on which service has which language supported? Instead of relying on multiple try/catch API calls?
- Simplify the formality settings so we don't have the redundant enums? Example call right now that seems clunkier than it needs to be:

```
mtProps
	.primaryService(PrimaryServiceEnum.AWS)
	.primaryServiceInfo(new MtServiceInfo().formality(FormalityEnum.FORMAL).serviceType(ServiceTypeEnum.AWS))
	.enabledServices(Set.of(EnabledServicesEnum.AWS))
	.addEnabledServicesInfoItem(new MtServiceInfo().formality(FormalityEnum.FORMAL).serviceType(ServiceTypeEnum.AWS));
```

**Comment by JanCizmar** [comment]
Thanks for reporting! I am adding this to my TODO list.

**Comment by JanCizmar** [comment]
Hey!

I am looking into this.

> Expose which languages are supported by which service?

This will be added.

> Set the primary, secondary, etc. in one call and Tolgee can pick which one "sticks" based on which service has which language supported? Instead of relying on multiple try/catch API calls?

This doesn't feel like a right path since it might be confusing for the users using the API. When you have the lists exposed, you can check it on your side, right?

> Simplify the formality settings so we don't have the redundant enums? Example call right now that seems clunkier than it needs to be:

The `primaryService` and `enabledServices` are deprecated fields and are kept only for backward compatibility. Aren't they marked deprecated in your generated code?

**Comment by jdimeo** [comment]
- Great thank you!
- I think that it is a very common use case to have two competing priorities: these are the services I want to use in this order, yet I want to maximize language coverage. If you expose the info, we can definitely handle that in client code yes. But I think it will be common for users to say "use AWS, then Google, then DeepL, because that is my order, but keep going until you find a service that supports my language". But if you don't want to add that to the API, I understand- having the list of supported languages is all that is required.
- Yes, I see that now- it was deprecated recently. So what is the preferred/new way of setting this?

**Comment by JanCizmar** [comment]
Hey!

> I think that it is a very common use case to have two competing priorities: these are the services I want to use in this order, yet I want to maximize language coverage. If you expose the info, we can definitely handle that in client code yes. But I think it will be common for users to say "use AWS, then Google, then DeepL, because that is my order, but keep going until you find a service that supports my language". But if you don't want to add that to the API, I understand- having the list of supported languages is all that is required.

It's a valid use case, but since we wouldn't store the info about the priorities and only store the provider which works, IMHO it is not conceptional.

> So what is the preferred/new way of setting this?

This should do:
```
mtProps
	.primaryServiceInfo(new MtServiceInfo().formality(FormalityEnum.FORMAL).serviceType(ServiceTypeEnum.AWS))
	.addEnabledServicesInfoItem(new MtServiceInfo().formality(FormalityEnum.FORMAL).serviceType(ServiceTypeEnum.AWS));
```
We just have added the formality, so now there is more then the provider to the settings.
