### ISSUE TITLE
ID is not displayed in the project dashboard

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2207]
In the SDKs, Platform and CLI and docs we refer to a project ID, but we don't display it in the project dashboard. I believe it was deleted form the UI by mistake some time ago and never added back.

**Comment by stepan662** [comment]
It was in the place where the billing is displayed and also the batch operations.

I think we should put it somewhere else, this place is already overloaded.

![Snímek obrazovky 2024-03-21 v 11 06 23](https://github.com/tolgee/tolgee-platform/assets/8831144/1b249592-9b5a-4399-bc21-7808fb3d569d)

**Comment by ZuzanaOdstrcilova** [comment]
Project ID will be:

- on the main dashboard under project name with other info
- on the project dashboard next to name of project

https://www.figma.com/file/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?type=design&node-id=1487%3A52659&mode=design&t=5q8WTfDe1GQD04xJ-1
