### ISSUE TITLE
iOS characters escaping issues

### ISSUE THREAD

**Issue by dubraf** [tolgee/tolgee-platform#2222]
Hi, I noticed some issues while testing iOS export functionality:
- \n is double escaped,
- unicode literals like \u00A0 are double escaped too. 
Example:
Key with non-breaking\u00A0space and\nnew line.
Result:
Key with non-breaking\\\u00A0space and\\\nnew line.

Moreover in the iOS Localizable.strings file it needs to be \U00A0 while in Android strings.xml \u00A0. It would be nice to have such conversion while exporting translations for given platform ;)

**Comment by JanCizmar** [comment]
Hello, 
you can use newlines, instead of `\n` in your string. Tolgee currently doesn't treat `\n` as a newline, but just character sequence. 

It's true that `\u....` are handled specially when exporting to android (so they are not double escaped), so we can indeed handle them specially for iOS.

**Comment by dubraf** [comment]
Don'y you think that using \n as a new line would be more readable? 
I'm thinking also about a case when I need a few new lines in a row.
With \n as a new line Localizable.strings file would look like:
![image](https://github.com/tolgee/tolgee-platform/assets/23438098/9d0fe146-1c3d-4c75-bdad-02c587039ec1)
instead of:
![image](https://github.com/tolgee/tolgee-platform/assets/23438098/51a17c7e-f1d9-46e7-9453-9517c2dda605)

**Comment by JanCizmar** [comment]
Well, thats how the string reads, right? Truth is, that we can add option to escape new lines when exporting. However, adding ability to escape the newlines in the Tolgee platform would actually make it unreadable for other non-developer users  (e.g., translators) who would access the platform and might be potentially confused by such characters.

**Comment by dubraf** [comment]
Maybe a good option would be to do this like Weblate did. I'm talking about the buttons above the text field that allow you to insert the appropriate characters. I think, It would be more readable for non-developer users ;) 
![image](https://github.com/tolgee/tolgee-platform/assets/23438098/eda1c95b-4e90-47bd-be0a-7ad7313fcba6)

**Comment by JanCizmar** [comment]
The UI of Tolgee is designed so it has clean look and it doesn't have unnecessary control elements. Our strategy is keep it as clean as possible. That's one of the reasons why users coming from Weblate to Tolgee.

**Comment by dubraf** [comment]
I fully agree and I also prefer Toglee interface😉 However it gets problematic in above examples. 

I noticed also that it's possible to use <nbsp> html tag, so maybe it would be possible to convert it to appropriate unicode while exporting file to given platform?

**Comment by JanCizmar** [comment]
Where does `<nbsp>` tag comes from?

**Comment by dubraf** [comment]
I noticed that Tolgee specifically marks it, isn't it? 
![image](https://github.com/tolgee/tolgee-platform/assets/23438098/aab4056d-19c5-4442-a973-a71f428452e7)
