### ISSUE TITLE
401 error code 

### ISSUE THREAD

**Issue by bohyun82** [tolgee/tolgee-platform#2249]
I used the Tolgee Tools extension. But suddenly the Tolgee Tools extension does not work on the website I am using and an error code 401 appears. Even if I delete everything and register again, it's still the same. What is the solution? My coworkers are normal and it's only a problem for my account.

![12](https://github.com/tolgee/tolgee-platform/assets/167145653/1be067c6-5a12-4460-867d-a31190e73cba)

**Comment by bohyun82** [comment]
How do I update Tolgee SDKs? The version of Tolgee tool I am currently using is 1.7.0. Even after uninstalling and reinstalling, the same error code appears.
A 401 error will appear and the pop-up window at the top will display invalid.

**Comment by stepan662** [comment]
Hey, I think you are talking about Tolgee chrome plugin, but we are talking about Tolgee SDK. However, if it works fine for your colleagues, it's probably not the issue. One thing that comes to my mind, is that it can be influenced by other extensinsions in your browser, which could be blocking requests. So you can try to deactivate other chrome extensions or try in private mode.

If the issue persists, please try to look into chrome dev tools and check the network (here is tutorial: https://developer.chrome.com/docs/devtools/network), and find the request that is failing and what error it is producing - that way I can give you better support.
