### ISSUE TITLE
Accounts cannot be deleted

### ISSUE THREAD

**Issue by teawithfruit** [tolgee/tolgee-platform#2258]
If there are more than 10 accounts in a self-hosted environment, it is not possible to delete or disable unnecessary accounts in the server administration. The error message `free_self_hosted_seat_limit_exceeded` is also displayed when deleting.

**Comment by JanCizmar** [comment]
Hello, thanks for reporting. This is a duplicate of this #2219, we will address it soon. Sorry for inconvenience.

**Comment by JanCizmar** [comment]
Fixed in #2267
