### ISSUE TITLE
Feature: machine translation during import

### ISSUE THREAD

**Issue by webard** [tolgee/tolgee-platform#2265]
Hello,

next useful feature will be setting machine translation for chosen languages during importing some files.

For example, I upload imports for:
- en-US
- fr-FR

but translations for de-DE will be available later, but we want them to make release. Will be great to choose to translate de-DE by machine translation provider, and later manual translations will be imported.

Thank you

**Comment by JanCizmar** [comment]
Hello, 

thanks for the query.

isn't current auto translation satisfying your need? https://tolgee.io/platform/projects_and_organizations/machine-translation-settings#automatic-translation

As stated in docs:
```
You can also enable automatic translation when there are new keys imported by the CLI, Import UI or any REST API endpoint importing multiple keys.
```

**Comment by webard** [comment]
Yes, it works perfectly. Sorry, I didn't notice this functionality. I'm closing issue.

Thank you!

**Comment by webard** [comment]
This option is good, but a bit hard to find. It also causes the keys be machine translated on every import or never. It would be ideal to have this selection when importing.
