### ISSUE TITLE
Translation view > filter improvements

### ISSUE THREAD

**Issue by ZuzanaOdstrcilova** [tolgee/tolgee-platform#2274]
- [x] Research what is needed - issues, discussions, UX research community
- [x] Check competitors
- [x] Check current solution
- [x] New ideas / design

**Comment by ZuzanaOdstrcilova** [comment]
https://github.com/tolgee/tolgee-platform/issues/1808

**Comment by andr-04** [comment]
Filter by opened / resolved comments is also needed. It allows translators to see what of their translations should be retranslated again.

**Comment by ZuzanaOdstrcilova** [comment]
note from our customer: ![Image](https://github.com/user-attachments/assets/e4f6463b-9d89-438e-b11d-ec3e7079a96a)

**Comment by ZuzanaOdstrcilova** [comment]
Design for development
https://www.figma.com/design/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?node-id=3244-7707&t=WGI8P2fmJbOzA6WE-1

### **We decided to do filters in two complex tasks.**

### **The first version**
- We decided to move some items to the second level of the menu.
- We cleaned states and translations - the previous version was confusing. Now you will filter just in the visible items

**Tags** 
We will add:
- an exclude option 
- an option without a tag

![Image](https://github.com/user-attachments/assets/6a352fe4-741b-4460-bb36-a163e7e5005e)


**Namespaces**
We will add:
- an exclude option 
- an option without a namespace

**Translation**
- We will join states and translation in one place
- Languages can the user change in the dropdown menu
- We will add a checkbox for ignoring the base language

![Image](https://github.com/user-attachments/assets/5977e9eb-7faf-456c-bd2b-baecfcaa7cc2)

**Autotranslation**
- by Machine translation
- by Translation memory

**Comments**
- unresolved comments
- resolved comments

**Screenshots**
- will stay the same; just go to the second level

### **The second version**
- We are planning to create an advanced filter
- There will be an option to save your filter

**Comment by ZuzanaOdstrcilova** [comment]
The first version 
https://github.com/tolgee/tolgee-platform/issues/2777
