### ISSUE TITLE
Incorrect request on docs

### ISSUE THREAD

**Issue by jenyaftw** [tolgee/tolgee-platform#2275]
The request for "Get for key" in the documentation is actually setting the translations by key.

![image](https://github.com/tolgee/tolgee-platform/assets/24240873/5f26a361-1062-46bf-9c21-efcb34e496da)

**Comment by JanCizmar** [comment]
Oh no! I am fixing it immediately.

**Comment by jenyaftw** [comment]
@JanCizmar How would I get translations by key then?

**Comment by JanCizmar** [comment]
Hey! The [Get Translations](https://tolgee.io/api/get-translations) endpoint has `filterKeyName` and `filterNamespace `, params you can use to get translations for single key.
