### ISSUE TITLE
Integration with Vue 2

### ISSUE THREAD

**Issue by adam314315** [tolgee/tolgee-platform#2282]
Hello,

How to integrate Tolgee with Vue 2 ?

The current Vue installation guide is for Vue 3
https://tolgee.io/js-sdk/4.x.x/using_with_vue/installation

But I saw this integration guide via i18next with Vue 2
https://tolgee.io/js-sdk/4.x.x/using_with_i18next/vue_integration

Could you please advise for the best step to use it with Vue 2 ?
Thanks.

**Comment by stepan662** [comment]
Hey, we don't support vue2 natively, but it's possible to use it with i18next plugin.
You are referring to links to an old docs, so here is the docs for latest version:

I18next:
https://tolgee.io/js-sdk/integrations/i18next/vue-integration

**Comment by adam314315** [comment]
Yes thanks. I followed this integration guide and succeeded.

**Comment by stepan662** [comment]
Cool, I'll close this issue as the workaround is available
