### ISSUE TITLE
Self hosting missing machine translatiions and users features

### ISSUE THREAD

**Issue by davidyoung77** [tolgee/tolgee-platform#2319]
https://tolgee.io/platform/self_hosting/running_with_docker

I'm not sure that this is a bug or missing/hard to find documentation.

When I self host as described in the documentation above, or clone this repo and serve locally, both the users, and machine translations features are missing.

- Users feature- I am not prompted to sign in with a user account and the users feature is missing from the navigation side bar.
- Machine translations- On the translations page there are no machine translations enabled, none show up and I am unable to configure.

Is there configuration that I need to set in order for these features to be enabled? Is this documented somewhere?

**Comment by cyyynthia** [comment]
You will need to configure [authentication](https://tolgee.io/platform/self_hosting/configuration#authentication) and your [machine translation providers](https://tolgee.io/platform/self_hosting/configuration#machine-translation).

Tolgee Translator (Tolgee's own MT Engine) requires a team subscription or higher for self-hosted instances.
