### ISSUE TITLE
Authentication settings are ignored / No log-in required

### ISSUE THREAD

**Issue by Larsschoen** [tolgee/tolgee-platform#2321]
I'm running Tolgee v3.61.3 in Docker and I'm trying to enable authentication. I followed the docs and my config.yaml looks like that:

```yaml
tolgee:
   authentication:
      enabled: true
```

However, upon visiting the web-UI I'm always getting logged in as the admin user. Clearing cookies/local storage or opening the web-ui in chrome's incognito-tab yields no results.

I can confirm that the `config.yaml` is actually getting used by the the application, changing the server.port works!

Is there something I'm missing here?

**Comment by Larsschoen** [comment]
Well...seems like I found my mistake. I was missing the `spring.config.additional-location` as environment in the docker-compose file. 
However, I switched to using .env for configuration. Now I'm getting the log-in page, just what I wanted!

Case closed.

**Comment by JanCizmar** [comment]
Oh! Cool! I am glad you've fixed it. Sorry for not responding in time.
