### ISSUE TITLE
Add new filters to the backend and UI

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2338]
We need to provide few more simple filters to enhance user experience
- [ ] Enable filtering by `machine translated` flag
  - This is useful when user runs an batch and need to know which translations were affected or not 
- [ ] Enable filtering by `tag not`
  - When tagged keys by the cool new [CLI 2.0](https://github.com/tolgee/tolgee-cli/issues/74) features, it would be great which keys were **not tagged**. In our environment we started tagging keys included in production build with `production` tag. It would be great to see keys, which are not in production to remove possibly them.

**Comment by ZuzanaOdstrcilova** [comment]
The design is ready. Now, it is waiting for development. We added it to the first group of filter improvements.

https://github.com/orgs/tolgee/projects/3/views/7?pane=issue&itemId=90724276&issue=tolgee%7Ctolgee-platform%7C2777

**Comment by ZuzanaOdstrcilova** [comment]
![Image](https://github.com/user-attachments/assets/7efd05e1-b952-419d-adaa-16d81a732beb)
![Image](https://github.com/user-attachments/assets/b8093852-80b6-4b35-acf9-28ef7a572f1d)
