### ISSUE TITLE
Slack integration Frontend -> Handle disabled slack_integration feature

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2346]
When `SLACK_INTEGRATION` feature is disabled, the user can hit the button, but it throws error message.

This should be handled with some  message inviting to pricing.

 
![image](https://github.com/tolgee/tolgee-platform/assets/18496315/706eaa2a-982c-46fe-a9c0-dea6e1b493f9)

(sorry for Czech screenshot)

**Comment by stepan662** [comment]
Done
