### ISSUE TITLE
Ability to count words and characters on currently filtered view

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#2348]
When estimating price of a translation job, agencies require to know number of words.

Our user suggests, we should show number of words in the general translation view, so he can just filter what needs to be translated and then see how many words that is.

I'm thinking it could be something like batch operation (if it's a performance intensive).

**Comment by jdimeo** [comment]
This would be great! If you are calculating "live" because of this feature, it would be great to have a checkbox that "excludes words that don't have at least one letter" or "exclude words that are only symbols/punctuation"
(unless those kinds of options are already built in?)

**Comment by stepan662** [comment]
It's is part of new `Tasks` feature, so I'm closing this
