### ISSUE TITLE
Tasks (UI)

### ISSUE THREAD

**Issue by ZuzanaOdstrcilova** [tolgee/tolgee-platform#2360]
**Design**
Figma file: https://www.figma.com/design/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?node-id=1718-54457

- [x] the process and specification
- [x] bulk creation of a task
- [x] new task dialog
- [x] my tasks 
- [x] my tasks menu
- [x] project task
- [x] create task from project
- [x] translation in task
- [x] task filtration
- [x] task editing
- [x] spec. of report

**Comment by JanCizmar** [comment]
Hey @Zuzka, @stepan662,
on the today's call, we got several interesting questions and feedback from a customer.  

- Trello-like view is nice to have  
- "Delete from task" in batch ops sounds dangerous  
- Restrict that translator/reviewer can only edit keys specified in a task

**Comment by JanCizmar** [comment]
Closing this, since Stepan is already implementing this.
