### ISSUE TITLE
PO_ICU format import unnecessarily escapes ICU formatted values

### ISSUE THREAD

**Issue by sinukaarel** [tolgee/tolgee-platform#2375]
**Describe the bug**
Importing `.po` file translations in `PO_ICU` format escapes `{` characters with single quotes. This behavior makes the variable considered as text and not as a variable.

**To Reproduce**
1. Go to https://github.com/tolgee/tolgee-platform/blob/main/backend/data/src/test/resources/import/po/example_params.po
2. Click on `download raw file`.
3. Import the downloaded file through UI to the Tolgee project.
4. Imported `icuParam` is not shown as a parameter in UI as the brackets are escaped.

![image](https://github.com/tolgee/tolgee-platform/assets/22918359/daeb2287-5748-4efb-acc0-67351eb14f5c)

**Expected behavior**
ICU parameters are considered as parameters and are not escaped.
![image](https://github.com/tolgee/tolgee-platform/assets/22918359/5f7d44d1-3dac-497d-a12b-61a6ca9691f7)

**Versions and environment**
- Environment: Latest in https://app.tolgee.io

**Comment by JanCizmar** [comment]
Hey! This behaviour is actualy expected. The [example_params.po](https://github.com/tolgee/tolgee-platform/blob/main/backend/data/src/test/resources/import/po/example_params.po) file contains also sprintf params, and this message format was detected under the hood.

Are you encountering such issue with another file? 

As a workaround you can use Tolgee CLI, or our single step import REST API endpoint. It enables you to force specific message format. 

Docs for `format` option of the CLI: https://tolgee.io/tolgee-cli/project-configuration#format
Single step import endpoint docs: https://tolgee.io/api/do-import

**Comment by sinukaarel** [comment]
Yes, the `sprintf` variables seem to be picked up and converted just fine. It might be a conflict of two formats being used simultaneously.

Another example is a `.po` file consisting of only one message in ICU format.
```
msgid ""
msgstr ""
"Project-Id-Version: Tolgee 1.0.1\n"
"Report-Msgid-Bugs-To: info@tolgee.io \n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "welcome"
msgstr "Willkommen, {name}"
```

Using the single-step endpoint with the `PO_ICU` format still gives the same result. The resulting translations ICU token is escaped.
![image](https://github.com/tolgee/tolgee-platform/assets/22918359/7e163263-a7ad-4dcf-8c96-6325f02fb0b0)

[Exporting](https://tolgee.io/api/export) the same translation with `"format":"PO", "messageFormat:"ICU"` however, results as correctly formatted message, same as the input.

```
msgid ""
msgstr ""
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals = 2; plural = (n !== 1)\n"
"X-Generator: Tolgee\n"

msgid "welcome"
msgstr "Willkommen, {name}"
```

When I correct the translation value in UI to reflect that the `{name}` is a placeholder by removing `'` around brackets. Then, the UI reflects that the value is a placeholder and the exported result is the same as before.

![image](https://github.com/tolgee/tolgee-platform/assets/22918359/dba60bdf-d642-4609-bc29-382dde47958f)

So I still think that the import adds unnecessary escape characters around ICU formatted value brackets, resulting in UI not displaying the value properly. The import should result in the final image, not the first one.

**Comment by JanCizmar** [comment]
Hey, you're right the new example, you've provided seems like a bug. I have reproduced it 👍

Please let me look into that :)
