### ISSUE TITLE
PO file import doesn't parse double-quotes

### ISSUE THREAD

**Issue by sinukaarel** [tolgee/tolgee-platform#2384]
**Describe the bug**
When importing a `.po` file containing quotes, those quotes are not correctly extracted - they are missing. This happens for both translation keys and messages.

**To Reproduce**
1. Example `.po` file.

```
msgid ""
msgstr ""
"Project-Id-Version: Tolgee 1.0.1\n"
"Report-Msgid-Bugs-To: info@tolgee.io \n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "This is a \"quote\""
msgstr "Dies ist ein \"zitat\""
```

2. Import the example file through UI or single-step import.
3. Quotes are missing in the key and also in the message.
![image](https://github.com/tolgee/tolgee-platform/assets/22918359/9b94188a-26aa-4127-b97b-f7e662e4c328)

**Expected behavior**
Quotes are preserved through the import process.

![image](https://github.com/tolgee/tolgee-platform/assets/22918359/f0eb64a0-cc0b-4892-a956-f96c3a5d80f0)

**Versions and environment**
- Environment: Latest in https://app.tolgee.io/, etc.

**Additional context**

**Comment by JanCizmar** [comment]
Thanks for reporting!
