### ISSUE TITLE
export description with strings as comment for Android

### ISSUE THREAD

**Issue by Nailik** [tolgee/tolgee-platform#2391]
**Is your feature request related to a problem? Please describe.**
When exporting strings.xml for android the description in tolgee is missing.

**Describe the solution you'd like**
before every string that contains a not empty description there should be a comment 
`<!-- this is a comment in xml -->`

**Comment by Nailik** [comment]
no it's not completed! @JanCizmar the bot should really stop just closing issues.

**Comment by stepan662** [comment]
This shouldn't be complicated, right @JanCizmar?
