### ISSUE TITLE
How to use Tolgee in a Spring Boot project?

### ISSUE THREAD

**Issue by firmianaQ** [tolgee/tolgee-platform#2398]
你好

我目前正在做一个Spring Boot项目，并希望集成Tolgee进行本地化。您能否提供有关如何在 Spring Boot 应用程序中设置和使用 Tolgee 的指导或分步教程？

谢谢！

**Comment by JanCizmar** [comment]
Hello!

Thanks for the query! We currently don't have such tutorial, but you're right we should provide it. 

You can export `.properties` or `.yaml` file from Tolgee and then use it in your project.
