### ISSUE TITLE
Parameter interpolation: In Tolgee Version 5 its variable name is not printing in Vuejs file

### ISSUE THREAD

**Issue by nasirzid** [tolgee/tolgee-platform#2407]
Its printing same string instead to replace {service} with "Google". please check following script

``````
<template>
  <div>
    {{ $t('service.not_configured_service', { service: serviceName }) }}
  </div>
</template>

<script>
export default {
  data() {
    return {
      serviceName: 'Google' // Replace with dynamic value as per your application logic
    };
  }
};
</script>```

**Comment by nasirzid** [comment]
Here is Output:
`You have not configured {service} service.`

Here is Tolgee value:
![image](https://github.com/tolgee/tolgee-platform/assets/11215808/77c07e06-13ed-4dd2-8d11-03b25d432716)

**Comment by stepan662** [comment]
Hello, I'm not really able to replicate from provided description. Have you looked at the migration guide from v4?
https://tolgee.io/js-sdk/migration_to_v5/core

**Comment by nasirzid** [comment]
@stepan662 I'm currently using Tolgee version 5, and I'm facing this issue within v5.

**Comment by stepan662** [comment]
Ok, but I would need to see more details to replicate your issue. I don't know how you initialize Tolgee or what exact version are you using and without that, I can't help you.

**Comment by JanCizmar** [comment]
Hey! Any news here?
