### ISSUE TITLE
Activity label breaks, when tag added to 0 keys

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#2418]
<img width="698" alt="Snímek obrazovky 2024-07-23 v 17 35 45" src="https://github.com/user-attachments/assets/70c8aa0e-4498-4f0b-b8ab-65fa2dbc9a6f">

**Comment by JanCizmar** [comment]
Is this frontend or backend issue?

**Comment by stepan662** [comment]
I didn't investigate much further, I think there is some issue with the statistics returned from the backend, there is some value `KeyCount`, which is normally a number and in this case is missing. For other batch operations it seems to be there, but not for this one. Can be fixed on the FE, but would be nice if it would behave consistently.

**Comment by huglx** [comment]
I'll look into that 🙂

**Comment by huglx** [comment]
@stepan662 can you please help me with reproducing this bug. Thanks:)

**Comment by stepan662** [comment]
It happens when the batch operation adds 0 tags (can happen if the keys are already tagged with the same tag)

https://github.com/user-attachments/assets/8dcacc57-78c6-43e5-8a0f-f67952d6b028

**Comment by huglx** [comment]
@JanCizmar, @stepan662 Is it okay if I just throw an exception when adding a tag to 0 keys? Or is this a useful feature (idk why)?

**Comment by stepan662** [comment]
No, we shouldn't throw any errors, it's a valid case that can happen. We might skip activity creation all together (as basically nothing changed). But maybe we should tell the user how many keys were actually updated - however if this is complicated, I think it's enough to just not to create activity.
