### ISSUE TITLE
Unexpected machine translations when changing a translation

### ISSUE THREAD

**Issue by sebb3** [tolgee/tolgee-platform#2434]
**Describe the bug**
I have configured a few languages for customer-specific translations. These languages are excluded from machine translations and that works well when adding new translation keys to the project. Machine translations are generated for standard languages,and are omitted where expected. 

Just noticed that if I change the english (primary language) translation for any translation key, machine translations are triggered, and in this case they also replace the languages that are supposed to be excluded. I havent found any setting to control this behaviour, and it seems to me to be a bug, I cant really imagine a scenario where this would be the expected behaviour.

Any advice on how to overcome this?

**Comment by stepan662** [comment]
Hey, automatic translation is controlled by this checkbox
![Snímek obrazovky 2024-08-20 v 14 07 12](https://github.com/user-attachments/assets/84b56eac-cee3-4299-adde-2dd8d89c1442)
Do you have it disabled?

**Comment by JanCizmar** [comment]
Hey! I am closing this, since there are no updates.

**Comment by sebb3** [comment]
Sorry! @stepan662  I have that box ticked in, and it works as expected when adding a new key.
However, when updating the primary translation, this checkbox is not being respected.

**Comment by JanCizmar** [comment]
Hey! If you update primary translation, it only auto-translates if there is the auto-translation flag (the label showing the logo of any machine translation provider). Tolgee doesn't overwrite manually provided transaltions.
