### ISSUE TITLE
Review project hard delete

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2441]
Review, how project is hard deleted. It should probably trigger hard deletes on each language instead of deleting it via SQL or translation entities deleting. It might generate super lot of slow SQLs.

**Comment by jdimeo** [comment]
On a related note, I was unable to delete a project whose name had only 3 characters in the UI (the confirm dialog box's confirm button was still grayed out after typing the project name). Maybe there is a UI feature that is expecting text longer than 3 characters?

**Comment by JanCizmar** [comment]
@jdimeo Thanks for reporting. Can you please create separate issue for this?

**Comment by JanCizmar** [comment]
Inclued in #2518
