### ISSUE TITLE
Impossible to connect to the built in Postgres DB when self hosting.

### ISSUE THREAD

**Issue by HoplaGeiss** [tolgee/tolgee-platform#2450]
Impossible to connect to the built in Postgres DB when self hosting.

jdbc:postgresql://localhost:25432/postgres
username: postgres
password: postgres

**Comment by JanCizmar** [comment]
Hello! You're very probably doing something wrong. If you believe it's a bug, please attach exact steps to reproduce, follow our issue templates and append all configuration files. (docker compose config file and tolgee app config)
