### ISSUE TITLE
Add tag filter to the translation returning endpoint for JS SKDs

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2453]
According to this [discussion](https://github.com/tolgee/tolgee-platform/discussions/2436), when client uses single project for multiple platforms, they need a way how to fetch only keys for specific platform tag. e.g. `web`, `mobile`. To achieve the JS SDK enhancement, we need to enable tag filtering on the endpoint.

- [ ] Enable tag filtering on this endpoint https://tolgee.io/api/get-all-translations

**Comment by Ajit594** [comment]
hey sir, i would love to work on it. Shall I proceed?

**Comment by Ajit594** [comment]
# Problem is
When someone uses a single Tolgee project for different platforms (like web and mobile), they want to get translations only for one platform at a time. For example, they want only the "web" translations when working on a web app and "mobile" translations for a mobile app. Right now, the API returns all translations, but they need a way to filter and get translations only for a specific platform.

# Solution

steps:-

Backend Update: We add a new "tag" argument to the API that returns translations. Only translations with the specified tag will be returned if one such as web is supplied. It will return all translations as before if no tag is supplied.

Java code modifications:

We will be updating the Java backend code that manages the /get-all-translations API. A new option to filter translations according to tags will be added.
Additionally, we'll ensure that the translations may be filtered by tag in the database.


JS SDK Changes: The JavaScript SDK (the tool developers use to fetch translations in their apps) will be updated so developers can pass a "tag" when they request translations.
