### ISSUE TITLE
Error No static resource favicon.ico on actuator paths

### ISSUE THREAD

**Issue by AUMakarov** [tolgee/tolgee-platform#2469]
**Describe the bug**
Request to /actuator/prometheus or /actuator/health generate error 
org.springframework.web.servlet.resource.NoResourceFoundException: No static resource favicon.ico

**To Reproduce**
1. Start docker compose
2. Open browser and navigate to http://localhost:8080/actuator/prometheus
3. See log:
`2024-09-17T20:21:07.986Z ERROR 1 --- [nio-8080-exec-1] io.tolgee.ExceptionHandlers              : org.springframework.web.servlet.resource.NoResourceFoundException: No static resource favicon.ico.`

**Versions and environment**
- Tolgee Platform version: Version: v3.72.0
- Environment: Docker version v27.2.0
- Browser: Chrome

**Comment by empz** [comment]
+1

**Comment by JanCizmar** [comment]
Hello, I believe this error is actually incorrectly handled 404, which is currently analyzed by @Anty0. Our production prometheus run correctly, so I think you just have it disabled.

**Comment by JanCizmar** [comment]
Oh! I see. The prometheus works. It just throws an error, when the browser searches for favicon.
