### ISSUE TITLE
email invitation for a new user 500 error

### ISSUE THREAD

**Issue by killershotpy** [tolgee/tolgee-platform#2488]
in the free “self-hosted” plan, encountered a 500 error when trying to invite a user on the “email” tab:

1. I open “members”, it doesn't matter whether it's through “organization” or “project”:
![image](https://github.com/user-attachments/assets/157d6e21-c2dd-4084-9586-b015d1c135eb)
2. I specify a valid e-mail address with basic view-only settings (in fact, access rights to the project can be anything), and getting 500 error:
![image](https://github.com/user-attachments/assets/f9c0a3a9-3d43-40a4-86f3-eee8ab37d703)

tracing the error from devtools browser:
![image](https://github.com/user-attachments/assets/d83c3d90-f9e4-40df-917b-dfd0af968266)
```
payload:
{"type":"VIEW","email":"QA@techsolutionsltd.kz"}
response:
{"code":"unexpected_error_occurred","params":["java.lang.IllegalStateException"]}
```

- Tolgee Platform version: v3.54.6
- Environment: Launched with "**Helm Chart**" in **Kubernetes**
- Browser: Google Chrome 113.0.5672.127 (64 bit) (cohort: Stable)

**Comment by JanCizmar** [comment]
Jus a quick question: How do you have configured your SMTP in the server config?

**Comment by killershotpy** [comment]
unfortunately, there's no logging...
there is no SMTP server configuration, that is strictly “basic settings” after repository installation

**Comment by killershotpy** [comment]
> In that case you will have to configure the SMTP if you want to send e-mails.

hello

Yes, recently found out that we didn't have the SMTP service configured in the container for this functionality

I guess that's the problem.
thanks.

But still, as a user I expect to see not 500 but an informational message in the UI to tell me about it.

since configuration and support can be handled by 1 team.
and working inside and creating new users by another team.
