### ISSUE TITLE
Search API is not functioning as expected

### ISSUE THREAD

**Issue by webard** [tolgee/tolgee-platform#2492]
**Describe the bug**
Hello,
In my project, I have keys with dot notation, like `db.product.XX.name`, where XX is the identifier of the resource. Keys can have different resources, like `db.category.XX.name`, or fields, like `db.product.XX.description`.

When I search for keys using the full key (e.g., `/v2/projects/8/keys/search?search=db.product.2229.name`), I expect the API to return information about this specific key. However, what I receive instead is:

```
{
  "_embedded": {
    "keys": [
      {
        "translation": null,
        "baseTranslation": null,
        "description": null,
        "namespace": "string",
        "name": "db.product.108.name",
        "id": 1001758083
      },
      {
        "translation": null,
        "baseTranslation": null,
        "description": null,
        "namespace": "string",
        "name": "db.product.233972.name",
        "id": 1001758084
      }
    ]
  },
```

Or, in some cases, no results at all, even though the keys exist in the Tolgee project.

**Expected behavior**
When I query the API for `db.product.2229.name`, I expect it to return information specific to that key.

**Versions and environment**
- Tolgee Platform v3.74.3

**Comment by JanCizmar** [comment]
Hello, search doesn't guarantee exact key name will be matched. It is not the parameter you should use if you need to match exact key. There are `filterNamespace` and `filterKeyName` parameters.
