### ISSUE TITLE
Unable to Access Slack Community Link

### ISSUE THREAD

**Issue by Ayushjhawar8** [tolgee/tolgee-platform#2513]
**Describe the bug**
I am unable to access the Slack community link provided in the README file of the Toglee repository.

**To Reproduce**
1. Go to the Toglee repository homepage.
2. Locate the Slack community link in the README file.
3. Click on the link.
4. See error.

**Expected behavior**
I expected to be redirected to the Toglee Slack community where I can join and interact with other users.

**Screenshots**
![image](https://github.com/user-attachments/assets/fdbb13ab-9969-4c62-8247-e5a6e54692ff)

**Comment by Ayushjhawar8** [comment]
just update the new link in the repo and it will be fixed as simple as that

**Comment by JanCizmar** [comment]
Fixed! Thx for reporting!
