### ISSUE TITLE
Unify badge-like components in the activity

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2516]
We have different styles of visuals for e.g. for language.

All the badge-like items should look the same. (less gray, pink)
![image](https://github.com/user-attachments/assets/c65138a9-5496-45a7-9980-b198e9a71458)

**Comment by Avii-KS** [comment]
Hi @JanCizmar  can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by JanCizmar** [comment]
I have assigned you. Have fun.
