### ISSUE TITLE
Tolgee does not strip key's trailing whitespaces when craeting new translation

### ISSUE THREAD

**Issue by mehrdad-khojastefar** [tolgee/tolgee-platform#2522]
**Describe the bug**
When adding new translation with trailing whitespaces, tolgee does not strip them. 

**To Reproduce**
1. Go to 'projects'
2. Go to 'translations'
3. Click on 'Add'
4. Create a translation with trailing whitespace in it's key
5. Now the value does not get shown

**Expected behavior**
When adding a key with trailing whitespaces, the expected behavior is to strip them. So that it does not make confusions, since I guess that trailing whitespaces are there by mistake.  

**Versions and environment**
- Tolgee Platform version: v3.61.0
- Environment: Kubernetes

**Comment by JanCizmar** [comment]
Hello! We cannot prevent users from using keys with trailing or leading white spaces. If someone has this for example in json they're importing, we have to preserve the spaces to not break their projects.

I understand that for some cases this might be weird, but it's a fact of life.
