### ISSUE TITLE
Footer is so messy some links can be differentiated, and social links can be added in another section

### ISSUE THREAD

**Issue by NishantRana07** [tolgee/tolgee-platform#2524]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions and environment**
- Tolgee Platform version: [e.g. 2.63.1]
- Environment: Docker version, Java Version, OS, etc.
- Browser: (In cases of UI issues)

**Additional context**

**Comment by JanCizmar** [comment]
This issue has no valid body. Please describe it properly.
