### ISSUE TITLE
Ordering professional translation - first version

### ISSUE THREAD

**Issue by ZuzanaOdstrcilova** [tolgee/tolgee-platform#2530]
Create a new order using tasks.
Design and notes here: https://www.figma.com/design/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?node-id=1713-29712

**Comment by stepan662** [comment]
Frontend
[ ] UI for managing agencies
[ ] UI for creating order
Backend 
[ ] DB models and controllers for agencies
[ ] Endpoint for creating order - email for agency
[ ] Invitation updates
