### ISSUE TITLE
🤩 Create Meal Prep Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2533]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Habit Tracker 🍴

Develop a simple habit-tracking app where users can create new habits, set daily or weekly goals, and check them off as completed. 

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by Akash-cloud001** [comment]
Hi! 👋

I’d like to take on the task of developing the habit-tracking app. I plan to implement features for creating new habits, setting daily or weekly goals, and marking them as completed. Please assign this issue to me!

Thanks!

**Comment by RashmitTopG** [comment]
I would also like to work on this.

**Comment by marketachalupnikova** [comment]
Thanks a lot @Akash-cloud001 and @RashmitTopG. You can both create your projects! I just assigned the issue to both of you.
