### ISSUE TITLE
🤩 Create Flag Quiz (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2536]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Flag Quiz 🎌

Develop a simple app that quizzes users on world flags. Users are shown a random flag, and they must guess the corresponding country.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by Vaishali785** [comment]
Hi @marketachalupnikova , I'd like to work on this issue. Could you please assign it to me?

**Comment by marketachalupnikova** [comment]
Sure, it's yours! Thanks for contributing 🙌

**Comment by marketachalupnikova** [comment]
Assigning to you @parth-1372. Thanks for your contribution!

**Comment by Vaishnavi-Raykar** [comment]
@marketachalupnikova , I'm interested.

**Comment by Vaishnavi-Raykar** [comment]
@marketachalupnikova
@JanCizmar

Please my both PR -

Multilingual Phrasebook https://github.com/tolgee/tolgee-platform/issues/2538
Flag Quiz https://github.com/tolgee/tolgee-platform/issues/2536

**Comment by Vaishali785** [comment]
Hi @marketachalupnikova , kindly check my PR and if any changes are required please let me know.

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , Please assign this task to me.
Would love to complete it.
