### ISSUE TITLE
🤩 Create Random Movie Picker (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2545]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Random Movie Picker 🎥

Develop a simple app where users can input their favorite movie genres, and the app suggests random movies to watch.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by yashp4858** [comment]
Hey @marketachalupnikova, I would like to work on this issue.

**Comment by marketachalupnikova** [comment]
Glad to hear that, thank you @yashp4858 🙌

**Comment by yashp4858** [comment]
Hey @marketachalupnikova,

I am trying to run the backend on my localhost. First, I executed the following command to run with Gradle:
./gradlew server-app:bootRun --args='--spring.profiles.active=dev'This step built successfully. 

However, when I run the command:
./gradlew diffChangeLog or ./gradlew diffChangeLog --no-daemon I receive the error: "permission denied while trying to connect to the Docker daemon socket."

**Comment by yashp4858** [comment]
@marketachalupnikova i am also getting this error,
> Task :stopDbChangelogContainer
tolgee_postgres_dbschema

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ee-app:diffChangelog'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':data:diffChangelog'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
so i need to add my local database

**Comment by stepan662** [comment]
Hey, I think running tolgee locally for this task is not necessary. Or if you really want to, it's easier to do so with Docker https://tolgee.io/platform/self_hosting/running_with_docker

But you can easily use cloud version, just sign up, you don't have to pay anything.

**Comment by yashp4858** [comment]
thanks @stepan662

**Comment by yashp4858** [comment]
hey @stepan662 i am creating this demo app in angular but how to get api key and apiurl ?

**Comment by marketachalupnikova** [comment]
Hi @Toprun123 sure! thanks a lot for your contribution

**Comment by Toprun123** [comment]
Thank you too. I started working on a demo using ruby on rails. That's okay right?

**Comment by Toprun123** [comment]
I've opened a PR for this:  #2641

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , Please assign this task to me.
I would love to complete it.

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , Please assign this task to me.
I would love to complete it.
