### ISSUE TITLE
🤩 Create Workout Dice (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2548]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Workout Dice 🏋️

Create a simple app that simulates a dice roll, where each face of the dice corresponds to a different exercise (like push-ups, sit-ups, or squats). The app generates a workout routine based on the dice rolls for users who want a spontaneous workout!

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by Akash-cloud001** [comment]
Hi! 👋

I’d like to take on the task of creating the dice roll workout app. I will implement features that correspond each face of the dice to different exercises, generating spontaneous workout routines for users. Please assign this issue to me!

Thanks!

**Comment by RashmitTopG** [comment]
I would also like to work on this.

**Comment by marketachalupnikova** [comment]
Great, I assigned the task to both of you. Curious to both of your projects! Good luck

**Comment by RashmitTopG** [comment]
Can you please check my PR.

**Comment by marketachalupnikova** [comment]
Thanks for the contribution @RashmitTopG! To me, it looks very nice. @JanCizmar will soon assign the points and I'll reach out back to you about the swag package.

**Comment by Akash-cloud001** [comment]
@marketachalupnikova, I have submitted my PR. please review it. Thank you

**Comment by Akash-cloud001** [comment]
Hey @marketachalupnikova, are there any updates regarding my PR

**Comment by marketachalupnikova** [comment]
hey, @Akash-cloud001, yes, @JanCizmar is working on it.

**Comment by RashmitTopG** [comment]
Hey @marketachalupnikova can you please check my PR too I made some changes on it.

**Comment by Akash-cloud001** [comment]
> hey, @Akash-cloud001, yes, @JanCizmar is working on it.

Thanks for the update

**Comment by RashmitTopG** [comment]
@marketachalupnikova can you please add the hacktoberfest and hacktoberfest accepted tags to the PR.

**Comment by JanCizmar** [comment]
Done!

**Comment by Akash-cloud001** [comment]
![image](https://github.com/user-attachments/assets/15d19afd-e9d7-477f-a051-e94ce1e32a28)
what could be the reason for this, and how can we solve this, can you guide us

**Comment by Akash-cloud001** [comment]
> ![image](https://private-user-images.githubusercontent.com/74132002/378500548-15d19afd-e9d7-477f-a051-e94ce1e32a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Njc5NjMsIm5iZiI6MTcyOTc2NzY2MywicGF0aCI6Ii83NDEzMjAwMi8zNzg1MDA1NDgtMTVkMTlhZmQtZTlkNy00NzdmLWEwNTEtZTk0Y2UxZTMyYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDExMDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZTUyODBiMzlkNDE2NjM1NmUxNDNjZGEwNTNlM2IwNGU1ZDJiMjRkMmFkYzllZGEyYmU2MDY0ZTI5ZmJhNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SVSthWpT_rBgylgvmkrTa9_KWfuuCUHQCEwMxOqH_-s) what could be the reason for this, and how can we solve this, can you guide us

Still same issue, any update will be appreciated

**Comment by JanCizmar** [comment]
My bad! Is it resolved now?

**Comment by Akash-cloud001** [comment]
Yes thanks for the help

**Comment by Akash-cloud001** [comment]
@JanCizmar and @marketachalupnikova It's been a week and I was waiting for how many points I scored in my submission.
So that I can evaluate my project. 
It would be great to hearing that from your end
Thank You.
