### ISSUE TITLE
🤩 Create Flag Country Finder (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2562]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Flag Country Finder 🌐

Build a simple app where users can select a flag from a dropdown menu, and the app will display information about the country, including its capital, population, and interesting facts.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by YogeshBabyOP** [comment]
Production Webpage using react.js👇
https://countryflagfinder.netlify.app/


I used this api for data retrieval 👇
https://restcountries.com/v3.1/all

**Comment by JanCizmar** [comment]
It's very nice, but so far it doesn't use Tolgee for localization. :)

**Comment by YogeshBabyOP** [comment]
for that it was asking for api keys, I create a project and generate some api keys, but it doesn't working :)

**Comment by marketachalupnikova** [comment]
sorry to hear that! You can check the example react app with Tolgee integration here: https://github.com/tolgee/tolgee-js/tree/main/packages/react

**Comment by Sparklegift** [comment]
@marketachalupnikova 
I'd like to work on this

**Comment by marketachalupnikova** [comment]
thank you @Sparklegift Looking forward to your contribution!

**Comment by YogeshBabyOP** [comment]
> use Tolgee for localization. :

Thank you for the resource, here is the final version using Tolgee for localization.

This was the production url : https://tolgee-flag-finder.vercel.app/

**Comment by YogeshBabyOP** [comment]
@maetachalupnikova can I create a PR now and add into demos/ ??

**Comment by YogeshBabyOP** [comment]
@marketachalupnikova can I create a PR now and add into demos/ ??

**Comment by marketachalupnikova** [comment]
yes please @YogeshBabyOP
