### ISSUE TITLE
🤩 Create Mouse Memory Game (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2563]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Mouse Memory Game 🧠

Create a basic version of a memory game where users have to match pairs of mouse-themed cards. Start with just a few pairs to keep it simple.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by kaleaditya779** [comment]
Hey! I would love to contribute on this project. Can you assign it to me.. I would be very happy.

**Comment by marketachalupnikova** [comment]
Hi @kaleaditya779 great to hear that! I just assigned it to you. Thanks for your contribution!

**Comment by RashmitTopG** [comment]
I would like to work on this

**Comment by marketachalupnikova** [comment]
Great to hear that! you can start working on it. Thanks for your contribution

**Comment by kaleaditya779** [comment]
> Hi @kaleaditya779 great to hear that! I just assigned it to you. Thanks for your contribution!

https://github.com/tolgee/tolgee-platform/pull/2591
I have done it.

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , Please assign this task to me.
I would love to complete it.
