### ISSUE TITLE
🤩 Create Flag Emoji Converter (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2564]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Flag Emoji Converter 🌍

Create a simple app that converts country names into their respective flag emojis. Users can type a country name and see the corresponding flag emoji.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by marketachalupnikova** [comment]
Great, thanks! I just assigned it to you

**Comment by syamjir** [comment]
Hi@marketachalupnikova, Can i work on this? it already has one pull request with a small app that include the required fields

**Comment by marketachalupnikova** [comment]
Hi @syamjir! Sure, multiple people can work on the demos. Thanks for your contribution!

**Comment by marketachalupnikova** [comment]
sure, go ahead @ashishk1331

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , please assign this task to me.
I would love to complete it.
