### ISSUE TITLE
🤩 Create Countdown Timer (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2568]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Countdown Timer ⏳

Develop a countdown timer app where users can set a timer for specific events and receive notifications when the time is up.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by SyedMuzamilShah** [comment]
Could you please assign this issue to me? I'm ready to start working on it.

**Comment by marketachalupnikova** [comment]
Sure, it's yours! Thanks for contributing

**Comment by SyedMuzamilShah** [comment]
@marketachalupnikova I accidentally unassigned myself from this issue. Could you please reassign it to me? Thanks!

**Comment by Sparklegift** [comment]
@marketachalupnikova 
I'd like to work on this

**Comment by prathamesh424** [comment]
@JanCizmar  @marketachalupnikova  assign this issue to me

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , please assign this task to me.

**Comment by anshuman-rai-27** [comment]
Hey @marketachalupnikova , please assign this task.

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , please assign this task to me.
I would love to complete it.
