### ISSUE TITLE
[bug]: fix the slack community link

### ISSUE THREAD

**Issue by bandhan-majumder** [tolgee/tolgee-platform#2602]
![image](https://github.com/user-attachments/assets/8fd95661-a9da-4979-a793-4e08fc1ee6e0)
please add a new link to join the slack community on line no `68` on `README.md`

**Comment by TSP06** [comment]
Assign me this @bandhan-majumder

**Comment by abhirajadhikary06** [comment]
It is completely fine and no issue persists.

**Comment by bandhan-majumder** [comment]
> It is completely fine and no issue persists.

share me the link then please

**Comment by JanCizmar** [comment]
@bandhan-majumder https://tolg.ee/slack I hope this one is used in the README, too.

**Comment by bandhan-majumder** [comment]
> @bandhan-majumder https://tolg.ee/slack I hope this one is used in the README, too.

Thanks
