### ISSUE TITLE
No machine translation engines displayed for selection in translation settings

### ISSUE THREAD

**Issue by ammassey** [tolgee/tolgee-platform#2703]
**Describe the bug**
I have an empty view of machine translation engines to enable when looking accessing the language settings in the Machine Translation view.  This is occurring on front end/ backend build from branch reflecting most current "main"

**To Reproduce**
1. Go to active Project
2. Click on Languages
3. Navigate to "Machine Translation"
4. Click on Cog for language to access settings
5. See missing MT engines

**Expected behavior**
I expect to see Tolgee supported MT Engines that can be enabled or disabled

**Screenshots**
Expected
<img width="641" alt="Screenshot 2024-11-19 at 6 38 10 PM" src="https://github.com/user-attachments/assets/cdf4edf9-38c6-4b38-80ce-0ef6c75810c1">

Actual
<img width="603" alt="Screenshot 2024-11-19 at 6 35 15 PM" src="https://github.com/user-attachments/assets/9b7adb8f-6a8d-4090-8f8d-6993a6e25106">

**Versions and environment**
- Tolgee Platform version:  Currently build off of most current main. Local deployment
- Environment: Docker version: 27.3.1, Java Version: 21.0.5, OS: MacOS
- Browser: Chrome

**Additional context**
Initially caught when trying to run batch processing for machine translations. The process would go through with no error, but no MT results would populate.

**Comment by JanCizmar** [comment]
Hello!

This looks like a configuration issue. Have you provided the machine configuration properties for at lease one of the provider?

Since you're using your custom build, you should be able to debug this issue yourself and provide more detailed information about the bug.

We cannot provide support for forked versions unless you provide us the code.
