### ISSUE TITLE
Internal: Create automated tests for reset password requests

### ISSUE THREAD

**Issue by StaNov** [tolgee/tolgee-platform#2727]
In #2724, limiting reset password requests were implemented without tests.

Add tests covering the code added.

Marking as `for-superday` since it looks like a good task where no domain knowledge is needed.

**Comment by subchat** [comment]
Hello sir, I can confirm that the reset password requests were implemented properly and Rate Limit is rightfully Implemented.

**Comment by JanCizmar** [comment]
I believe the `@RateLimit` annotation is generally tested, so it's probably not necessary to test it specifically for the the password request or login endpoins.

**Comment by subchat** [comment]
@JanCizmar , Sir, here it was implemented but in my recent report(as you asked me to report individually in Github) I showed you that other end points for api - like "generate-token" is not rate limited and gives a Jwt token that leads to account takeover and IDOR. Please check it out.
