### ISSUE TITLE
Improve the UX of Keyboard shortcuts

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2728]
- [x] Make the shortcuts more easily acessible - I wasn't able to find them. I would also put a link to them to the `?` section in the left down corner
- [x] Add to the keyboard shortcuts the SHIFT multiselect https://github.com/tolgee/tolgee-platform/pull/2712

**Comment by stepan662** [comment]
I'd be for adding a link to `?` section, what do you think @ZuzanaOdstrcilova

**Comment by ZuzanaOdstrcilova** [comment]
Yes, it was even in some design:)
![image](https://github.com/user-attachments/assets/f8f37f22-606a-4dc6-9125-3a63071fb558)
