### ISSUE TITLE
Saving key context is slow

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#2741]
Saving context in "Tolgee itself" project takes about 20s. It seems to be getting progressively slower, probably because the number of "context connections" is increasing.

Steps to reproduce:
 - connect tolgee platfrom FE to "Tolgee itself" project
 - Edit/create/add screenshot to any key (saving is slow)

Investigate the issue, find a possible improvement.

**Comment by JanCizmar** [comment]
Please follow the template: provide steps to reproduce.
