### ISSUE TITLE
Tolgee 3.85.0 never starts.

### ISSUE THREAD

**Issue by mzch** [tolgee/tolgee-platform#2764]
**Describe the bug**
Tolgee 3.85.0 never starts because of SQL error

**To Reproduce**
1. Download 3.85.0
2. Update Tolgee from 3.84.3 to 3.85.0
3. Start Tolgee

**Expected behavior**
Update database and start normally

**Error Log**
Please see https://gist.github.com/mzch/bbf57f2df2b1fb4321a31ad42f4e95c0

**Versions and environment**
- Tolgee Platform version: 3.85.0
- Environment: Java Version: 23.0.1, OS: Debian 12.8 (bookworm)

**Comment by marticliment** [comment]
Same here, self-hosted Tolgee on ubuntu 24.04 x64 (jar executable).

The traceback is the same as the one attached by OP.

Downgrading to 3.84.x allows the server to run again

**Comment by stepan662** [comment]
Looking into it

**Comment by stepan662** [comment]
Ok, fix on the way https://github.com/tolgee/tolgee-platform/pull/2765

**Comment by mzch** [comment]
Thanks, @stepan662 ! I'm looking forward to next release.

**Comment by StaNov** [comment]
@mzch, @marticliment, thank you for letting us know, it means a lot! :heart:
