### ISSUE TITLE
Android .xml export does not export Chinese Characters as keys

### ISSUE THREAD

**Issue by jojoclt** [tolgee/tolgee-platform#2775]
**Describe the bug**
When setting keys to Chinese Characters instead of English as keys, when click export to Android .xml, it will show __ as keys

And I think the header of the xml is wrong, normally for android it should be 3rd screenshot
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/1429ee21-665f-4220-b379-c71add4a11d9)

![image](https://github.com/user-attachments/assets/03e7b9ba-ea81-4cf1-b9c0-dd0cc3c11032)
![image](https://github.com/user-attachments/assets/4039758f-130d-4bbb-b605-1dbbfcbe854d)
![image](https://github.com/user-attachments/assets/f47396f2-d0d4-4e2d-8444-add9f1f62032)

**Versions and environment**
- Tolgee Platform version: [e.g. 2.63.1]
- Environment: Docker version, Java Version, OS, etc.
- Browser: (In cases of UI issues)

**Additional context**

**Comment by JanCizmar** [comment]
Hello, thanks for reporting. I don't suspect the header. It has it's own purpose. I believe there's something wrong going wrong with the writer. Can you please investigate it @Anty0?

**Comment by Anty0** [comment]
Hi! Thanks for the report!

This is a deliberate decision. Android uses the keys to generate resource classes, and using unsupported characters might cause an issue. To avoid that, only `[a-zA-Z0-9_]` characters are kept. I could not find the limits for naming these keys in the official Android documentation, but other localization tools use similar limits.

@jojoclt Do you know any documentation where we might find a broader list of supported characters for keys in Android XML files?

Closing the issue for now, but feel free to reopen!
