### ISSUE TITLE
Support for Microsoft CDN cache purging (not azure frontdoor)

### ISSUE THREAD

**Issue by mohamediburan** [tolgee/tolgee-platform#2791]
**Is your feature request related to a problem? Please describe.**
Currently, azure cache purging doesn't seem to be working with the classic Microsoft CDN. The endpoints for hitting the azure frontdoor for purging is hard-coded in the code which only supports azure frontdoor endpoints.

**Describe the solution you'd like**
Would like a config or some option to choose between afd endpoints and Microsoft CDN endpoints.

**Comment by JanCizmar** [comment]
Hello! 

Thanks for reaching out!

We have stopped using Microsoft Azure for CDN. So we are not going to implement this by ourselves. However! PRs are welcomed! 🤩

**Comment by mohamediburan** [comment]
Hi @pasotee going forward, tolgee will only support S3? This puts us in a tough spot.

Alright. I'll see if I can come up with an PR.

**Comment by JanCizmar** [comment]
@mohamediburan No, we will keep supporting the Azure Blob & FrontDoor. We just won't add the support for new CDN providers unless some company with advanced subscription will request this.

However, adding new cache purging is an easy task, so creating a PR should not be a problem for you. 🚀

**Comment by mohamediburan** [comment]
> Hey @mohamediburan, did you intend to ping me or Jan?
I was trying to ping Jan. Somehow mistyped the username.
