### ISSUE TITLE
Key description

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#918]
Enable users to manage text description of key

**Comment by ZuzanaOdstrcilova** [comment]
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=101%3A889

**Comment by jdimeo** [comment]
Still interested in this

**Comment by stepan662** [comment]
Implemented here: https://github.com/tolgee/tolgee-platform/pull/2092
