### ISSUE TITLE
Ability to resend registration email

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-platform#968]
Update by @JanCizmar:

Currently, the user cannot login before they have verified e-mail.
- [ ] Enable to the user to login, but without any permissions, telling them, they should verify 
- [ ] Add backend endpoint to resend the verification link
- [ ] Add the "request verify" screen to the frontend
- [ ] We need to limit the number of the requests per hour to some constant per e-mail and ip

**Comment by JanCizmar** [comment]
@huglx Ivan, can you please look into this? It looks like nice issue for you.

**Comment by huglx** [comment]
> @huglx Ivan, can you please look into this? It looks like nice issue for you.

OK, I'll look into this

**Comment by JanCizmar** [comment]
I've assigned this to @ZuzanaOdstrcilova to prepare the UI for the new flow.

**Comment by ZuzanaOdstrcilova** [comment]
There will be an notice after registration on top. Link will resend the email to an address from registration.
https://www.figma.com/file/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?type=design&node-id=1535%3A49438&mode=design&t=e9oXkVgblBgV35rV-1
