### ISSUE TITLE
Instance administration

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-platform#974]
It'd be nice to have a way for administrators (I noticed there's already an `ADMIN` flag on users) to be able to see all the users, organizations, and projects living on the instance, and manage them. This could also allow disabling registrations on an instance, and creating accounts manually for people who should be allowed to log in.

As tolgee.io also provides Tolgee as a service, management can quickly become an issue and a nightmare to deal with when people decide to start abusing the platform (we can't have nice things in this world 😔). Maybe it'll also become a handy place to put tools when paid plans roll out as well, who knows!

**Comment by JanCizmar** [comment]
Hi there. You are totally right. We will add it to our road map, hopefully we are going to find resources to make it happen as soon as possible.
