### ISSUE TITLE
Use of "username" term is confusing

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-platform#975]
While looking at the source code (and on the login page), I saw that in a lot of places (including in the database), the email address is referred to as "username", which was quite confusing to me at first. On the login screen, it makes it ambiguous whether the app is asking for the name you set while registering, or the email address. It also made me confused at first when browsing the source code, as I once again didn't expect the username to be a reference to the email address.

While renaming the database field and request objects internally may be a breaking change, changing the wording of "username" to "email" or "login" on the login screen would be less confusing to end users, and would be more consistent internally.

**Comment by JanCizmar** [comment]
You are right once again.

**Comment by KaKi87** [comment]
Today, when trying to login to Tolgee, I read *username*, so I tried `KaKi87`, and it took me a few minutes, to realize that my password was correct, but that I just needed to add `@pm.me` to my "username" because it needs an email address.

This is bad UX.
