### ISSUE TITLE
Backend documentation

### ISSUE THREAD

**Issue by eweren** [tolgee/tolgee-platform#999]
I am trying to get the spring backend up and running in order to try things out regarding webhooks. Since I am new to spring I don't have experience in getting those kind of projects up and running. Therefore it would be nice to have some documentation.

**Comment by JanCizmar** [comment]
Will do tommorow.

**Comment by JanCizmar** [comment]
I created this Wiki page describing how to run all you need. Tell me whether it's understandable. 

https://github.com/tolgee/tolgee-platform/wiki/Development

**Comment by eweren** [comment]
This helps a lot, thank you! What do I have to configure to get something similar to hot reload to work?
And I guess the `clone`-command should be edited to `git clone git@github.com:tolgee/tolgee-platform.git`

**Comment by JanCizmar** [comment]
> This helps a lot, thank you! What do I have to configure to get something similar to hot reload to work?

Hmm... You mean on the backend? Do you use Idea CE or Ultimate?

> And I guess the clone-command should be edited to git clone git@github.com:tolgee/tolgee-platform.git

Right! Thanks.

**Comment by eweren** [comment]
I'm using IDEA CE

**Comment by JanCizmar** [comment]
Since Kotlin/Java are languages which need compilation. You have to rebuild the project (there is a hammer in top right). If project is rebuilt and you are running it, it is automatically restarted.

**Comment by JanCizmar** [comment]
I think this is done.
